-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [evm_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace StdBorrowRefNew

/-- [core::cell::Cell]
    Source: '/rustc/library/core/src/cell.rs', lines 315:0-315:26
    Name pattern: [core::cell::Cell]
    Visibility: public -/
@[rust_type "core::cell::Cell"]
axiom core.cell.Cell (T : Type) : Type

/-- [core::cell::{core::cell::Cell<T>}::replace]:
    Source: '/rustc/library/core/src/cell.rs', lines 513:4-513:44
    Name pattern: [core::cell::{core::cell::Cell<@T>}::replace]
    Visibility: public -/
@[rust_fun "core::cell::{core::cell::Cell<@T>}::replace"]
axiom core.cell.Cell.replace {T : Type} : core.cell.Cell T → T → Result T

/-- [core::cell::{core::cell::Cell<T>}::get]:
    Source: '/rustc/library/core/src/cell.rs', lines 555:4-555:32
    Name pattern: [core::cell::{core::cell::Cell<@T>}::get]
    Visibility: public -/
@[rust_fun "core::cell::{core::cell::Cell<@T>}::get"]
axiom core.cell.Cell.get
  {T : Type} (markerCopyInst : core.marker.Copy T) :
  core.cell.Cell T → Result T

/-- [core::cell::UNUSED]
    Source: '/rustc/library/core/src/cell.rs', lines 949:0-949:27
    Name pattern: [core::cell::UNUSED] -/
@[global_simps, irreducible, rust_const "core::cell::UNUSED"]
def core.cell.UNUSED : Std.Isize := 0#isize

/-- [core::cell::is_reading]:
    Source: '/rustc/library/core/src/cell.rs', lines 957:0-957:45
    Name pattern: [core::cell::is_reading] -/
@[rust_fun "core::cell::is_reading"]
def core.cell.is_reading (x : Std.Isize) : Result Bool := do
  ok (x > core.cell.UNUSED)

/-- [core::cell::BorrowRef]
    Source: '/rustc/library/core/src/cell.rs', lines 1555:0-1555:20
    Name pattern: [core::cell::BorrowRef] -/
@[rust_type "core::cell::BorrowRef"]
structure core.cell.BorrowRef where
  borrow : core.cell.Cell Std.Isize

/-- [core::cell::{core::cell::BorrowRef<'b>}::new]:
    Source: '/rustc/library/core/src/cell.rs', lines 1561:4-1561:74
    Name pattern: [core::cell::{core::cell::BorrowRef<'b>}::new] -/
@[rust_fun "core::cell::{core::cell::BorrowRef<'b>}::new"]
def core.cell.BorrowRef.new
  (borrow : core.cell.Cell Std.Isize) :
  Result (Option core.cell.BorrowRef)
  := do
  let i ← core.cell.Cell.get core.marker.CopyIsize borrow
  let b ← lift (core.num.Isize.wrapping_add i 1#isize)
  let b1 ← core.cell.is_reading b
  if b1
  then let _ ← core.cell.Cell.replace borrow b
       ok (some { borrow })
  else ok none

end StdBorrowRefNew
