-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_word_extracted]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace WordExtracted

/-- [ruint::algorithms::add::carrying_add]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/algorithms/add.rs', lines 6:0-6:73
    Name pattern: [ruint::algorithms::add::carrying_add]
    Visibility: public -/
@[rust_fun "ruint::algorithms::add::carrying_add"]
def ruint.algorithms.add.carrying_add
  (lhs : Std.U64) (rhs : Std.U64) (carry : Bool) :
  Result (Std.U64 × Bool)
  := do
  let (result, carry_1) ← lift (core.num.U64.overflowing_add lhs rhs)
  let i ← lift (UScalar.cast_fromBool .U64 carry)
  let (result1, carry_2) ← lift (core.num.U64.overflowing_add result i)
  ok (result1, carry_1 || carry_2)

/-- [ruint::algorithms::add::borrowing_sub]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/algorithms/add.rs', lines 24:0-24:75
    Name pattern: [ruint::algorithms::add::borrowing_sub]
    Visibility: public -/
@[rust_fun "ruint::algorithms::add::borrowing_sub"]
def ruint.algorithms.add.borrowing_sub
  (lhs : Std.U64) (rhs : Std.U64) (borrow : Bool) :
  Result (Std.U64 × Bool)
  := do
  let (result, borrow_1) ← lift (core.num.U64.overflowing_sub lhs rhs)
  let i ← lift (UScalar.cast_fromBool .U64 borrow)
  let (result1, borrow_2) ← lift (core.num.U64.overflowing_sub result i)
  ok (result1, borrow_1 || borrow_2)

/-- [kasane_word_extracted::carrying_add]:
    Source: 'lib.rs', lines 1:0-3:1
    Visibility: public -/
def carrying_add
  (lhs : Std.U64) (rhs : Std.U64) (carry : Bool) :
  Result (Std.U64 × Bool)
  := do
  ruint.algorithms.add.carrying_add lhs rhs carry

/-- [kasane_word_extracted::borrowing_sub]:
    Source: 'lib.rs', lines 5:0-7:1
    Visibility: public -/
def borrowing_sub
  (lhs : Std.U64) (rhs : Std.U64) (borrow : Bool) :
  Result (Std.U64 × Bool)
  := do
  ruint.algorithms.add.borrowing_sub lhs rhs borrow

end WordExtracted
