-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_ledger_timestamp_probe]: function definitions
import Aeneas
import LedgerDurationExtract.Types
import LedgerDurationExtract.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace LedgerDuration

/-- [core::convert::num::{impl core::convert::TryFrom<u128, core::num::error::TryFromIntError> for u64}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 383:12-383:64
    Name pattern: [core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from"]
def U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from
  (u : Std.U128) :
  Result (core.result.Result Std.U64 core.num.error.TryFromIntError)
  := do
  let i ← lift (UScalar.cast .U128 core.num.U64.MAX)
  if u > i
  then ok (core.result.Result.Err core.num.error.IntErrorKind.PosOverflow)
  else let i1 ← lift (UScalar.cast .U64 u)
       ok (core.result.Result.Ok i1)

/-- Trait implementation: [core::num::error::{impl core::fmt::Debug for core::num::error::TryFromIntError}]
    Source: '/rustc/library/core/src/num/error.rs', lines 8:9-8:14
    Name pattern: [core::fmt::Debug<core::num::error::TryFromIntError>] -/
@[reducible, rust_trait_impl
  "core::fmt::Debug<core::num::error::TryFromIntError>"]
def core.num.error.TryFromIntError.Insts.CoreFmtDebug : core.fmt.Debug
  core.num.error.TryFromIntError := {
  fmt := core.num.error.TryFromIntError.Insts.CoreFmtDebug.fmt
}

/-- [kasane_ledger_timestamp_probe::timestamp::{impl core::ops::arith::Add<core::time::Duration, kasane_ledger_timestamp_probe::timestamp::TimeStamp> for kasane_ledger_timestamp_probe::timestamp::TimeStamp}::add]:
    Source: 'timestamp.rs', lines 68:4-74:5
    Visibility: public -/
def timestamp.TimeStamp.Insts.CoreOpsArithAddDurationTimeStamp.add
  (self : timestamp.TimeStamp) (d : core.time.Duration) :
  Result timestamp.TimeStamp
  := do
  let i ← core.time.Duration.as_nanos d
  let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i
  let i1 ←
    core.result.Result.unwrap core.num.error.TryFromIntError.Insts.CoreFmtDebug
      r
  let i2 ← lift (core.num.U64.saturating_add self.timestamp_nanos i1)
  ok { timestamp_nanos := i2 }

/-- [kasane_ledger_timestamp_probe::timestamp::{kasane_ledger_timestamp_probe::timestamp::TimeStamp}::from_nanos_since_unix_epoch]:
    Source: 'timestamp.rs', lines 41:4-45:5
    Visibility: public -/
def timestamp.TimeStamp.from_nanos_since_unix_epoch
  (nanos : Std.U64) : Result timestamp.TimeStamp := do
  ok { timestamp_nanos := nanos }

/-- [kasane_ledger_timestamp_probe::add_time]:
    Source: 'lib.rs', lines 4:0-6:1
    Visibility: public -/
def add_time
  (nanos : Std.U64) (duration : Std.U64) : Result timestamp.TimeStamp := do
  let ts ← timestamp.TimeStamp.from_nanos_since_unix_epoch nanos
  let d ← core.time.Duration.from_nanos duration
  timestamp.TimeStamp.Insts.CoreOpsArithAddDurationTimeStamp.add ts d

/-- [kasane_ledger_timestamp_probe::timestamp::{impl core::ops::arith::Sub<core::time::Duration, kasane_ledger_timestamp_probe::timestamp::TimeStamp> for kasane_ledger_timestamp_probe::timestamp::TimeStamp}::sub]:
    Source: 'timestamp.rs', lines 80:4-86:5
    Visibility: public -/
def timestamp.TimeStamp.Insts.CoreOpsArithSubDurationTimeStamp.sub
  (self : timestamp.TimeStamp) (d : core.time.Duration) :
  Result timestamp.TimeStamp
  := do
  let i ← core.time.Duration.as_nanos d
  let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i
  let i1 ←
    core.result.Result.unwrap core.num.error.TryFromIntError.Insts.CoreFmtDebug
      r
  let i2 ← lift (core.num.U64.saturating_sub self.timestamp_nanos i1)
  ok { timestamp_nanos := i2 }

/-- [kasane_ledger_timestamp_probe::sub_time]:
    Source: 'lib.rs', lines 7:0-9:1
    Visibility: public -/
def sub_time
  (nanos : Std.U64) (duration : Std.U64) : Result timestamp.TimeStamp := do
  let ts ← timestamp.TimeStamp.from_nanos_since_unix_epoch nanos
  let d ← core.time.Duration.from_nanos duration
  timestamp.TimeStamp.Insts.CoreOpsArithSubDurationTimeStamp.sub ts d

end LedgerDuration
