-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_ledger_timestamp_probe]: type definitions
import Aeneas
import LedgerDurationExtract.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace LedgerDuration

/-- [core::num::error::IntErrorKind]
    Source: '/rustc/library/core/src/num/error.rs', lines 88:0-88:21
    Name pattern: [core::num::error::IntErrorKind]
    Visibility: public -/
@[discriminant isize, rust_type "core::num::error::IntErrorKind"]
inductive core.num.error.IntErrorKind where
| Empty : core.num.error.IntErrorKind
| InvalidDigit : core.num.error.IntErrorKind
| PosOverflow : core.num.error.IntErrorKind
| NegOverflow : core.num.error.IntErrorKind
| Zero : core.num.error.IntErrorKind
| NotAPowerOfTwo : core.num.error.IntErrorKind

/-- [kasane_ledger_timestamp_probe::timestamp::TimeStamp]
    Source: 'timestamp.rs', lines 28:0-31:1
    Visibility: public -/
structure timestamp.TimeStamp where
  timestamp_nanos : Std.U64

end LedgerDuration
