/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApiError = { 'Internal' : ApiErrorDetail } |
  { 'Rejected' : ApiErrorDetail } |
  { 'InvalidArgument' : ApiErrorDetail };
export interface ApiErrorDetail { 'code' : string, 'message' : string }
export interface BlockView {
  'tx_list_hash' : Uint8Array,
  'block_hash' : Uint8Array,
  'number' : bigint,
  'timestamp' : bigint,
  'tx_ids' : Array<Uint8Array>,
  'state_root' : Uint8Array,
  'parent_hash' : Uint8Array,
}
export interface DecodedTxView {
  'to' : [] | [Uint8Array],
  'value' : Uint8Array,
  'max_priority_fee_per_gas' : [] | [bigint],
  'from' : Uint8Array,
  'max_fee_per_gas' : [] | [bigint],
  'chain_id' : [] | [bigint],
  'nonce' : bigint,
  'gas_limit' : bigint,
  'input' : Uint8Array,
  'gas_price' : [] | [bigint],
}
export interface DropCountView { 'code' : number, 'count' : bigint }
export interface EstimateIcTxOk {
  'suggested_max_fee_per_gas' : bigint,
  'suggested_max_priority_fee_per_gas' : bigint,
  'gas_limit' : bigint,
}
export interface EthBlockView {
  'txs' : EthTxListView,
  'base_fee_per_gas' : [] | [bigint],
  'beneficiary' : Uint8Array,
  'block_hash' : Uint8Array,
  'number' : bigint,
  'timestamp' : bigint,
  'gas_limit' : [] | [bigint],
  'gas_used' : [] | [bigint],
  'state_root' : Uint8Array,
  'parent_hash' : Uint8Array,
}
export interface EthLogFilterView {
  'limit' : [] | [number],
  'topic0' : [] | [Uint8Array],
  'topic1' : [] | [Uint8Array],
  'address' : [] | [Uint8Array],
  'to_block' : [] | [bigint],
  'from_block' : [] | [bigint],
}
export interface EthLogItemView {
  'tx_index' : number,
  'log_index' : number,
  'data' : Uint8Array,
  'block_number' : bigint,
  'topics' : Array<Uint8Array>,
  'address' : Uint8Array,
  'eth_tx_hash' : [] | [Uint8Array],
  'tx_hash' : Uint8Array,
}
export interface EthLogsCursorView {
  'tx_index' : number,
  'log_index' : number,
  'block_number' : bigint,
}
export interface EthLogsPageView {
  'next_cursor' : [] | [EthLogsCursorView],
  'items' : Array<EthLogItemView>,
}
export interface EthReceiptLogView {
  'log_index' : number,
  'data' : Uint8Array,
  'topics' : Array<Uint8Array>,
  'address' : Uint8Array,
}
export interface EthReceiptView {
  'to' : [] | [Uint8Array],
  'effective_gas_price' : bigint,
  'status' : number,
  'l1_data_fee' : bigint,
  'tx_index' : number,
  'block_hash' : [] | [Uint8Array],
  'from' : [] | [Uint8Array],
  'logs' : Array<EthReceiptLogView>,
  'total_fee' : bigint,
  'block_number' : bigint,
  'operator_fee' : bigint,
  'eth_tx_hash' : [] | [Uint8Array],
  'gas_used' : bigint,
  'contract_address' : [] | [Uint8Array],
  'tx_hash' : Uint8Array,
}
export type EthTxListView = { 'Full' : Array<EthTxView> } |
  { 'Hashes' : Array<Uint8Array> };
export interface EthTxView {
  'raw' : Uint8Array,
  'tx_index' : [] | [number],
  'block_hash' : [] | [Uint8Array],
  'decode_ok' : boolean,
  'hash' : Uint8Array,
  'kind' : TxKindView,
  'block_number' : [] | [bigint],
  'eth_tx_hash' : [] | [Uint8Array],
  'caller_principal' : [] | [Uint8Array],
  'decoded' : [] | [DecodedTxView],
}
export interface ExportChunkView {
  'start' : number,
  'segment' : number,
  'payload_len' : number,
  'bytes' : Uint8Array,
}
export interface ExportCursorView {
  'byte_offset' : number,
  'block_number' : bigint,
  'segment' : number,
}
export type ExportErrorView = { 'Limit' : null } |
  { 'InvalidCursor' : { 'message' : string } } |
  { 'MissingData' : { 'message' : string } } |
  { 'Pruned' : { 'pruned_before_block' : bigint } };
export interface ExportResponseView {
  'next_cursor' : [] | [ExportCursorView],
  'chunks' : Array<ExportChunkView>,
}
export interface GenesisBalanceView {
  'address' : Uint8Array,
  'amount' : bigint,
}
export type GetLogsErrorView = { 'TooManyResults' : null } |
  { 'RangeTooLarge' : null } |
  { 'InvalidArgument' : string } |
  { 'UnsupportedFilter' : string };
export interface HealthView {
  'query_instruction_soft_limit' : bigint,
  'update_instruction_soft_limit' : bigint,
  'is_producing' : boolean,
  'mining_scheduled' : boolean,
  'block_gas_limit' : bigint,
  'tip_hash' : Uint8Array,
  'tip_number' : bigint,
  'auto_production_enabled' : boolean,
  'last_block_time' : bigint,
  'queue_len' : bigint,
}
export interface Icrc21ConsentInfo {
  'metadata' : Icrc21ConsentMessageMetadata,
  'consent_message' : Icrc21ConsentMessage,
}
export type Icrc21ConsentMessage = {
    'LineDisplayMessage' : Icrc21LineDisplayMessage
  } |
  { 'GenericDisplayMessage' : string };
export interface Icrc21ConsentMessageMetadata {
  'utc_offset_minutes' : [] | [number],
  'language' : string,
}
export interface Icrc21ConsentMessageRequest {
  'arg' : Uint8Array,
  'method' : string,
  'user_preferences' : Icrc21ConsentMessageSpec,
}
export interface Icrc21ConsentMessageSpec {
  'metadata' : Icrc21ConsentMessageMetadata,
  'device_spec' : [] | [Icrc21DeviceSpec],
}
export type Icrc21DeviceSpec = { 'GenericDisplay' : null } |
  { 'LineDisplay' : Icrc21LineDisplaySpec };
export type Icrc21Error = {
    'GenericError' : { 'description' : string, 'error_code' : bigint }
  } |
  { 'InsufficientPayment' : Icrc21ErrorInfo } |
  { 'UnsupportedCanisterCall' : Icrc21ErrorInfo } |
  { 'ConsentMessageUnavailable' : Icrc21ErrorInfo };
export interface Icrc21ErrorInfo { 'description' : string }
export interface Icrc21LineDisplayMessage {
  'pages' : Array<Icrc21LineDisplayPage>,
}
export interface Icrc21LineDisplayPage { 'lines' : Array<string> }
export interface Icrc21LineDisplaySpec {
  'characters_per_line' : number,
  'lines_per_page' : number,
}
export interface InitArgs {
  'genesis_balances' : Array<GenesisBalanceView>,
  'query_instruction_soft_limit' : [] | [bigint],
  'update_instruction_soft_limit' : [] | [bigint],
  'wrap_canister_id' : Principal,
  'wrap_factory_address' : Uint8Array,
}
export interface LogView {
  'data' : Uint8Array,
  'topics' : Array<Uint8Array>,
  'address' : Uint8Array,
}
export type LookupError = { 'NotFound' : null } |
  { 'Pruned' : { 'pruned_before_block' : bigint } } |
  { 'Pending' : null };
export interface MemoryBreakdownView {
  'stable_bytes_total' : bigint,
  'regions_pages_total' : bigint,
  'regions' : Array<MemoryRegionView>,
  'unattributed_stable_pages' : bigint,
  'unattributed_stable_bytes' : bigint,
  'stable_pages_total' : bigint,
  'heap_pages' : bigint,
  'heap_bytes' : bigint,
  'regions_bytes_total' : bigint,
}
export interface MemoryRegionView {
  'id' : number,
  'name' : string,
  'pages' : bigint,
  'bytes' : bigint,
}
export interface MetricsView {
  'txs' : bigint,
  'ema_txs_per_block_x1000' : bigint,
  'pruned_before_block' : [] | [bigint],
  'ema_block_rate_per_sec_x1000' : bigint,
  'total_submitted' : bigint,
  'window' : bigint,
  'avg_txs_per_block' : bigint,
  'block_rate_per_sec_x1000' : [] | [bigint],
  'cycles' : bigint,
  'total_dropped' : bigint,
  'blocks' : bigint,
  'drop_counts' : Array<DropCountView>,
  'queue_len' : bigint,
  'total_included' : bigint,
}
export interface OpsConfigView {
  'low_watermark' : bigint,
  'freeze_on_critical' : boolean,
  'critical' : bigint,
}
export type OpsModeView = { 'Low' : null } |
  { 'Normal' : null } |
  { 'Critical' : null };
export interface OpsStatusView {
  'needs_migration' : boolean,
  'critical_corrupt' : boolean,
  'decode_failure_last_ts' : bigint,
  'log_filter_override' : [] | [string],
  'last_cycle_balance' : bigint,
  'mode' : OpsModeView,
  'last_check_ts' : bigint,
  'mining_error_count' : bigint,
  'log_truncated_count' : bigint,
  'query_instruction_soft_limit' : bigint,
  'schema_version' : number,
  'update_instruction_soft_limit' : bigint,
  'safe_stop_latched' : boolean,
  'decode_failure_last_label' : [] | [string],
  'prune_error_count' : bigint,
  'block_gas_limit' : bigint,
  'config' : OpsConfigView,
  'decode_failure_count' : bigint,
}
export type PendingStatusView = { 'Queued' : { 'seq' : bigint } } |
  { 'Included' : { 'tx_index' : number, 'block_number' : bigint } } |
  { 'Unknown' : null } |
  { 'Dropped' : { 'code' : number } };
export type ProduceBlockError = { 'Internal' : string } |
  { 'InvalidArgument' : string };
export interface PrunePolicyView {
  'headroom_ratio_bps' : number,
  'target_bytes' : bigint,
  'retain_blocks' : bigint,
  'retain_days' : bigint,
  'hard_emergency_ratio_bps' : number,
  'max_ops_per_tick' : number,
}
export interface PruneResultView {
  'pruned_before_block' : [] | [bigint],
  'did_work' : boolean,
  'remaining' : bigint,
}
export interface PruneStatusView {
  'pruning_enabled' : boolean,
  'hard_emergency_bytes' : bigint,
  'pruned_before_block' : [] | [bigint],
  'low_water_bytes' : bigint,
  'high_water_bytes' : bigint,
  'oldest_kept_timestamp' : [] | [bigint],
  'estimated_kept_bytes' : bigint,
  'need_prune' : boolean,
  'last_prune_at' : bigint,
  'prune_running' : boolean,
  'oldest_kept_block' : [] | [bigint],
}
export interface QueueItemView {
  'seq' : bigint,
  'tx_id' : Uint8Array,
  'kind' : TxKindView,
}
export interface QueueSnapshotView {
  'next_cursor' : [] | [bigint],
  'items' : Array<QueueItemView>,
}
export interface ReceiptView {
  'effective_gas_price' : bigint,
  'status' : number,
  'l1_data_fee' : bigint,
  'tx_id' : Uint8Array,
  'tx_index' : number,
  'return_data_hash' : Uint8Array,
  'logs' : Array<LogView>,
  'return_data' : [] | [Uint8Array],
  'total_fee' : bigint,
  'block_number' : bigint,
  'operator_fee' : bigint,
  'gas_used' : bigint,
  'contract_address' : [] | [Uint8Array],
}
export type RequestDispatchStatusView = { 'Queued' : null } |
  { 'Dispatching' : null } |
  { 'Dispatched' : null } |
  { 'DispatchFailed' : null };
export type Result = { 'Ok' : null } |
  { 'Err' : ApiError };
export type Result_1 = { 'Ok' : EstimateIcTxOk } |
  { 'Err' : ApiError };
export type Result_10 = { 'Ok' : Uint8Array } |
  { 'Err' : string };
export type Result_11 = { 'Ok' : bigint } |
  { 'Err' : RpcErrorView };
export type Result_12 = { 'Ok' : RpcFeeHistoryView } |
  { 'Err' : RpcErrorView };
export type Result_13 = { 'Ok' : bigint } |
  { 'Err' : RpcErrorView };
export type Result_14 = { 'Ok' : Uint8Array } |
  { 'Err' : RpcErrorView };
export type Result_15 = { 'Ok' : [] | [bigint] } |
  { 'Err' : string };
export type Result_16 = { 'Ok' : EthLogsPageView } |
  { 'Err' : GetLogsErrorView };
export type Result_17 = { 'Ok' : Uint8Array } |
  { 'Err' : SubmitTxError };
export type Result_18 = { 'Ok' : null } |
  { 'Err' : string };
export type Result_2 = { 'Ok' : bigint } |
  { 'Err' : string };
export type Result_3 = { 'Ok' : ExportResponseView } |
  { 'Err' : ExportErrorView };
export type Result_4 = { 'Ok' : BlockView } |
  { 'Err' : LookupError };
export type Result_5 = { 'Ok' : ReceiptView } |
  { 'Err' : LookupError };
export type Result_6 = { 'Ok' : Icrc21ConsentInfo } |
  { 'Err' : Icrc21Error };
export type Result_7 = { 'Ok' : string } |
  { 'Err' : string };
export type Result_8 = { 'Ok' : PruneResultView } |
  { 'Err' : ProduceBlockError };
export type Result_9 = { 'Ok' : RpcCallResultView } |
  { 'Err' : RpcErrorView };
export interface RpcAccessListItemView {
  'storage_keys' : Array<Uint8Array>,
  'address' : Uint8Array,
}
export type RpcBlockLookupView = { 'NotFound' : null } |
  { 'Found' : EthBlockView } |
  { 'Pruned' : { 'pruned_before_block' : bigint } };
export type RpcBlockTagView = { 'Earliest' : null } |
  { 'Safe' : null } |
  { 'Finalized' : null } |
  { 'Latest' : null } |
  { 'Number' : bigint } |
  { 'Pending' : null };
export interface RpcCallObjectView {
  'to' : [] | [Uint8Array],
  'gas' : [] | [bigint],
  'value' : [] | [Uint8Array],
  'max_priority_fee_per_gas' : [] | [bigint],
  'data' : [] | [Uint8Array],
  'from' : [] | [Uint8Array],
  'max_fee_per_gas' : [] | [bigint],
  'chain_id' : [] | [bigint],
  'nonce' : [] | [bigint],
  'tx_type' : [] | [bigint],
  'access_list' : [] | [Array<RpcAccessListItemView>],
  'gas_price' : [] | [bigint],
}
export interface RpcCallResultView {
  'status' : number,
  'return_data' : Uint8Array,
  'gas_used' : bigint,
  'revert_data' : [] | [Uint8Array],
}
export interface RpcErrorView {
  'error_prefix' : [] | [string],
  'code' : number,
  'message' : string,
}
export interface RpcFeeHistoryView {
  'reward' : [] | [Array<Array<bigint>>],
  'base_fee_per_gas' : BigUint64Array,
  'oldest_block' : bigint,
  'gas_used_ratio' : Array<number>,
}
export interface RpcHistoryWindowView {
  'latest' : bigint,
  'oldest_available' : bigint,
}
export type RpcReceiptLookupView = { 'NotFound' : null } |
  { 'Found' : EthReceiptView } |
  { 'PossiblyPruned' : { 'pruned_before_block' : bigint } } |
  { 'Pruned' : { 'pruned_before_block' : bigint } };
export interface StandardRecord { 'url' : string, 'name' : string }
export interface SubmitIcTxArgsDto {
  'to' : [] | [Uint8Array],
  'value' : bigint,
  'max_priority_fee_per_gas' : bigint,
  'data' : Uint8Array,
  'from' : [] | [Uint8Array],
  'max_fee_per_gas' : bigint,
  'nonce' : bigint,
  'gas_limit' : bigint,
}
export type SubmitTxError = { 'Internal' : string } |
  { 'Rejected' : string } |
  { 'InvalidArgument' : string };
export type TxKindView = { 'EthSigned' : null } |
  { 'IcSynthetic' : null };
export interface UnwrapDispatchOverviewView {
  'request_id' : Uint8Array,
  'status' : RequestDispatchStatusView,
  'error' : [] | [string],
}
export interface _SERVICE {
  'credit_native_deposit' : ActorMethod<
    [Uint8Array, Uint8Array, bigint],
    Result
  >,
  'estimate_ic_tx' : ActorMethod<[SubmitIcTxArgsDto], Result_1>,
  'expected_nonce_by_address' : ActorMethod<[Uint8Array], Result_2>,
  'export_blocks' : ActorMethod<[[] | [ExportCursorView], number], Result_3>,
  'get_block' : ActorMethod<[bigint], Result_4>,
  'get_cycle_balance' : ActorMethod<[], bigint>,
  'get_ops_status' : ActorMethod<[], OpsStatusView>,
  'get_pending' : ActorMethod<[Uint8Array], PendingStatusView>,
  'get_prune_status' : ActorMethod<[], PruneStatusView>,
  'get_queue_snapshot' : ActorMethod<
    [number, [] | [bigint]],
    QueueSnapshotView
  >,
  'get_receipt' : ActorMethod<[Uint8Array], Result_5>,
  'get_unwrap_dispatch_overview' : ActorMethod<
    [Uint8Array],
    [] | [UnwrapDispatchOverviewView]
  >,
  'get_unwrap_request_ids_by_eth_tx_hash' : ActorMethod<
    [Uint8Array],
    Array<Uint8Array>
  >,
  'get_unwrap_request_ids_by_tx_id' : ActorMethod<
    [Uint8Array],
    Array<Uint8Array>
  >,
  'health' : ActorMethod<[], HealthView>,
  'icrc10_supported_standards' : ActorMethod<[], Array<StandardRecord>>,
  'icrc21_canister_call_consent_message' : ActorMethod<
    [Icrc21ConsentMessageRequest],
    Result_6
  >,
  'memory_breakdown' : ActorMethod<[], MemoryBreakdownView>,
  'metrics' : ActorMethod<[bigint], MetricsView>,
  'metrics_prometheus' : ActorMethod<[], Result_7>,
  'prune_blocks' : ActorMethod<[bigint, number], Result_8>,
  'rpc_eth_block_number' : ActorMethod<[], bigint>,
  'rpc_eth_call_object' : ActorMethod<[RpcCallObjectView], Result_9>,
  'rpc_eth_call_object_at' : ActorMethod<
    [RpcCallObjectView, RpcBlockTagView],
    Result_9
  >,
  'rpc_eth_call_rawtx' : ActorMethod<[Uint8Array], Result_10>,
  'rpc_eth_chain_id' : ActorMethod<[], bigint>,
  'rpc_eth_estimate_gas_object' : ActorMethod<[RpcCallObjectView], Result_11>,
  'rpc_eth_estimate_gas_object_at' : ActorMethod<
    [RpcCallObjectView, RpcBlockTagView],
    Result_11
  >,
  'rpc_eth_fee_history' : ActorMethod<
    [bigint, RpcBlockTagView, [] | [Array<number>]],
    Result_12
  >,
  'rpc_eth_gas_price' : ActorMethod<[], Result_13>,
  'rpc_eth_get_balance' : ActorMethod<[Uint8Array, RpcBlockTagView], Result_14>,
  'rpc_eth_get_block_by_number' : ActorMethod<
    [bigint, boolean],
    [] | [EthBlockView]
  >,
  'rpc_eth_get_block_by_number_with_status' : ActorMethod<
    [bigint, boolean],
    RpcBlockLookupView
  >,
  'rpc_eth_get_block_number_by_hash' : ActorMethod<
    [Uint8Array, number],
    Result_15
  >,
  'rpc_eth_get_code' : ActorMethod<[Uint8Array, RpcBlockTagView], Result_14>,
  'rpc_eth_get_logs_paged' : ActorMethod<
    [EthLogFilterView, [] | [EthLogsCursorView], number],
    Result_16
  >,
  'rpc_eth_get_storage_at' : ActorMethod<
    [Uint8Array, Uint8Array, RpcBlockTagView],
    Result_14
  >,
  'rpc_eth_get_transaction_by_eth_hash' : ActorMethod<
    [Uint8Array],
    [] | [EthTxView]
  >,
  'rpc_eth_get_transaction_by_tx_id' : ActorMethod<
    [Uint8Array],
    [] | [EthTxView]
  >,
  'rpc_eth_get_transaction_count_at' : ActorMethod<
    [Uint8Array, RpcBlockTagView],
    Result_11
  >,
  'rpc_eth_get_transaction_receipt_by_eth_hash' : ActorMethod<
    [Uint8Array],
    [] | [EthReceiptView]
  >,
  'rpc_eth_get_transaction_receipt_with_status_by_eth_hash' : ActorMethod<
    [Uint8Array],
    RpcReceiptLookupView
  >,
  'rpc_eth_get_transaction_receipt_with_status_by_tx_id' : ActorMethod<
    [Uint8Array],
    RpcReceiptLookupView
  >,
  'rpc_eth_history_window' : ActorMethod<[], RpcHistoryWindowView>,
  'rpc_eth_max_priority_fee_per_gas' : ActorMethod<[], Result_13>,
  'rpc_eth_send_raw_transaction' : ActorMethod<[Uint8Array], Result_17>,
  'set_log_filter' : ActorMethod<[[] | [string]], Result_18>,
  'set_prune_policy' : ActorMethod<[PrunePolicyView], Result_18>,
  'set_pruning_enabled' : ActorMethod<[boolean], Result_18>,
  'submit_ic_tx' : ActorMethod<[SubmitIcTxArgsDto], Result_17>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];