/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const GenesisBalanceView = IDL.Record({
    'address' : IDL.Vec(IDL.Nat8),
    'amount' : IDL.Nat,
  });
  const WrapConfigArgs = IDL.Record({
    'native_ledger_canister' : IDL.Principal,
    'allowed_assets' : IDL.Vec(IDL.Principal),
    'fee_ledger_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const InitArgs = IDL.Record({
    'genesis_balances' : IDL.Vec(GenesisBalanceView),
    'query_instruction_soft_limit' : IDL.Opt(IDL.Nat64),
    'update_instruction_soft_limit' : IDL.Opt(IDL.Nat64),
    'wrap_config' : IDL.Opt(WrapConfigArgs),
    'wrap_canister_id' : IDL.Principal,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  const ApiErrorDetail = IDL.Record({
    'code' : IDL.Text,
    'message' : IDL.Text,
  });
  const ApiError = IDL.Variant({
    'Internal' : ApiErrorDetail,
    'Rejected' : ApiErrorDetail,
    'InvalidArgument' : ApiErrorDetail,
  });
  const Result = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : ApiError });
  const DispatchNativeWithdrawalRequestArgs = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'recipient' : IDL.Principal,
    'amount_e8s' : IDL.Nat,
  });
  const DispatchUnwrapRequestOk = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
  });
  const Result_1 = IDL.Variant({
    'Ok' : DispatchUnwrapRequestOk,
    'Err' : ApiError,
  });
  const DispatchUnwrapRequestArgs = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'recipient' : IDL.Principal,
    'amount_e8s' : IDL.Nat,
    'asset_id' : IDL.Principal,
  });
  const SubmitIcTxArgsDto = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'value' : IDL.Nat,
    'max_priority_fee_per_gas' : IDL.Nat,
    'data' : IDL.Vec(IDL.Nat8),
    'from' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'max_fee_per_gas' : IDL.Nat,
    'nonce' : IDL.Nat64,
    'gas_limit' : IDL.Nat64,
  });
  const EstimateIcTxOk = IDL.Record({
    'suggested_max_fee_per_gas' : IDL.Nat,
    'suggested_max_priority_fee_per_gas' : IDL.Nat,
    'gas_limit' : IDL.Nat64,
  });
  const Result_2 = IDL.Variant({ 'Ok' : EstimateIcTxOk, 'Err' : ApiError });
  const Result_3 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text });
  const ExportCursorView = IDL.Record({
    'byte_offset' : IDL.Nat32,
    'block_number' : IDL.Nat64,
    'segment' : IDL.Nat8,
  });
  const ExportChunkView = IDL.Record({
    'start' : IDL.Nat32,
    'segment' : IDL.Nat8,
    'payload_len' : IDL.Nat32,
    'bytes' : IDL.Vec(IDL.Nat8),
  });
  const ExportResponseView = IDL.Record({
    'next_cursor' : IDL.Opt(ExportCursorView),
    'chunks' : IDL.Vec(ExportChunkView),
  });
  const ExportErrorView = IDL.Variant({
    'Limit' : IDL.Null,
    'InvalidCursor' : IDL.Record({ 'message' : IDL.Text }),
    'MissingData' : IDL.Record({ 'message' : IDL.Text }),
    'Pruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
  });
  const Result_4 = IDL.Variant({
    'Ok' : ExportResponseView,
    'Err' : ExportErrorView,
  });
  const Result_5 = IDL.Variant({
    'Ok' : IDL.Vec(IDL.Principal),
    'Err' : IDL.Text,
  });
  const BlockView = IDL.Record({
    'tx_list_hash' : IDL.Vec(IDL.Nat8),
    'block_hash' : IDL.Vec(IDL.Nat8),
    'number' : IDL.Nat64,
    'timestamp' : IDL.Nat64,
    'tx_ids' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'state_root' : IDL.Vec(IDL.Nat8),
    'parent_hash' : IDL.Vec(IDL.Nat8),
  });
  const LookupError = IDL.Variant({
    'NotFound' : IDL.Null,
    'Pruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
    'Pending' : IDL.Null,
  });
  const Result_6 = IDL.Variant({ 'Ok' : BlockView, 'Err' : LookupError });
  const FeePolicyView = IDL.Record({
    'fee_ledger_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const Result_7 = IDL.Variant({ 'Ok' : FeePolicyView, 'Err' : IDL.Text });
  const RequestStatus = IDL.Variant({
    'Queued' : IDL.Null,
    'Failed' : IDL.Null,
    'Succeeded' : IDL.Null,
    'Running' : IDL.Null,
  });
  const RequestKind = IDL.Variant({
    'Wrap' : IDL.Null,
    'NativeDeposit' : IDL.Null,
    'Unwrap' : IDL.Null,
    'NativeWithdrawal' : IDL.Null,
  });
  const RequestDispatchStatusView = IDL.Variant({
    'Queued' : IDL.Null,
    'Dispatching' : IDL.Null,
    'Dispatched' : IDL.Null,
    'DispatchFailed' : IDL.Null,
  });
  const RequestStageView = IDL.Variant({
    'Queued' : IDL.Null,
    'Refunding' : IDL.Null,
    'Failed' : IDL.Null,
    'Refunded' : IDL.Null,
    'MintSubmitting' : IDL.Null,
    'MintSubmitted' : IDL.Null,
    'PullPending' : IDL.Null,
    'Dispatching' : IDL.Null,
    'Dispatched' : IDL.Null,
    'FeePending' : IDL.Null,
    'Succeeded' : IDL.Null,
    'Pulled' : IDL.Null,
    'DispatchFailed' : IDL.Null,
    'FeeCollected' : IDL.Null,
  });
  const RequestOverview = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'status' : RequestStatus,
    'recoverable' : IDL.Bool,
    'charged_fee_e8s' : IDL.Opt(IDL.Nat),
    'withdraw_in_progress' : IDL.Bool,
    'withdraw_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'kind' : RequestKind,
    'dispatch_status' : IDL.Opt(RequestDispatchStatusView),
    'error' : IDL.Opt(ApiErrorDetail),
    'dispatch_error' : IDL.Opt(IDL.Text),
    'stage' : IDL.Opt(RequestStageView),
    'fee_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'charged_gas_price_wei' : IDL.Opt(IDL.Nat),
    'withdraw_error' : IDL.Opt(ApiErrorDetail),
    'ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'withdrawn' : IDL.Bool,
    'mint_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'pull_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const OpsModeView = IDL.Variant({
    'Low' : IDL.Null,
    'Normal' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const OpsConfigView = IDL.Record({
    'low_watermark' : IDL.Nat,
    'freeze_on_critical' : IDL.Bool,
    'critical' : IDL.Nat,
  });
  const OpsStatusView = IDL.Record({
    'needs_migration' : IDL.Bool,
    'critical_corrupt' : IDL.Bool,
    'decode_failure_last_ts' : IDL.Nat64,
    'log_filter_override' : IDL.Opt(IDL.Text),
    'last_cycle_balance' : IDL.Nat,
    'mode' : OpsModeView,
    'last_check_ts' : IDL.Nat64,
    'mining_error_count' : IDL.Nat64,
    'log_truncated_count' : IDL.Nat64,
    'query_instruction_soft_limit' : IDL.Nat64,
    'schema_version' : IDL.Nat32,
    'update_instruction_soft_limit' : IDL.Nat64,
    'safe_stop_latched' : IDL.Bool,
    'decode_failure_last_label' : IDL.Opt(IDL.Text),
    'prune_error_count' : IDL.Nat64,
    'block_gas_limit' : IDL.Nat64,
    'config' : OpsConfigView,
    'decode_failure_count' : IDL.Nat64,
  });
  const PendingStatusView = IDL.Variant({
    'Queued' : IDL.Record({ 'seq' : IDL.Nat64 }),
    'Included' : IDL.Record({
      'tx_index' : IDL.Nat32,
      'block_number' : IDL.Nat64,
    }),
    'Unknown' : IDL.Null,
    'Dropped' : IDL.Record({ 'code' : IDL.Nat16 }),
  });
  const PruneStatusView = IDL.Record({
    'pruning_enabled' : IDL.Bool,
    'hard_emergency_bytes' : IDL.Nat64,
    'pruned_before_block' : IDL.Opt(IDL.Nat64),
    'low_water_bytes' : IDL.Nat64,
    'high_water_bytes' : IDL.Nat64,
    'oldest_kept_timestamp' : IDL.Opt(IDL.Nat64),
    'estimated_kept_bytes' : IDL.Nat64,
    'need_prune' : IDL.Bool,
    'last_prune_at' : IDL.Nat64,
    'prune_running' : IDL.Bool,
    'oldest_kept_block' : IDL.Opt(IDL.Nat64),
  });
  const TxKindView = IDL.Variant({
    'EthSigned' : IDL.Null,
    'IcSynthetic' : IDL.Null,
  });
  const QueueItemView = IDL.Record({
    'seq' : IDL.Nat64,
    'tx_id' : IDL.Vec(IDL.Nat8),
    'kind' : TxKindView,
  });
  const QueueSnapshotView = IDL.Record({
    'next_cursor' : IDL.Opt(IDL.Nat64),
    'items' : IDL.Vec(QueueItemView),
  });
  const LogView = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'topics' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Vec(IDL.Nat8),
  });
  const ReceiptView = IDL.Record({
    'effective_gas_price' : IDL.Nat64,
    'status' : IDL.Nat8,
    'l1_data_fee' : IDL.Nat,
    'tx_id' : IDL.Vec(IDL.Nat8),
    'tx_index' : IDL.Nat32,
    'return_data_hash' : IDL.Vec(IDL.Nat8),
    'logs' : IDL.Vec(LogView),
    'return_data' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'total_fee' : IDL.Nat,
    'block_number' : IDL.Nat64,
    'operator_fee' : IDL.Nat,
    'gas_used' : IDL.Nat64,
    'contract_address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const Result_8 = IDL.Variant({ 'Ok' : ReceiptView, 'Err' : LookupError });
  const UnwrapDispatchOverviewView = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'status' : RequestDispatchStatusView,
    'error' : IDL.Opt(IDL.Text),
  });
  const GetUnwrapRequirementsArgs = IDL.Record({
    'caller_evm_address' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'asset_id' : IDL.Principal,
  });
  const UnwrapReadiness = IDL.Variant({
    'TokenNotDeployed' : IDL.Null,
    'InsufficientAllowance' : IDL.Null,
    'InsufficientBalance' : IDL.Null,
    'Ready' : IDL.Null,
  });
  const GetUnwrapRequirementsOk = IDL.Record({
    'balance' : IDL.Nat,
    'wrapped_token_address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'approve_required' : IDL.Bool,
    'allowance' : IDL.Nat,
    'factory_address' : IDL.Vec(IDL.Nat8),
    'readiness' : UnwrapReadiness,
  });
  const Result_9 = IDL.Variant({
    'Ok' : GetUnwrapRequirementsOk,
    'Err' : ApiError,
  });
  const WrapRuntimeConfigView = IDL.Record({
    'native_ledger_canister' : IDL.Principal,
    'allowed_assets' : IDL.Vec(IDL.Principal),
    'fee_ledger_canister' : IDL.Principal,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  const Result_10 = IDL.Variant({
    'Ok' : WrapRuntimeConfigView,
    'Err' : IDL.Text,
  });
  const HealthView = IDL.Record({
    'query_instruction_soft_limit' : IDL.Nat64,
    'update_instruction_soft_limit' : IDL.Nat64,
    'is_producing' : IDL.Bool,
    'mining_scheduled' : IDL.Bool,
    'block_gas_limit' : IDL.Nat64,
    'tip_hash' : IDL.Vec(IDL.Nat8),
    'tip_number' : IDL.Nat64,
    'auto_production_enabled' : IDL.Bool,
    'last_block_time' : IDL.Nat64,
    'queue_len' : IDL.Nat64,
  });
  const StandardRecord = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const Icrc21ConsentMessageMetadata = IDL.Record({
    'utc_offset_minutes' : IDL.Opt(IDL.Int16),
    'language' : IDL.Text,
  });
  const Icrc21LineDisplaySpec = IDL.Record({
    'characters_per_line' : IDL.Nat16,
    'lines_per_page' : IDL.Nat16,
  });
  const Icrc21DeviceSpec = IDL.Variant({
    'GenericDisplay' : IDL.Null,
    'LineDisplay' : Icrc21LineDisplaySpec,
  });
  const Icrc21ConsentMessageSpec = IDL.Record({
    'metadata' : Icrc21ConsentMessageMetadata,
    'device_spec' : IDL.Opt(Icrc21DeviceSpec),
  });
  const Icrc21ConsentMessageRequest = IDL.Record({
    'arg' : IDL.Vec(IDL.Nat8),
    'method' : IDL.Text,
    'user_preferences' : Icrc21ConsentMessageSpec,
  });
  const Icrc21LineDisplayPage = IDL.Record({ 'lines' : IDL.Vec(IDL.Text) });
  const Icrc21LineDisplayMessage = IDL.Record({
    'pages' : IDL.Vec(Icrc21LineDisplayPage),
  });
  const Icrc21ConsentMessage = IDL.Variant({
    'LineDisplayMessage' : Icrc21LineDisplayMessage,
    'GenericDisplayMessage' : IDL.Text,
  });
  const Icrc21ConsentInfo = IDL.Record({
    'metadata' : Icrc21ConsentMessageMetadata,
    'consent_message' : Icrc21ConsentMessage,
  });
  const Icrc21ErrorInfo = IDL.Record({ 'description' : IDL.Text });
  const Icrc21Error = IDL.Variant({
    'GenericError' : IDL.Record({
      'description' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'InsufficientPayment' : Icrc21ErrorInfo,
    'UnsupportedCanisterCall' : Icrc21ErrorInfo,
    'ConsentMessageUnavailable' : Icrc21ErrorInfo,
  });
  const Result_11 = IDL.Variant({
    'Ok' : Icrc21ConsentInfo,
    'Err' : Icrc21Error,
  });
  const MemoryRegionView = IDL.Record({
    'id' : IDL.Nat8,
    'name' : IDL.Text,
    'pages' : IDL.Nat64,
    'bytes' : IDL.Nat64,
  });
  const MemoryBreakdownView = IDL.Record({
    'stable_bytes_total' : IDL.Nat64,
    'regions_pages_total' : IDL.Nat64,
    'regions' : IDL.Vec(MemoryRegionView),
    'unattributed_stable_pages' : IDL.Nat64,
    'unattributed_stable_bytes' : IDL.Nat64,
    'stable_pages_total' : IDL.Nat64,
    'heap_pages' : IDL.Nat64,
    'heap_bytes' : IDL.Nat64,
    'regions_bytes_total' : IDL.Nat64,
  });
  const DropCountView = IDL.Record({ 'code' : IDL.Nat16, 'count' : IDL.Nat64 });
  const MetricsView = IDL.Record({
    'txs' : IDL.Nat64,
    'ema_txs_per_block_x1000' : IDL.Nat64,
    'pruned_before_block' : IDL.Opt(IDL.Nat64),
    'ema_block_rate_per_sec_x1000' : IDL.Nat64,
    'total_submitted' : IDL.Nat64,
    'window' : IDL.Nat64,
    'avg_txs_per_block' : IDL.Nat64,
    'block_rate_per_sec_x1000' : IDL.Opt(IDL.Nat64),
    'cycles' : IDL.Nat,
    'total_dropped' : IDL.Nat64,
    'blocks' : IDL.Nat64,
    'drop_counts' : IDL.Vec(DropCountView),
    'queue_len' : IDL.Nat64,
    'total_included' : IDL.Nat64,
  });
  const Result_12 = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text });
  const PruneResultView = IDL.Record({
    'pruned_before_block' : IDL.Opt(IDL.Nat64),
    'did_work' : IDL.Bool,
    'remaining' : IDL.Nat64,
  });
  const ProduceBlockError = IDL.Variant({
    'Internal' : IDL.Text,
    'InvalidArgument' : IDL.Text,
  });
  const Result_13 = IDL.Variant({
    'Ok' : PruneResultView,
    'Err' : ProduceBlockError,
  });
  const QuoteNativeDepositArgs = IDL.Record({
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
  });
  const QuoteNativeDepositOk = IDL.Record({
    'charged_fee_e8s' : IDL.Nat,
    'native_ledger_canister' : IDL.Principal,
    'fee_ledger_canister' : IDL.Principal,
  });
  const Result_14 = IDL.Variant({
    'Ok' : QuoteNativeDepositOk,
    'Err' : ApiError,
  });
  const QuoteNativeWithdrawalArgs = IDL.Record({
    'recipient' : IDL.Principal,
    'amount_e8s' : IDL.Nat,
  });
  const QuoteNativeWithdrawalOk = IDL.Record({
    'native_ledger_canister' : IDL.Principal,
    'ledger_fee_e8s' : IDL.Nat,
    'receive_amount_e8s' : IDL.Nat,
  });
  const Result_15 = IDL.Variant({
    'Ok' : QuoteNativeWithdrawalOk,
    'Err' : ApiError,
  });
  const QuoteWrapRequestArgs = IDL.Record({
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'gas_limit' : IDL.Nat64,
    'asset_id' : IDL.Principal,
  });
  const QuoteWrapRequestOk = IDL.Record({
    'charged_fee_e8s' : IDL.Nat,
    'fee_ledger_canister' : IDL.Principal,
    'charged_gas_price_wei' : IDL.Nat,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const Result_16 = IDL.Variant({
    'Ok' : QuoteWrapRequestOk,
    'Err' : ApiError,
  });
  const RecoverFailedWrapArgs = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
  });
  const Result_17 = IDL.Variant({ 'Ok' : RequestOverview, 'Err' : ApiError });
  const Result_18 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const RetryRequestArgs = IDL.Record({ 'request_id' : IDL.Vec(IDL.Nat8) });
  const RpcAccessListItemView = IDL.Record({
    'storage_keys' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Vec(IDL.Nat8),
  });
  const RpcCallObjectView = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'gas' : IDL.Opt(IDL.Nat64),
    'value' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'max_priority_fee_per_gas' : IDL.Opt(IDL.Nat),
    'data' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'max_fee_per_gas' : IDL.Opt(IDL.Nat),
    'chain_id' : IDL.Opt(IDL.Nat64),
    'nonce' : IDL.Opt(IDL.Nat64),
    'tx_type' : IDL.Opt(IDL.Nat64),
    'access_list' : IDL.Opt(IDL.Vec(RpcAccessListItemView)),
    'gas_price' : IDL.Opt(IDL.Nat),
  });
  const RpcCallResultView = IDL.Record({
    'status' : IDL.Nat8,
    'return_data' : IDL.Vec(IDL.Nat8),
    'gas_used' : IDL.Nat64,
    'revert_data' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const RpcErrorView = IDL.Record({
    'error_prefix' : IDL.Opt(IDL.Text),
    'code' : IDL.Nat32,
    'message' : IDL.Text,
  });
  const Result_19 = IDL.Variant({
    'Ok' : RpcCallResultView,
    'Err' : RpcErrorView,
  });
  const RpcBlockTagView = IDL.Variant({
    'Earliest' : IDL.Null,
    'Safe' : IDL.Null,
    'Finalized' : IDL.Null,
    'Latest' : IDL.Null,
    'Number' : IDL.Nat64,
    'Pending' : IDL.Null,
  });
  const Result_20 = IDL.Variant({ 'Ok' : IDL.Vec(IDL.Nat8), 'Err' : IDL.Text });
  const Result_21 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : RpcErrorView });
  const RpcFeeHistoryView = IDL.Record({
    'reward' : IDL.Opt(IDL.Vec(IDL.Vec(IDL.Nat))),
    'base_fee_per_gas' : IDL.Vec(IDL.Nat64),
    'oldest_block' : IDL.Nat64,
    'gas_used_ratio' : IDL.Vec(IDL.Float64),
  });
  const Result_22 = IDL.Variant({
    'Ok' : RpcFeeHistoryView,
    'Err' : RpcErrorView,
  });
  const Result_23 = IDL.Variant({ 'Ok' : IDL.Nat, 'Err' : RpcErrorView });
  const Result_24 = IDL.Variant({
    'Ok' : IDL.Vec(IDL.Nat8),
    'Err' : RpcErrorView,
  });
  const DecodedTxView = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'signature_r' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'signature_s' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'signature_v' : IDL.Opt(IDL.Nat64),
    'value' : IDL.Vec(IDL.Nat8),
    'max_priority_fee_per_gas' : IDL.Opt(IDL.Nat),
    'from' : IDL.Vec(IDL.Nat8),
    'max_fee_per_gas' : IDL.Opt(IDL.Nat),
    'chain_id' : IDL.Opt(IDL.Nat64),
    'nonce' : IDL.Nat64,
    'gas_limit' : IDL.Nat64,
    'input' : IDL.Vec(IDL.Nat8),
    'tx_type' : IDL.Opt(IDL.Nat8),
    'gas_price' : IDL.Opt(IDL.Nat),
  });
  const EthTxView = IDL.Record({
    'raw' : IDL.Vec(IDL.Nat8),
    'tx_index' : IDL.Opt(IDL.Nat32),
    'block_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'decode_ok' : IDL.Bool,
    'hash' : IDL.Vec(IDL.Nat8),
    'kind' : TxKindView,
    'block_number' : IDL.Opt(IDL.Nat64),
    'eth_tx_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'caller_principal' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'decoded' : IDL.Opt(DecodedTxView),
  });
  const EthTxListView = IDL.Variant({
    'Full' : IDL.Vec(EthTxView),
    'Hashes' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const EthBlockView = IDL.Record({
    'txs' : EthTxListView,
    'base_fee_per_gas' : IDL.Opt(IDL.Nat64),
    'beneficiary' : IDL.Vec(IDL.Nat8),
    'block_hash' : IDL.Vec(IDL.Nat8),
    'number' : IDL.Nat64,
    'timestamp' : IDL.Nat64,
    'gas_limit' : IDL.Opt(IDL.Nat64),
    'gas_used' : IDL.Opt(IDL.Nat64),
    'state_root' : IDL.Vec(IDL.Nat8),
    'parent_hash' : IDL.Vec(IDL.Nat8),
  });
  const RpcBlockLookupView = IDL.Variant({
    'NotFound' : IDL.Null,
    'Found' : EthBlockView,
    'Pruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
  });
  const Result_25 = IDL.Variant({
    'Ok' : IDL.Opt(IDL.Nat64),
    'Err' : IDL.Text,
  });
  const EthLogFilterView = IDL.Record({
    'limit' : IDL.Opt(IDL.Nat32),
    'topic0' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'topic1' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'to_block' : IDL.Opt(IDL.Nat64),
    'from_block' : IDL.Opt(IDL.Nat64),
  });
  const EthLogsCursorView = IDL.Record({
    'tx_index' : IDL.Nat32,
    'log_index' : IDL.Nat32,
    'block_number' : IDL.Nat64,
  });
  const EthLogItemView = IDL.Record({
    'tx_index' : IDL.Nat32,
    'block_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'log_index' : IDL.Nat32,
    'data' : IDL.Vec(IDL.Nat8),
    'block_number' : IDL.Nat64,
    'topics' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Vec(IDL.Nat8),
    'eth_tx_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'tx_hash' : IDL.Vec(IDL.Nat8),
  });
  const EthLogsPageView = IDL.Record({
    'next_cursor' : IDL.Opt(EthLogsCursorView),
    'items' : IDL.Vec(EthLogItemView),
  });
  const GetLogsErrorView = IDL.Variant({
    'TooManyResults' : IDL.Null,
    'RangeTooLarge' : IDL.Null,
    'InvalidArgument' : IDL.Text,
    'UnsupportedFilter' : IDL.Text,
  });
  const Result_26 = IDL.Variant({
    'Ok' : EthLogsPageView,
    'Err' : GetLogsErrorView,
  });
  const EthReceiptLogView = IDL.Record({
    'log_index' : IDL.Nat32,
    'data' : IDL.Vec(IDL.Nat8),
    'topics' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Vec(IDL.Nat8),
  });
  const EthReceiptView = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'effective_gas_price' : IDL.Nat64,
    'status' : IDL.Nat8,
    'l1_data_fee' : IDL.Nat,
    'tx_index' : IDL.Nat32,
    'block_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'logs' : IDL.Vec(EthReceiptLogView),
    'total_fee' : IDL.Nat,
    'block_number' : IDL.Nat64,
    'operator_fee' : IDL.Nat,
    'cumulative_gas_used' : IDL.Opt(IDL.Nat64),
    'eth_tx_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'gas_used' : IDL.Nat64,
    'contract_address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'tx_hash' : IDL.Vec(IDL.Nat8),
    'tx_type' : IDL.Opt(IDL.Nat8),
  });
  const RpcReceiptLookupView = IDL.Variant({
    'NotFound' : IDL.Null,
    'Found' : EthReceiptView,
    'PossiblyPruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
    'Pruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
  });
  const RpcHistoryWindowView = IDL.Record({
    'latest' : IDL.Nat64,
    'oldest_available' : IDL.Nat64,
  });
  const SubmitTxError = IDL.Variant({
    'Internal' : IDL.Text,
    'Rejected' : IDL.Text,
    'InvalidArgument' : IDL.Text,
  });
  const Result_27 = IDL.Variant({
    'Ok' : IDL.Vec(IDL.Nat8),
    'Err' : SubmitTxError,
  });
  const PrunePolicyView = IDL.Record({
    'headroom_ratio_bps' : IDL.Nat32,
    'target_bytes' : IDL.Nat64,
    'retain_blocks' : IDL.Nat64,
    'retain_days' : IDL.Nat64,
    'hard_emergency_ratio_bps' : IDL.Nat32,
    'max_ops_per_tick' : IDL.Nat32,
  });
  const SubmitNativeDepositArgs = IDL.Record({
    'deposit_id' : IDL.Vec(IDL.Nat8),
    'max_fee_e8s' : IDL.Nat,
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'fee_ledger_canister' : IDL.Principal,
  });
  const SubmitNativeDepositOk = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'charged_fee_e8s' : IDL.Nat,
    'fee_ledger_tx_id' : IDL.Vec(IDL.Nat8),
  });
  const Result_28 = IDL.Variant({
    'Ok' : SubmitNativeDepositOk,
    'Err' : ApiError,
  });
  const SubmitWrapRequestArgs = IDL.Record({
    'max_fee_e8s' : IDL.Nat,
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'fee_ledger_canister' : IDL.Principal,
    'gas_limit' : IDL.Nat64,
    'asset_id' : IDL.Principal,
    'quoted_gas_price_wei' : IDL.Nat,
    'evm_nonce' : IDL.Nat64,
  });
  const SubmitWrapRequestOk = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'charged_fee_e8s' : IDL.Nat,
    'fee_ledger_tx_id' : IDL.Vec(IDL.Nat8),
    'charged_gas_price_wei' : IDL.Nat,
  });
  const Result_29 = IDL.Variant({
    'Ok' : SubmitWrapRequestOk,
    'Err' : ApiError,
  });
  
  return IDL.Service({
    'credit_native_deposit' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Nat],
        [Result],
        [],
      ),
    'dispatch_native_withdrawal_request' : IDL.Func(
        [DispatchNativeWithdrawalRequestArgs],
        [Result_1],
        [],
      ),
    'dispatch_unwrap_request' : IDL.Func(
        [DispatchUnwrapRequestArgs],
        [Result_1],
        [],
      ),
    'estimate_ic_tx' : IDL.Func([SubmitIcTxArgsDto], [Result_2], ['query']),
    'expected_nonce_by_address' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [Result_3],
        ['query'],
      ),
    'export_blocks' : IDL.Func(
        [IDL.Opt(ExportCursorView), IDL.Nat32],
        [Result_4],
        ['query'],
      ),
    'get_allowed_assets' : IDL.Func([], [Result_5], ['query']),
    'get_block' : IDL.Func([IDL.Nat64], [Result_6], ['query']),
    'get_cycle_balance' : IDL.Func([], [IDL.Nat], ['query']),
    'get_fee_policy' : IDL.Func([], [Result_7], ['query']),
    'get_native_deposit_result' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(RequestOverview)],
        ['query'],
      ),
    'get_ops_status' : IDL.Func([], [OpsStatusView], ['query']),
    'get_pending' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [PendingStatusView],
        ['query'],
      ),
    'get_prune_status' : IDL.Func([], [PruneStatusView], ['query']),
    'get_queue_snapshot' : IDL.Func(
        [IDL.Nat32, IDL.Opt(IDL.Nat64)],
        [QueueSnapshotView],
        ['query'],
      ),
    'get_receipt' : IDL.Func([IDL.Vec(IDL.Nat8)], [Result_8], ['query']),
    'get_request' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(RequestOverview)],
        ['query'],
      ),
    'get_unwrap_dispatch_overview' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(UnwrapDispatchOverviewView)],
        ['query'],
      ),
    'get_unwrap_request_ids_by_eth_tx_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'get_unwrap_request_ids_by_tx_id' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'get_unwrap_requirements' : IDL.Func(
        [GetUnwrapRequirementsArgs],
        [Result_9],
        ['query'],
      ),
    'get_wrap_runtime_config' : IDL.Func([], [Result_10], ['query']),
    'health' : IDL.Func([], [HealthView], ['query']),
    'icrc10_supported_standards' : IDL.Func(
        [],
        [IDL.Vec(StandardRecord)],
        ['query'],
      ),
    'icrc21_canister_call_consent_message' : IDL.Func(
        [Icrc21ConsentMessageRequest],
        [Result_11],
        [],
      ),
    'memory_breakdown' : IDL.Func([], [MemoryBreakdownView], ['query']),
    'metrics' : IDL.Func([IDL.Nat64], [MetricsView], ['query']),
    'metrics_prometheus' : IDL.Func([], [Result_12], ['query']),
    'prune_blocks' : IDL.Func([IDL.Nat64, IDL.Nat32], [Result_13], []),
    'quote_native_deposit' : IDL.Func(
        [QuoteNativeDepositArgs],
        [Result_14],
        ['query'],
      ),
    'quote_native_withdrawal' : IDL.Func(
        [QuoteNativeWithdrawalArgs],
        [Result_15],
        ['composite_query'],
      ),
    'quote_wrap_request' : IDL.Func(
        [QuoteWrapRequestArgs],
        [Result_16],
        ['query'],
      ),
    'recover_failed_wrap' : IDL.Func([RecoverFailedWrapArgs], [Result_17], []),
    'repair_stale_wrap_operations' : IDL.Func([], [Result_18], []),
    'retry_native_deposit' : IDL.Func([RetryRequestArgs], [Result_17], []),
    'retry_native_withdrawal' : IDL.Func([RetryRequestArgs], [Result_17], []),
    'retry_request' : IDL.Func([RetryRequestArgs], [Result_17], []),
    'rpc_eth_block_number' : IDL.Func([], [IDL.Nat64], ['query']),
    'rpc_eth_call_object' : IDL.Func(
        [RpcCallObjectView],
        [Result_19],
        ['query'],
      ),
    'rpc_eth_call_object_at' : IDL.Func(
        [RpcCallObjectView, RpcBlockTagView],
        [Result_19],
        ['query'],
      ),
    'rpc_eth_call_rawtx' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [Result_20],
        ['query'],
      ),
    'rpc_eth_chain_id' : IDL.Func([], [IDL.Nat64], ['query']),
    'rpc_eth_estimate_gas_object' : IDL.Func(
        [RpcCallObjectView],
        [Result_21],
        ['query'],
      ),
    'rpc_eth_estimate_gas_object_at' : IDL.Func(
        [RpcCallObjectView, RpcBlockTagView],
        [Result_21],
        ['query'],
      ),
    'rpc_eth_fee_history' : IDL.Func(
        [IDL.Nat64, RpcBlockTagView, IDL.Opt(IDL.Vec(IDL.Float64))],
        [Result_22],
        ['query'],
      ),
    'rpc_eth_gas_price' : IDL.Func([], [Result_23], ['query']),
    'rpc_eth_get_balance' : IDL.Func(
        [IDL.Vec(IDL.Nat8), RpcBlockTagView],
        [Result_24],
        ['query'],
      ),
    'rpc_eth_get_block_by_number' : IDL.Func(
        [IDL.Nat64, IDL.Bool],
        [IDL.Opt(EthBlockView)],
        ['query'],
      ),
    'rpc_eth_get_block_by_number_with_status' : IDL.Func(
        [IDL.Nat64, IDL.Bool],
        [RpcBlockLookupView],
        ['query'],
      ),
    'rpc_eth_get_block_number_by_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Nat32],
        [Result_25],
        ['query'],
      ),
    'rpc_eth_get_code' : IDL.Func(
        [IDL.Vec(IDL.Nat8), RpcBlockTagView],
        [Result_24],
        ['query'],
      ),
    'rpc_eth_get_logs_paged' : IDL.Func(
        [EthLogFilterView, IDL.Opt(EthLogsCursorView), IDL.Nat32],
        [Result_26],
        ['query'],
      ),
    'rpc_eth_get_storage_at' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), RpcBlockTagView],
        [Result_24],
        ['query'],
      ),
    'rpc_eth_get_transaction_by_eth_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(EthTxView)],
        ['query'],
      ),
    'rpc_eth_get_transaction_by_tx_id' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(EthTxView)],
        ['query'],
      ),
    'rpc_eth_get_transaction_count_at' : IDL.Func(
        [IDL.Vec(IDL.Nat8), RpcBlockTagView],
        [Result_21],
        ['query'],
      ),
    'rpc_eth_get_transaction_receipt_by_eth_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(EthReceiptView)],
        ['query'],
      ),
    'rpc_eth_get_transaction_receipt_with_status_by_eth_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [RpcReceiptLookupView],
        ['query'],
      ),
    'rpc_eth_get_transaction_receipt_with_status_by_tx_id' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [RpcReceiptLookupView],
        ['query'],
      ),
    'rpc_eth_history_window' : IDL.Func([], [RpcHistoryWindowView], ['query']),
    'rpc_eth_max_priority_fee_per_gas' : IDL.Func([], [Result_23], ['query']),
    'rpc_eth_send_raw_transaction' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [Result_27],
        [],
      ),
    'set_allowed_assets' : IDL.Func([IDL.Vec(IDL.Principal)], [Result_18], []),
    'set_fee_policy' : IDL.Func([FeePolicyView], [Result_18], []),
    'set_log_filter' : IDL.Func([IDL.Opt(IDL.Text)], [Result_18], []),
    'set_prune_policy' : IDL.Func([PrunePolicyView], [Result_18], []),
    'set_pruning_enabled' : IDL.Func([IDL.Bool], [Result_18], []),
    'submit_ic_tx' : IDL.Func([SubmitIcTxArgsDto], [Result_27], []),
    'submit_native_deposit' : IDL.Func(
        [SubmitNativeDepositArgs],
        [Result_28],
        [],
      ),
    'submit_wrap_request' : IDL.Func([SubmitWrapRequestArgs], [Result_29], []),
  });
};

export const init = ({ IDL }) => {
  const GenesisBalanceView = IDL.Record({
    'address' : IDL.Vec(IDL.Nat8),
    'amount' : IDL.Nat,
  });
  const WrapConfigArgs = IDL.Record({
    'native_ledger_canister' : IDL.Principal,
    'allowed_assets' : IDL.Vec(IDL.Principal),
    'fee_ledger_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const InitArgs = IDL.Record({
    'genesis_balances' : IDL.Vec(GenesisBalanceView),
    'query_instruction_soft_limit' : IDL.Opt(IDL.Nat64),
    'update_instruction_soft_limit' : IDL.Opt(IDL.Nat64),
    'wrap_config' : IDL.Opt(WrapConfigArgs),
    'wrap_canister_id' : IDL.Principal,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  
  return [IDL.Opt(InitArgs)];
};