/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const GenesisBalanceView = IDL.Record({
    'address' : IDL.Vec(IDL.Nat8),
    'amount' : IDL.Nat,
  });
  const InitArgs = IDL.Record({
    'genesis_balances' : IDL.Vec(GenesisBalanceView),
    'query_instruction_soft_limit' : IDL.Opt(IDL.Nat64),
    'update_instruction_soft_limit' : IDL.Opt(IDL.Nat64),
    'wrap_canister_id' : IDL.Principal,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  const SubmitIcTxArgsDto = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'value' : IDL.Nat,
    'max_priority_fee_per_gas' : IDL.Nat,
    'data' : IDL.Vec(IDL.Nat8),
    'from' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'max_fee_per_gas' : IDL.Nat,
    'nonce' : IDL.Nat64,
    'gas_limit' : IDL.Nat64,
  });
  const EstimateIcTxOk = IDL.Record({
    'suggested_max_fee_per_gas' : IDL.Nat,
    'suggested_max_priority_fee_per_gas' : IDL.Nat,
    'gas_limit' : IDL.Nat64,
  });
  const ApiErrorDetail = IDL.Record({
    'code' : IDL.Text,
    'message' : IDL.Text,
  });
  const ApiError = IDL.Variant({
    'Internal' : ApiErrorDetail,
    'Rejected' : ApiErrorDetail,
    'InvalidArgument' : ApiErrorDetail,
  });
  const Result = IDL.Variant({ 'Ok' : EstimateIcTxOk, 'Err' : ApiError });
  const Result_1 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text });
  const ExportCursorView = IDL.Record({
    'byte_offset' : IDL.Nat32,
    'block_number' : IDL.Nat64,
    'segment' : IDL.Nat8,
  });
  const ExportChunkView = IDL.Record({
    'start' : IDL.Nat32,
    'segment' : IDL.Nat8,
    'payload_len' : IDL.Nat32,
    'bytes' : IDL.Vec(IDL.Nat8),
  });
  const ExportResponseView = IDL.Record({
    'next_cursor' : IDL.Opt(ExportCursorView),
    'chunks' : IDL.Vec(ExportChunkView),
  });
  const ExportErrorView = IDL.Variant({
    'Limit' : IDL.Null,
    'InvalidCursor' : IDL.Record({ 'message' : IDL.Text }),
    'MissingData' : IDL.Record({ 'message' : IDL.Text }),
    'Pruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
  });
  const Result_2 = IDL.Variant({
    'Ok' : ExportResponseView,
    'Err' : ExportErrorView,
  });
  const BlockView = IDL.Record({
    'tx_list_hash' : IDL.Vec(IDL.Nat8),
    'block_hash' : IDL.Vec(IDL.Nat8),
    'number' : IDL.Nat64,
    'timestamp' : IDL.Nat64,
    'tx_ids' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'state_root' : IDL.Vec(IDL.Nat8),
    'parent_hash' : IDL.Vec(IDL.Nat8),
  });
  const LookupError = IDL.Variant({
    'NotFound' : IDL.Null,
    'Pruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
    'Pending' : IDL.Null,
  });
  const Result_3 = IDL.Variant({ 'Ok' : BlockView, 'Err' : LookupError });
  const OpsModeView = IDL.Variant({
    'Low' : IDL.Null,
    'Normal' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const OpsConfigView = IDL.Record({
    'low_watermark' : IDL.Nat,
    'freeze_on_critical' : IDL.Bool,
    'critical' : IDL.Nat,
  });
  const OpsStatusView = IDL.Record({
    'needs_migration' : IDL.Bool,
    'critical_corrupt' : IDL.Bool,
    'decode_failure_last_ts' : IDL.Nat64,
    'log_filter_override' : IDL.Opt(IDL.Text),
    'last_cycle_balance' : IDL.Nat,
    'mode' : OpsModeView,
    'last_check_ts' : IDL.Nat64,
    'mining_error_count' : IDL.Nat64,
    'log_truncated_count' : IDL.Nat64,
    'query_instruction_soft_limit' : IDL.Nat64,
    'schema_version' : IDL.Nat32,
    'update_instruction_soft_limit' : IDL.Nat64,
    'safe_stop_latched' : IDL.Bool,
    'decode_failure_last_label' : IDL.Opt(IDL.Text),
    'prune_error_count' : IDL.Nat64,
    'block_gas_limit' : IDL.Nat64,
    'config' : OpsConfigView,
    'decode_failure_count' : IDL.Nat64,
  });
  const PendingStatusView = IDL.Variant({
    'Queued' : IDL.Record({ 'seq' : IDL.Nat64 }),
    'Included' : IDL.Record({
      'tx_index' : IDL.Nat32,
      'block_number' : IDL.Nat64,
    }),
    'Unknown' : IDL.Null,
    'Dropped' : IDL.Record({ 'code' : IDL.Nat16 }),
  });
  const PruneStatusView = IDL.Record({
    'pruning_enabled' : IDL.Bool,
    'hard_emergency_bytes' : IDL.Nat64,
    'pruned_before_block' : IDL.Opt(IDL.Nat64),
    'low_water_bytes' : IDL.Nat64,
    'high_water_bytes' : IDL.Nat64,
    'oldest_kept_timestamp' : IDL.Opt(IDL.Nat64),
    'estimated_kept_bytes' : IDL.Nat64,
    'need_prune' : IDL.Bool,
    'last_prune_at' : IDL.Nat64,
    'prune_running' : IDL.Bool,
    'oldest_kept_block' : IDL.Opt(IDL.Nat64),
  });
  const TxKindView = IDL.Variant({
    'EthSigned' : IDL.Null,
    'IcSynthetic' : IDL.Null,
  });
  const QueueItemView = IDL.Record({
    'seq' : IDL.Nat64,
    'tx_id' : IDL.Vec(IDL.Nat8),
    'kind' : TxKindView,
  });
  const QueueSnapshotView = IDL.Record({
    'next_cursor' : IDL.Opt(IDL.Nat64),
    'items' : IDL.Vec(QueueItemView),
  });
  const LogView = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'topics' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Vec(IDL.Nat8),
  });
  const ReceiptView = IDL.Record({
    'effective_gas_price' : IDL.Nat64,
    'status' : IDL.Nat8,
    'l1_data_fee' : IDL.Nat,
    'tx_id' : IDL.Vec(IDL.Nat8),
    'tx_index' : IDL.Nat32,
    'return_data_hash' : IDL.Vec(IDL.Nat8),
    'logs' : IDL.Vec(LogView),
    'return_data' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'total_fee' : IDL.Nat,
    'block_number' : IDL.Nat64,
    'operator_fee' : IDL.Nat,
    'gas_used' : IDL.Nat64,
    'contract_address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const Result_4 = IDL.Variant({ 'Ok' : ReceiptView, 'Err' : LookupError });
  const RequestDispatchStatusView = IDL.Variant({
    'Queued' : IDL.Null,
    'Dispatching' : IDL.Null,
    'Dispatched' : IDL.Null,
    'DispatchFailed' : IDL.Null,
  });
  const UnwrapDispatchOverviewView = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'status' : RequestDispatchStatusView,
    'error' : IDL.Opt(IDL.Text),
  });
  const HealthView = IDL.Record({
    'query_instruction_soft_limit' : IDL.Nat64,
    'update_instruction_soft_limit' : IDL.Nat64,
    'is_producing' : IDL.Bool,
    'mining_scheduled' : IDL.Bool,
    'block_gas_limit' : IDL.Nat64,
    'tip_hash' : IDL.Vec(IDL.Nat8),
    'tip_number' : IDL.Nat64,
    'auto_production_enabled' : IDL.Bool,
    'last_block_time' : IDL.Nat64,
    'queue_len' : IDL.Nat64,
  });
  const MemoryRegionView = IDL.Record({
    'id' : IDL.Nat8,
    'name' : IDL.Text,
    'pages' : IDL.Nat64,
    'bytes' : IDL.Nat64,
  });
  const MemoryBreakdownView = IDL.Record({
    'stable_bytes_total' : IDL.Nat64,
    'regions_pages_total' : IDL.Nat64,
    'regions' : IDL.Vec(MemoryRegionView),
    'unattributed_stable_pages' : IDL.Nat64,
    'unattributed_stable_bytes' : IDL.Nat64,
    'stable_pages_total' : IDL.Nat64,
    'heap_pages' : IDL.Nat64,
    'heap_bytes' : IDL.Nat64,
    'regions_bytes_total' : IDL.Nat64,
  });
  const DropCountView = IDL.Record({ 'code' : IDL.Nat16, 'count' : IDL.Nat64 });
  const MetricsView = IDL.Record({
    'txs' : IDL.Nat64,
    'ema_txs_per_block_x1000' : IDL.Nat64,
    'pruned_before_block' : IDL.Opt(IDL.Nat64),
    'ema_block_rate_per_sec_x1000' : IDL.Nat64,
    'total_submitted' : IDL.Nat64,
    'window' : IDL.Nat64,
    'avg_txs_per_block' : IDL.Nat64,
    'block_rate_per_sec_x1000' : IDL.Opt(IDL.Nat64),
    'cycles' : IDL.Nat,
    'total_dropped' : IDL.Nat64,
    'blocks' : IDL.Nat64,
    'drop_counts' : IDL.Vec(DropCountView),
    'queue_len' : IDL.Nat64,
    'total_included' : IDL.Nat64,
  });
  const Result_5 = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text });
  const PruneResultView = IDL.Record({
    'pruned_before_block' : IDL.Opt(IDL.Nat64),
    'did_work' : IDL.Bool,
    'remaining' : IDL.Nat64,
  });
  const ProduceBlockError = IDL.Variant({
    'Internal' : IDL.Text,
    'InvalidArgument' : IDL.Text,
  });
  const Result_6 = IDL.Variant({
    'Ok' : PruneResultView,
    'Err' : ProduceBlockError,
  });
  const RpcAccessListItemView = IDL.Record({
    'storage_keys' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Vec(IDL.Nat8),
  });
  const RpcCallObjectView = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'gas' : IDL.Opt(IDL.Nat64),
    'value' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'max_priority_fee_per_gas' : IDL.Opt(IDL.Nat),
    'data' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'max_fee_per_gas' : IDL.Opt(IDL.Nat),
    'chain_id' : IDL.Opt(IDL.Nat64),
    'nonce' : IDL.Opt(IDL.Nat64),
    'tx_type' : IDL.Opt(IDL.Nat64),
    'access_list' : IDL.Opt(IDL.Vec(RpcAccessListItemView)),
    'gas_price' : IDL.Opt(IDL.Nat),
  });
  const RpcCallResultView = IDL.Record({
    'status' : IDL.Nat8,
    'return_data' : IDL.Vec(IDL.Nat8),
    'gas_used' : IDL.Nat64,
    'revert_data' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const RpcErrorView = IDL.Record({
    'error_prefix' : IDL.Opt(IDL.Text),
    'code' : IDL.Nat32,
    'message' : IDL.Text,
  });
  const Result_7 = IDL.Variant({
    'Ok' : RpcCallResultView,
    'Err' : RpcErrorView,
  });
  const RpcBlockTagView = IDL.Variant({
    'Earliest' : IDL.Null,
    'Safe' : IDL.Null,
    'Finalized' : IDL.Null,
    'Latest' : IDL.Null,
    'Number' : IDL.Nat64,
    'Pending' : IDL.Null,
  });
  const Result_8 = IDL.Variant({ 'Ok' : IDL.Vec(IDL.Nat8), 'Err' : IDL.Text });
  const Result_9 = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : RpcErrorView });
  const RpcFeeHistoryView = IDL.Record({
    'reward' : IDL.Opt(IDL.Vec(IDL.Vec(IDL.Nat))),
    'base_fee_per_gas' : IDL.Vec(IDL.Nat64),
    'oldest_block' : IDL.Nat64,
    'gas_used_ratio' : IDL.Vec(IDL.Float64),
  });
  const Result_10 = IDL.Variant({
    'Ok' : RpcFeeHistoryView,
    'Err' : RpcErrorView,
  });
  const Result_11 = IDL.Variant({ 'Ok' : IDL.Nat, 'Err' : RpcErrorView });
  const Result_12 = IDL.Variant({
    'Ok' : IDL.Vec(IDL.Nat8),
    'Err' : RpcErrorView,
  });
  const DecodedTxView = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'value' : IDL.Vec(IDL.Nat8),
    'max_priority_fee_per_gas' : IDL.Opt(IDL.Nat),
    'from' : IDL.Vec(IDL.Nat8),
    'max_fee_per_gas' : IDL.Opt(IDL.Nat),
    'chain_id' : IDL.Opt(IDL.Nat64),
    'nonce' : IDL.Nat64,
    'gas_limit' : IDL.Nat64,
    'input' : IDL.Vec(IDL.Nat8),
    'gas_price' : IDL.Opt(IDL.Nat),
  });
  const EthTxView = IDL.Record({
    'raw' : IDL.Vec(IDL.Nat8),
    'tx_index' : IDL.Opt(IDL.Nat32),
    'block_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'decode_ok' : IDL.Bool,
    'hash' : IDL.Vec(IDL.Nat8),
    'kind' : TxKindView,
    'block_number' : IDL.Opt(IDL.Nat64),
    'eth_tx_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'caller_principal' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'decoded' : IDL.Opt(DecodedTxView),
  });
  const EthTxListView = IDL.Variant({
    'Full' : IDL.Vec(EthTxView),
    'Hashes' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const EthBlockView = IDL.Record({
    'txs' : EthTxListView,
    'base_fee_per_gas' : IDL.Opt(IDL.Nat64),
    'beneficiary' : IDL.Vec(IDL.Nat8),
    'block_hash' : IDL.Vec(IDL.Nat8),
    'number' : IDL.Nat64,
    'timestamp' : IDL.Nat64,
    'gas_limit' : IDL.Opt(IDL.Nat64),
    'gas_used' : IDL.Opt(IDL.Nat64),
    'state_root' : IDL.Vec(IDL.Nat8),
    'parent_hash' : IDL.Vec(IDL.Nat8),
  });
  const RpcBlockLookupView = IDL.Variant({
    'NotFound' : IDL.Null,
    'Found' : EthBlockView,
    'Pruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
  });
  const Result_13 = IDL.Variant({
    'Ok' : IDL.Opt(IDL.Nat64),
    'Err' : IDL.Text,
  });
  const EthLogFilterView = IDL.Record({
    'limit' : IDL.Opt(IDL.Nat32),
    'topic0' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'topic1' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'to_block' : IDL.Opt(IDL.Nat64),
    'from_block' : IDL.Opt(IDL.Nat64),
  });
  const EthLogsCursorView = IDL.Record({
    'tx_index' : IDL.Nat32,
    'log_index' : IDL.Nat32,
    'block_number' : IDL.Nat64,
  });
  const EthLogItemView = IDL.Record({
    'tx_index' : IDL.Nat32,
    'log_index' : IDL.Nat32,
    'data' : IDL.Vec(IDL.Nat8),
    'block_number' : IDL.Nat64,
    'topics' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Vec(IDL.Nat8),
    'eth_tx_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'tx_hash' : IDL.Vec(IDL.Nat8),
  });
  const EthLogsPageView = IDL.Record({
    'next_cursor' : IDL.Opt(EthLogsCursorView),
    'items' : IDL.Vec(EthLogItemView),
  });
  const GetLogsErrorView = IDL.Variant({
    'TooManyResults' : IDL.Null,
    'RangeTooLarge' : IDL.Null,
    'InvalidArgument' : IDL.Text,
    'UnsupportedFilter' : IDL.Text,
  });
  const Result_14 = IDL.Variant({
    'Ok' : EthLogsPageView,
    'Err' : GetLogsErrorView,
  });
  const EthReceiptLogView = IDL.Record({
    'log_index' : IDL.Nat32,
    'data' : IDL.Vec(IDL.Nat8),
    'topics' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'address' : IDL.Vec(IDL.Nat8),
  });
  const EthReceiptView = IDL.Record({
    'to' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'effective_gas_price' : IDL.Nat64,
    'status' : IDL.Nat8,
    'l1_data_fee' : IDL.Nat,
    'tx_index' : IDL.Nat32,
    'block_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'logs' : IDL.Vec(EthReceiptLogView),
    'total_fee' : IDL.Nat,
    'block_number' : IDL.Nat64,
    'operator_fee' : IDL.Nat,
    'eth_tx_hash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'gas_used' : IDL.Nat64,
    'contract_address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'tx_hash' : IDL.Vec(IDL.Nat8),
  });
  const RpcReceiptLookupView = IDL.Variant({
    'NotFound' : IDL.Null,
    'Found' : EthReceiptView,
    'PossiblyPruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
    'Pruned' : IDL.Record({ 'pruned_before_block' : IDL.Nat64 }),
  });
  const RpcHistoryWindowView = IDL.Record({
    'latest' : IDL.Nat64,
    'oldest_available' : IDL.Nat64,
  });
  const SubmitTxError = IDL.Variant({
    'Internal' : IDL.Text,
    'Rejected' : IDL.Text,
    'InvalidArgument' : IDL.Text,
  });
  const Result_15 = IDL.Variant({
    'Ok' : IDL.Vec(IDL.Nat8),
    'Err' : SubmitTxError,
  });
  const Result_16 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const PrunePolicyView = IDL.Record({
    'headroom_ratio_bps' : IDL.Nat32,
    'target_bytes' : IDL.Nat64,
    'retain_blocks' : IDL.Nat64,
    'retain_days' : IDL.Nat64,
    'hard_emergency_ratio_bps' : IDL.Nat32,
    'max_ops_per_tick' : IDL.Nat32,
  });
  
  return IDL.Service({
    'estimate_ic_tx' : IDL.Func([SubmitIcTxArgsDto], [Result], ['query']),
    'expected_nonce_by_address' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [Result_1],
        ['query'],
      ),
    'export_blocks' : IDL.Func(
        [IDL.Opt(ExportCursorView), IDL.Nat32],
        [Result_2],
        ['query'],
      ),
    'get_block' : IDL.Func([IDL.Nat64], [Result_3], ['query']),
    'get_cycle_balance' : IDL.Func([], [IDL.Nat], ['query']),
    'get_ops_status' : IDL.Func([], [OpsStatusView], ['query']),
    'get_pending' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [PendingStatusView],
        ['query'],
      ),
    'get_prune_status' : IDL.Func([], [PruneStatusView], ['query']),
    'get_queue_snapshot' : IDL.Func(
        [IDL.Nat32, IDL.Opt(IDL.Nat64)],
        [QueueSnapshotView],
        ['query'],
      ),
    'get_receipt' : IDL.Func([IDL.Vec(IDL.Nat8)], [Result_4], ['query']),
    'get_unwrap_dispatch_overview' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(UnwrapDispatchOverviewView)],
        ['query'],
      ),
    'get_unwrap_request_ids_by_tx_id' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'health' : IDL.Func([], [HealthView], ['query']),
    'memory_breakdown' : IDL.Func([], [MemoryBreakdownView], ['query']),
    'metrics' : IDL.Func([IDL.Nat64], [MetricsView], ['query']),
    'metrics_prometheus' : IDL.Func([], [Result_5], ['query']),
    'prune_blocks' : IDL.Func([IDL.Nat64, IDL.Nat32], [Result_6], []),
    'rpc_eth_block_number' : IDL.Func([], [IDL.Nat64], ['query']),
    'rpc_eth_call_object' : IDL.Func(
        [RpcCallObjectView],
        [Result_7],
        ['query'],
      ),
    'rpc_eth_call_object_at' : IDL.Func(
        [RpcCallObjectView, RpcBlockTagView],
        [Result_7],
        ['query'],
      ),
    'rpc_eth_call_rawtx' : IDL.Func([IDL.Vec(IDL.Nat8)], [Result_8], ['query']),
    'rpc_eth_chain_id' : IDL.Func([], [IDL.Nat64], ['query']),
    'rpc_eth_estimate_gas_object' : IDL.Func(
        [RpcCallObjectView],
        [Result_9],
        ['query'],
      ),
    'rpc_eth_estimate_gas_object_at' : IDL.Func(
        [RpcCallObjectView, RpcBlockTagView],
        [Result_9],
        ['query'],
      ),
    'rpc_eth_fee_history' : IDL.Func(
        [IDL.Nat64, RpcBlockTagView, IDL.Opt(IDL.Vec(IDL.Float64))],
        [Result_10],
        ['query'],
      ),
    'rpc_eth_gas_price' : IDL.Func([], [Result_11], ['query']),
    'rpc_eth_get_balance' : IDL.Func(
        [IDL.Vec(IDL.Nat8), RpcBlockTagView],
        [Result_12],
        ['query'],
      ),
    'rpc_eth_get_block_by_number' : IDL.Func(
        [IDL.Nat64, IDL.Bool],
        [IDL.Opt(EthBlockView)],
        ['query'],
      ),
    'rpc_eth_get_block_by_number_with_status' : IDL.Func(
        [IDL.Nat64, IDL.Bool],
        [RpcBlockLookupView],
        ['query'],
      ),
    'rpc_eth_get_block_number_by_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Nat32],
        [Result_13],
        ['query'],
      ),
    'rpc_eth_get_code' : IDL.Func(
        [IDL.Vec(IDL.Nat8), RpcBlockTagView],
        [Result_12],
        ['query'],
      ),
    'rpc_eth_get_logs_paged' : IDL.Func(
        [EthLogFilterView, IDL.Opt(EthLogsCursorView), IDL.Nat32],
        [Result_14],
        ['query'],
      ),
    'rpc_eth_get_storage_at' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), RpcBlockTagView],
        [Result_12],
        ['query'],
      ),
    'rpc_eth_get_transaction_by_eth_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(EthTxView)],
        ['query'],
      ),
    'rpc_eth_get_transaction_by_tx_id' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(EthTxView)],
        ['query'],
      ),
    'rpc_eth_get_transaction_count_at' : IDL.Func(
        [IDL.Vec(IDL.Nat8), RpcBlockTagView],
        [Result_9],
        ['query'],
      ),
    'rpc_eth_get_transaction_receipt_by_eth_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(EthReceiptView)],
        ['query'],
      ),
    'rpc_eth_get_transaction_receipt_with_status_by_eth_hash' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [RpcReceiptLookupView],
        ['query'],
      ),
    'rpc_eth_get_transaction_receipt_with_status_by_tx_id' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [RpcReceiptLookupView],
        ['query'],
      ),
    'rpc_eth_history_window' : IDL.Func([], [RpcHistoryWindowView], ['query']),
    'rpc_eth_max_priority_fee_per_gas' : IDL.Func([], [Result_11], ['query']),
    'rpc_eth_send_raw_transaction' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [Result_15],
        [],
      ),
    'set_log_filter' : IDL.Func([IDL.Opt(IDL.Text)], [Result_16], []),
    'set_prune_policy' : IDL.Func([PrunePolicyView], [Result_16], []),
    'set_pruning_enabled' : IDL.Func([IDL.Bool], [Result_16], []),
    'submit_ic_tx' : IDL.Func([SubmitIcTxArgsDto], [Result_15], []),
  });
};

export const init = ({ IDL }) => {
  const GenesisBalanceView = IDL.Record({
    'address' : IDL.Vec(IDL.Nat8),
    'amount' : IDL.Nat,
  });
  const InitArgs = IDL.Record({
    'genesis_balances' : IDL.Vec(GenesisBalanceView),
    'query_instruction_soft_limit' : IDL.Opt(IDL.Nat64),
    'update_instruction_soft_limit' : IDL.Opt(IDL.Nat64),
    'wrap_canister_id' : IDL.Principal,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  
  return [IDL.Opt(InitArgs)];
};