-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_bitwise_extracted]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace BitwiseExtracted

/-- [core::ub_checks::check_language_ub::runtime]:
    Source: '/rustc/library/core/src/intrinsics/mod.rs', lines 2526:8-2526:63
    Name pattern: [core::ub_checks::check_language_ub::runtime] -/
@[rust_fun "core::ub_checks::check_language_ub::runtime"]
def core.ub_checks.check_language_ub.runtime : Result Bool := do
  ok (¬ true)

/-- [core::ub_checks::check_language_ub]:
    Source: '/rustc/library/core/src/ub_checks.rs', lines 96:0-96:47
    Name pattern: [core::ub_checks::check_language_ub] -/
@[rust_fun "core::ub_checks::check_language_ub"]
def core.ub_checks.check_language_ub : Result Bool := do
  let b ← core.ub_checks.check_language_ub.runtime
  if b
  then ok false
  else ok false

/-- [core::num::{usize}::unchecked_add::precondition_check]:
    Source: '/rustc/library/core/src/ub_checks.rs', lines 68:12-68:55
    Name pattern: [core::num::{usize}::unchecked_add::precondition_check] -/
@[rust_fun "core::num::{usize}::unchecked_add::precondition_check"]
def core.num.Usize.unchecked_add.precondition_check
  (lhs : Std.Usize) (rhs : Std.Usize) : Result Unit := do
  let (_, b) ← lift (core.num.Usize.overflowing_add lhs rhs)
  massert (¬ b)

/-- [core::num::{usize}::unchecked_add]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 1031:8-1031:66
    Name pattern: [core::num::{usize}::unchecked_add]
    Visibility: public -/
@[rust_fun "core::num::{usize}::unchecked_add"]
def core.num.Usize.unchecked_add
  (self : Std.Usize) (rhs : Std.Usize) : Result Std.Usize := do
  let b ← core.ub_checks.check_language_ub
  if b
  then core.num.Usize.unchecked_add.precondition_check self rhs
  else ok ()
  self + rhs

/-- [ruint::Uint]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 158:0-158:54
    Name pattern: [ruint::Uint]
    Visibility: public -/
@[rust_type "ruint::Uint"]
structure ruint.Uint (BITS : Std.Usize) (LIMBS : Std.Usize) where
  limbs : Array Std.U64 LIMBS

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitand]: loop body 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:8-120:9
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitand]
    Visibility: public -/
@[rust_loop_body, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitand"]
def ruint.bits.Uint.bitand_loop.body
  {BITS : Std.Usize} {LIMBS : Std.Usize} (rhs : ruint.Uint BITS LIMBS)
  (self : ruint.Uint BITS LIMBS) (iter : Std.Usize) :
  Result (ControlFlow ((ruint.Uint BITS LIMBS) × Std.Usize) (ruint.Uint BITS
    LIMBS))
  := do
  if iter < LIMBS
  then
    let iter1 ← core.num.Usize.unchecked_add iter 1#usize
    let i ← Array.index_usize rhs.limbs iter
    let i1 ← Array.index_usize self.limbs iter
    let i2 ← lift (i1 &&& i)
    let a ← Array.update self.limbs iter i2
    ok (cont ({ limbs := a }, iter1))
  else ok (done self)

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitand]: loop 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:8-120:9
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitand]
    Visibility: public -/
@[rust_loop, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitand"]
def ruint.bits.Uint.bitand_loop
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) (iter : Std.Usize) :
  Result (ruint.Uint BITS LIMBS)
  := do
  loop
    (fun (self1, iter1) => ruint.bits.Uint.bitand_loop.body rhs self1 iter1)
    (self, iter)

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitand]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 774:12-774:83
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitand]
    Visibility: public -/
@[reducible, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitand"]
def ruint.bits.Uint.bitand
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.bits.Uint.bitand_loop self rhs 0#usize

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitor]: loop body 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:8-120:9
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitor]
    Visibility: public -/
@[rust_loop_body, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitor"]
def ruint.bits.Uint.bitor_loop.body
  {BITS : Std.Usize} {LIMBS : Std.Usize} (rhs : ruint.Uint BITS LIMBS)
  (self : ruint.Uint BITS LIMBS) (iter : Std.Usize) :
  Result (ControlFlow ((ruint.Uint BITS LIMBS) × Std.Usize) (ruint.Uint BITS
    LIMBS))
  := do
  if iter < LIMBS
  then
    let iter1 ← core.num.Usize.unchecked_add iter 1#usize
    let i ← Array.index_usize rhs.limbs iter
    let i1 ← Array.index_usize self.limbs iter
    let i2 ← lift (i1 ||| i)
    let a ← Array.update self.limbs iter i2
    ok (cont ({ limbs := a }, iter1))
  else ok (done self)

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitor]: loop 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:8-120:9
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitor]
    Visibility: public -/
@[rust_loop, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitor"]
def ruint.bits.Uint.bitor_loop
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) (iter : Std.Usize) :
  Result (ruint.Uint BITS LIMBS)
  := do
  loop
    (fun (self1, iter1) => ruint.bits.Uint.bitor_loop.body rhs self1 iter1)
    (self, iter)

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitor]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 774:12-774:83
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitor]
    Visibility: public -/
@[reducible, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitor"]
def ruint.bits.Uint.bitor
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.bits.Uint.bitor_loop self rhs 0#usize

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitxor]: loop body 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:8-120:9
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitxor]
    Visibility: public -/
@[rust_loop_body, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitxor"]
def ruint.bits.Uint.bitxor_loop.body
  {BITS : Std.Usize} {LIMBS : Std.Usize} (rhs : ruint.Uint BITS LIMBS)
  (self : ruint.Uint BITS LIMBS) (iter : Std.Usize) :
  Result (ControlFlow ((ruint.Uint BITS LIMBS) × Std.Usize) (ruint.Uint BITS
    LIMBS))
  := do
  if iter < LIMBS
  then
    let iter1 ← core.num.Usize.unchecked_add iter 1#usize
    let i ← Array.index_usize rhs.limbs iter
    let i1 ← Array.index_usize self.limbs iter
    let i2 ← lift (i1 ^^^ i)
    let a ← Array.update self.limbs iter i2
    ok (cont ({ limbs := a }, iter1))
  else ok (done self)

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitxor]: loop 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:8-120:9
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitxor]
    Visibility: public -/
@[rust_loop, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitxor"]
def ruint.bits.Uint.bitxor_loop
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) (iter : Std.Usize) :
  Result (ruint.Uint BITS LIMBS)
  := do
  loop
    (fun (self1, iter1) => ruint.bits.Uint.bitxor_loop.body rhs self1 iter1)
    (self, iter)

/-- [ruint::bits::{ruint::Uint<BITS, LIMBS>}::bitxor]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 774:12-774:83
    Name pattern: [ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitxor]
    Visibility: public -/
@[reducible, rust_fun "ruint::bits::{ruint::Uint<@BITS, @LIMBS>}::bitxor"]
def ruint.bits.Uint.bitxor
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.bits.Uint.bitxor_loop self rhs 0#usize

/-- [kasane_bitwise_extracted::bitand]:
    Source: 'lib.rs', lines 2:0-2:55
    Visibility: public -/
def bitand
  (a : ruint.Uint 256#usize 4#usize) (b : ruint.Uint 256#usize 4#usize) :
  Result (ruint.Uint 256#usize 4#usize)
  := do
  ruint.bits.Uint.bitand a b

/-- [kasane_bitwise_extracted::bitor]:
    Source: 'lib.rs', lines 3:0-3:53
    Visibility: public -/
def bitor
  (a : ruint.Uint 256#usize 4#usize) (b : ruint.Uint 256#usize 4#usize) :
  Result (ruint.Uint 256#usize 4#usize)
  := do
  ruint.bits.Uint.bitor a b

/-- [kasane_bitwise_extracted::bitxor]:
    Source: 'lib.rs', lines 4:0-4:55
    Visibility: public -/
def bitxor
  (a : ruint.Uint 256#usize 4#usize) (b : ruint.Uint 256#usize 4#usize) :
  Result (ruint.Uint 256#usize 4#usize)
  := do
  ruint.bits.Uint.bitxor a b

end BitwiseExtracted
