-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_ledger_timestamp_probe]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace LedgerTime

/-- [kasane_ledger_timestamp_probe::timestamp::TimeStamp]
    Source: 'timestamp.rs', lines 28:0-31:1
    Visibility: public -/
structure timestamp.TimeStamp where
  timestamp_nanos : Std.U64

/-- [kasane_ledger_timestamp_probe::timestamp::{kasane_ledger_timestamp_probe::timestamp::TimeStamp}::from_nanos_since_unix_epoch]:
    Source: 'timestamp.rs', lines 41:4-45:5
    Visibility: public -/
def timestamp.TimeStamp.from_nanos_since_unix_epoch
  (nanos : Std.U64) : Result timestamp.TimeStamp := do
  ok { timestamp_nanos := nanos }

/-- [kasane_ledger_timestamp_probe::from_nanos]:
    Source: 'lib.rs', lines 11:0-11:92
    Visibility: public -/
def from_nanos (nanos : Std.U64) : Result timestamp.TimeStamp := do
  timestamp.TimeStamp.from_nanos_since_unix_epoch nanos

/-- [kasane_ledger_timestamp_probe::timestamp::{kasane_ledger_timestamp_probe::timestamp::TimeStamp}::as_nanos_since_unix_epoch]:
    Source: 'timestamp.rs', lines 47:4-49:5
    Visibility: public -/
def timestamp.TimeStamp.as_nanos_since_unix_epoch
  (self : timestamp.TimeStamp) : Result Std.U64 := do
  ok self.timestamp_nanos

/-- [kasane_ledger_timestamp_probe::get_nanos]:
    Source: 'lib.rs', lines 12:0-12:71
    Visibility: public -/
def get_nanos (t : timestamp.TimeStamp) : Result Std.U64 := do
  timestamp.TimeStamp.as_nanos_since_unix_epoch t

/-- [kasane_ledger_timestamp_probe::timestamp::{kasane_ledger_timestamp_probe::timestamp::TimeStamp}::new]:
    Source: 'timestamp.rs', lines 34:4-39:5
    Visibility: public -/
def timestamp.TimeStamp.new
  (secs : Std.U64) (nanos : Std.U32) : Result timestamp.TimeStamp := do
  massert (nanos < 1000000000#u32)
  let i ← secs * 1000000000#u64
  let i1 ← lift (UScalar.cast .U64 nanos)
  let i2 ← i + i1
  ok { timestamp_nanos := i2 }

/-- [kasane_ledger_timestamp_probe::new_time]:
    Source: 'lib.rs', lines 13:0-13:83
    Visibility: public -/
def new_time
  (secs : Std.U64) (nanos : Std.U32) : Result timestamp.TimeStamp := do
  timestamp.TimeStamp.new secs nanos

end LedgerTime
