-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_mono_lifetime_probe]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace MonoLifetimeGeneric

/-- [kasane_mono_lifetime_probe::Same]
    Source: 'lib.rs', lines 2:0-5:1
    Visibility: public -/
structure Same where
  left : Std.U32
  right : Std.U32

/-- [kasane_mono_lifetime_probe::Split]
    Source: 'lib.rs', lines 7:0-10:1
    Visibility: public -/
structure Split where
  left : Std.U32
  right : Std.U32

/-- [kasane_mono_lifetime_probe::same_noop]:
    Source: 'lib.rs', lines 12:0-12:39
    Visibility: public -/
def same_noop (_context : Same) : Result Same := do
  ok _context

/-- [kasane_mono_lifetime_probe::split_noop]:
    Source: 'lib.rs', lines 14:0-14:45
    Visibility: public -/
def split_noop (_context : Split) : Result (Split × Split) := do
  ok (_context, _context)

/-- [kasane_mono_lifetime_probe::split_left]:
    Source: 'lib.rs', lines 16:0-18:1
    Visibility: public -/
def split_left
  (context : Split) : Result (Std.U32 × (Std.U32 → Split) × Split) := do
  let back'a := fun i => { context with left := i }
  ok (context.left, back'a, context)

/-- [kasane_mono_lifetime_probe::split_right]:
    Source: 'lib.rs', lines 20:0-22:1
    Visibility: public -/
def split_right
  (context : Split) : Result (Std.U32 × Split × (Std.U32 → Split)) := do
  let back'b := fun i => { context with right := i }
  ok (context.right, context, back'b)

end MonoLifetimeGeneric
