-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [evm_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RevmResult

/-- [revm_interpreter::instruction_result::InstructionResult]
    Source: 'vendor/revm/crates/interpreter/src/instruction_result.rs', lines 14:0-14:26
    Name pattern: [revm_interpreter::instruction_result::InstructionResult]
    Visibility: public -/
@[discriminant u8 [1,2,3,16,17,18,19,20,21,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54],
  rust_type "revm_interpreter::instruction_result::InstructionResult"]
inductive revm_interpreter.instruction_result.InstructionResult where
| Stop : revm_interpreter.instruction_result.InstructionResult
| Return : revm_interpreter.instruction_result.InstructionResult
| SelfDestruct : revm_interpreter.instruction_result.InstructionResult
| Revert : revm_interpreter.instruction_result.InstructionResult
| CallTooDeep : revm_interpreter.instruction_result.InstructionResult
| OutOfFunds : revm_interpreter.instruction_result.InstructionResult
| CreateInitCodeStartingEF00 :
  revm_interpreter.instruction_result.InstructionResult
| InvalidEOFInitCode : revm_interpreter.instruction_result.InstructionResult
| InvalidExtDelegateCallTarget :
  revm_interpreter.instruction_result.InstructionResult
| OutOfGas : revm_interpreter.instruction_result.InstructionResult
| MemoryOOG : revm_interpreter.instruction_result.InstructionResult
| MemoryLimitOOG : revm_interpreter.instruction_result.InstructionResult
| PrecompileOOG : revm_interpreter.instruction_result.InstructionResult
| InvalidOperandOOG : revm_interpreter.instruction_result.InstructionResult
| ReentrancySentryOOG : revm_interpreter.instruction_result.InstructionResult
| OpcodeNotFound : revm_interpreter.instruction_result.InstructionResult
| CallNotAllowedInsideStatic :
  revm_interpreter.instruction_result.InstructionResult
| StateChangeDuringStaticCall :
  revm_interpreter.instruction_result.InstructionResult
| InvalidFEOpcode : revm_interpreter.instruction_result.InstructionResult
| InvalidJump : revm_interpreter.instruction_result.InstructionResult
| NotActivated : revm_interpreter.instruction_result.InstructionResult
| StackUnderflow : revm_interpreter.instruction_result.InstructionResult
| StackOverflow : revm_interpreter.instruction_result.InstructionResult
| OutOfOffset : revm_interpreter.instruction_result.InstructionResult
| CreateCollision : revm_interpreter.instruction_result.InstructionResult
| OverflowPayment : revm_interpreter.instruction_result.InstructionResult
| PrecompileError : revm_interpreter.instruction_result.InstructionResult
| NonceOverflow : revm_interpreter.instruction_result.InstructionResult
| CreateContractSizeLimit :
  revm_interpreter.instruction_result.InstructionResult
| CreateContractStartingWithEF :
  revm_interpreter.instruction_result.InstructionResult
| CreateInitCodeSizeLimit :
  revm_interpreter.instruction_result.InstructionResult
| FatalExternalError : revm_interpreter.instruction_result.InstructionResult

/-- [revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_ok]:
    Source: 'vendor/revm/crates/interpreter/src/instruction_result.rs', lines 199:4-199:36
    Name pattern: [revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_ok]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_ok"]
def revm_interpreter.instruction_result.InstructionResult.is_ok
  (self : revm_interpreter.instruction_result.InstructionResult) :
  Result Bool
  := do
  match self with
  | revm_interpreter.instruction_result.InstructionResult.Stop => ok true
  | revm_interpreter.instruction_result.InstructionResult.Return => ok true
  | revm_interpreter.instruction_result.InstructionResult.SelfDestruct =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.Revert => ok false
  | revm_interpreter.instruction_result.InstructionResult.CallTooDeep =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OutOfFunds =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateInitCodeStartingEF00
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidEOFInitCode =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.InvalidExtDelegateCallTarget
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OutOfGas => ok false
  | revm_interpreter.instruction_result.InstructionResult.MemoryOOG => ok false
  | revm_interpreter.instruction_result.InstructionResult.MemoryLimitOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.PrecompileOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidOperandOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.ReentrancySentryOOG
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OpcodeNotFound =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CallNotAllowedInsideStatic
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.StateChangeDuringStaticCall
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidFEOpcode =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidJump =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.NotActivated =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.StackUnderflow =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.StackOverflow =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OutOfOffset =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.CreateCollision =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OverflowPayment =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.PrecompileError =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.NonceOverflow =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateContractSizeLimit
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateContractStartingWithEF
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateInitCodeSizeLimit
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.FatalExternalError =>
    ok false

/-- [revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_ok_or_revert]:
    Source: 'vendor/revm/crates/interpreter/src/instruction_result.rs', lines 205:4-205:46
    Name pattern: [revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_ok_or_revert]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_ok_or_revert"]
def revm_interpreter.instruction_result.InstructionResult.is_ok_or_revert
  (self : revm_interpreter.instruction_result.InstructionResult) :
  Result Bool
  := do
  match self with
  | revm_interpreter.instruction_result.InstructionResult.Stop => ok true
  | revm_interpreter.instruction_result.InstructionResult.Return => ok true
  | revm_interpreter.instruction_result.InstructionResult.SelfDestruct =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.Revert => ok true
  | revm_interpreter.instruction_result.InstructionResult.CallTooDeep =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.OutOfFunds => ok true
  |
    revm_interpreter.instruction_result.InstructionResult.CreateInitCodeStartingEF00
    =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.InvalidEOFInitCode =>
    ok true
  |
    revm_interpreter.instruction_result.InstructionResult.InvalidExtDelegateCallTarget
    =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.OutOfGas => ok false
  | revm_interpreter.instruction_result.InstructionResult.MemoryOOG => ok false
  | revm_interpreter.instruction_result.InstructionResult.MemoryLimitOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.PrecompileOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidOperandOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.ReentrancySentryOOG
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OpcodeNotFound =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CallNotAllowedInsideStatic
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.StateChangeDuringStaticCall
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidFEOpcode =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidJump =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.NotActivated =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.StackUnderflow =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.StackOverflow =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OutOfOffset =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.CreateCollision =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OverflowPayment =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.PrecompileError =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.NonceOverflow =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateContractSizeLimit
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateContractStartingWithEF
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateInitCodeSizeLimit
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.FatalExternalError =>
    ok false

/-- [revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_revert]:
    Source: 'vendor/revm/crates/interpreter/src/instruction_result.rs', lines 211:4-211:40
    Name pattern: [revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_revert]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_revert"]
def revm_interpreter.instruction_result.InstructionResult.is_revert
  (self : revm_interpreter.instruction_result.InstructionResult) :
  Result Bool
  := do
  match self with
  | revm_interpreter.instruction_result.InstructionResult.Stop => ok false
  | revm_interpreter.instruction_result.InstructionResult.Return => ok false
  | revm_interpreter.instruction_result.InstructionResult.SelfDestruct =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.Revert => ok true
  | revm_interpreter.instruction_result.InstructionResult.CallTooDeep =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.OutOfFunds => ok true
  |
    revm_interpreter.instruction_result.InstructionResult.CreateInitCodeStartingEF00
    =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.InvalidEOFInitCode =>
    ok true
  |
    revm_interpreter.instruction_result.InstructionResult.InvalidExtDelegateCallTarget
    =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.OutOfGas => ok false
  | revm_interpreter.instruction_result.InstructionResult.MemoryOOG => ok false
  | revm_interpreter.instruction_result.InstructionResult.MemoryLimitOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.PrecompileOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidOperandOOG =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.ReentrancySentryOOG
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OpcodeNotFound =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CallNotAllowedInsideStatic
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.StateChangeDuringStaticCall
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidFEOpcode =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidJump =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.NotActivated =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.StackUnderflow =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.StackOverflow =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OutOfOffset =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.CreateCollision =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OverflowPayment =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.PrecompileError =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.NonceOverflow =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateContractSizeLimit
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateContractStartingWithEF
    =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateInitCodeSizeLimit
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.FatalExternalError =>
    ok false

/-- [revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_error]:
    Source: 'vendor/revm/crates/interpreter/src/instruction_result.rs', lines 217:4-217:39
    Name pattern: [revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_error]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::instruction_result::{revm_interpreter::instruction_result::InstructionResult}::is_error"]
def revm_interpreter.instruction_result.InstructionResult.is_error
  (self : revm_interpreter.instruction_result.InstructionResult) :
  Result Bool
  := do
  match self with
  | revm_interpreter.instruction_result.InstructionResult.Stop => ok false
  | revm_interpreter.instruction_result.InstructionResult.Return => ok false
  | revm_interpreter.instruction_result.InstructionResult.SelfDestruct =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.Revert => ok false
  | revm_interpreter.instruction_result.InstructionResult.CallTooDeep =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OutOfFunds =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.CreateInitCodeStartingEF00
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.InvalidEOFInitCode =>
    ok false
  |
    revm_interpreter.instruction_result.InstructionResult.InvalidExtDelegateCallTarget
    =>
    ok false
  | revm_interpreter.instruction_result.InstructionResult.OutOfGas => ok true
  | revm_interpreter.instruction_result.InstructionResult.MemoryOOG => ok true
  | revm_interpreter.instruction_result.InstructionResult.MemoryLimitOOG =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.PrecompileOOG =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.InvalidOperandOOG =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.ReentrancySentryOOG
    =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.OpcodeNotFound =>
    ok true
  |
    revm_interpreter.instruction_result.InstructionResult.CallNotAllowedInsideStatic
    =>
    ok true
  |
    revm_interpreter.instruction_result.InstructionResult.StateChangeDuringStaticCall
    =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.InvalidFEOpcode =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.InvalidJump =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.NotActivated =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.StackUnderflow =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.StackOverflow =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.OutOfOffset =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.CreateCollision =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.OverflowPayment =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.PrecompileError =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.NonceOverflow =>
    ok true
  |
    revm_interpreter.instruction_result.InstructionResult.CreateContractSizeLimit
    =>
    ok true
  |
    revm_interpreter.instruction_result.InstructionResult.CreateContractStartingWithEF
    =>
    ok true
  |
    revm_interpreter.instruction_result.InstructionResult.CreateInitCodeSizeLimit
    =>
    ok true
  | revm_interpreter.instruction_result.InstructionResult.FatalExternalError =>
    ok true

end RevmResult
