-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [evm_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RevmExecuteDynamic

/-- [revm_interpreter::gas::MemoryGas]
    Source: 'vendor/revm/crates/interpreter/src/gas.rs', lines 176:0-176:20
    Name pattern: [revm_interpreter::gas::MemoryGas]
    Visibility: public -/
@[rust_type "revm_interpreter::gas::MemoryGas"]
structure revm_interpreter.gas.MemoryGas where
  words_num : Std.Usize
  expansion_cost : Std.U64

/-- [revm_interpreter::gas::Gas]
    Source: 'vendor/revm/crates/interpreter/src/gas.rs', lines 8:0-8:14
    Name pattern: [revm_interpreter::gas::Gas]
    Visibility: public -/
@[rust_type "revm_interpreter::gas::Gas"]
structure revm_interpreter.gas.Gas where
  limit : Std.U64
  remaining : Std.U64
  refunded : Std.I64
  memory : revm_interpreter.gas.MemoryGas

/-- [revm_interpreter::interpreter::Interpreter]
    Source: 'vendor/revm/crates/interpreter/src/interpreter.rs', lines 32:0-32:63
    Name pattern: [revm_interpreter::interpreter::Interpreter]
    Visibility: public -/
@[rust_type "revm_interpreter::interpreter::Interpreter"]
structure revm_interpreter.interpreter.Interpreter (WIRE : Type) (Clause0_Stack
  : Type) (Clause0_Memory : Type) (Clause0_Bytecode : Type) (Clause0_ReturnData
  : Type) (Clause0_Input : Type) (Clause0_RuntimeFlag : Type) (Clause0_Extend :
  Type) (Clause0_Output : Type) where
  bytecode : Clause0_Bytecode
  gas : revm_interpreter.gas.Gas
  stack : Clause0_Stack
  return_data : Clause0_ReturnData
  memory : Clause0_Memory
  input : Clause0_Input
  runtime_flag : Clause0_RuntimeFlag
  extend : Clause0_Extend

/-- [revm_interpreter::instruction_context::InstructionContext]
    Source: 'vendor/revm/crates/interpreter/src/instruction_context.rs', lines 6:0-6:67
    Name pattern: [revm_interpreter::instruction_context::InstructionContext]
    Visibility: public -/
@[rust_type "revm_interpreter::instruction_context::InstructionContext"
  (mutRegions := #[0])]
structure revm_interpreter.instruction_context.InstructionContext (H : Type)
  (ITy : Type) (Clause0_Stack : Type) (Clause0_Memory : Type) (Clause0_Bytecode
  : Type) (Clause0_ReturnData : Type) (Clause0_Input : Type)
  (Clause0_RuntimeFlag : Type) (Clause0_Extend : Type) (Clause0_Output : Type)
  where
  interpreter : revm_interpreter.interpreter.Interpreter ITy Clause0_Stack
    Clause0_Memory Clause0_Bytecode Clause0_ReturnData Clause0_Input
    Clause0_RuntimeFlag Clause0_Extend Clause0_Output
  host : H

/-- [revm_interpreter::instructions::Instruction]
    Source: 'vendor/revm/crates/interpreter/src/instructions.rs', lines 37:0-37:54
    Name pattern: [revm_interpreter::instructions::Instruction]
    Visibility: public -/
@[rust_type "revm_interpreter::instructions::Instruction"]
structure revm_interpreter.instructions.Instruction (W : Type) (H : Type)
  (Clause0_Stack : Type) (Clause0_Memory : Type) (Clause0_Bytecode : Type)
  (Clause0_ReturnData : Type) (Clause0_Input : Type) (Clause0_RuntimeFlag :
  Type) (Clause0_Extend : Type) (Clause0_Output : Type) where
  fn_ : revm_interpreter.instruction_context.InstructionContext H W
    Clause0_Stack Clause0_Memory Clause0_Bytecode Clause0_ReturnData
    Clause0_Input Clause0_RuntimeFlag Clause0_Extend Clause0_Output → Result
    (revm_interpreter.instruction_context.InstructionContext H W Clause0_Stack
    Clause0_Memory Clause0_Bytecode Clause0_ReturnData Clause0_Input
    Clause0_RuntimeFlag Clause0_Extend Clause0_Output)
  static_gas : Std.U64

/-- [revm_interpreter::instructions::{revm_interpreter::instructions::Instruction<W, H, Clause0_Stack, Clause0_Memory, Clause0_Bytecode, Clause0_ReturnData, Clause0_Input, Clause0_RuntimeFlag, Clause0_Extend, Clause0_Output>}::execute]:
    Source: 'vendor/revm/crates/interpreter/src/instructions.rs', lines 60:4-60:59
    Name pattern: [revm_interpreter::instructions::{revm_interpreter::instructions::Instruction<@W, @H, @Clause0_Stack, @Clause0_Memory, @Clause0_Bytecode, @Clause0_ReturnData, @Clause0_Input, @Clause0_RuntimeFlag, @Clause0_Extend, @Clause0_Output>}::execute]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::instructions::{revm_interpreter::instructions::Instruction<@W, @H, @Clause0_Stack, @Clause0_Memory, @Clause0_Bytecode, @Clause0_ReturnData, @Clause0_Input, @Clause0_RuntimeFlag, @Clause0_Extend, @Clause0_Output>}::execute"]
def revm_interpreter.instructions.Instruction.execute
  {W : Type} {H : Type} {Clause0_Stack : Type} {Clause0_Memory : Type}
  {Clause0_Bytecode : Type} {Clause0_ReturnData : Type} {Clause0_Input : Type}
  {Clause0_RuntimeFlag : Type} {Clause0_Extend : Type} {Clause0_Output : Type}
  (self : revm_interpreter.instructions.Instruction W H Clause0_Stack
  Clause0_Memory Clause0_Bytecode Clause0_ReturnData Clause0_Input
  Clause0_RuntimeFlag Clause0_Extend Clause0_Output)
  (ctx : revm_interpreter.instruction_context.InstructionContext H W
  Clause0_Stack Clause0_Memory Clause0_Bytecode Clause0_ReturnData
  Clause0_Input Clause0_RuntimeFlag Clause0_Extend Clause0_Output) :
  Result (revm_interpreter.instruction_context.InstructionContext H W
    Clause0_Stack Clause0_Memory Clause0_Bytecode Clause0_ReturnData
    Clause0_Input Clause0_RuntimeFlag Clause0_Extend Clause0_Output)
  := do
  self.fn_ ctx

end RevmExecuteDynamic
