-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [evm_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RevmGas

/-- [revm_interpreter::gas::MemoryGas]
    Source: 'vendor/revm/crates/interpreter/src/gas.rs', lines 176:0-176:20
    Name pattern: [revm_interpreter::gas::MemoryGas]
    Visibility: public -/
@[rust_type "revm_interpreter::gas::MemoryGas"]
structure revm_interpreter.gas.MemoryGas where
  words_num : Std.Usize
  expansion_cost : Std.U64

/-- [revm_interpreter::gas::Gas]
    Source: 'vendor/revm/crates/interpreter/src/gas.rs', lines 8:0-8:14
    Name pattern: [revm_interpreter::gas::Gas]
    Visibility: public -/
@[rust_type "revm_interpreter::gas::Gas"]
structure revm_interpreter.gas.Gas where
  limit : Std.U64
  remaining : Std.U64
  refunded : Std.I64
  memory : revm_interpreter.gas.MemoryGas

/-- [revm_interpreter::gas::{revm_interpreter::gas::Gas}::record_cost]:
    Source: 'vendor/revm/crates/interpreter/src/gas.rs', lines 139:4-139:52
    Name pattern: [revm_interpreter::gas::{revm_interpreter::gas::Gas}::record_cost]
    Visibility: public -/
@[rust_fun "revm_interpreter::gas::{revm_interpreter::gas::Gas}::record_cost"]
def revm_interpreter.gas.Gas.record_cost
  (self : revm_interpreter.gas.Gas) (cost : Std.U64) :
  Result (Bool × revm_interpreter.gas.Gas)
  := do
  let o ← lift (U64.checked_sub self.remaining cost)
  match o with
  | none => ok (false, self)
  | some new_remaining => ok (true, { self with remaining := new_remaining })

/-- [revm_interpreter::gas::{revm_interpreter::gas::Gas}::record_cost_unsafe]:
    Source: 'vendor/revm/crates/interpreter/src/gas.rs', lines 152:4-152:59
    Name pattern: [revm_interpreter::gas::{revm_interpreter::gas::Gas}::record_cost_unsafe]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::gas::{revm_interpreter::gas::Gas}::record_cost_unsafe"]
def revm_interpreter.gas.Gas.record_cost_unsafe
  (self : revm_interpreter.gas.Gas) (cost : Std.U64) :
  Result (Bool × revm_interpreter.gas.Gas)
  := do
  let i ← lift (core.num.U64.wrapping_sub self.remaining cost)
  ok (self.remaining < cost, { self with remaining := i })

end RevmGas
