-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [evm_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace StdBorrowCounter

/-- [core::cell::UNUSED]
    Source: '/rustc/library/core/src/cell.rs', lines 949:0-949:27
    Name pattern: [core::cell::UNUSED] -/
@[global_simps, irreducible, rust_const "core::cell::UNUSED"]
def core.cell.UNUSED : Std.Isize := 0#isize

/-- [core::cell::is_writing]:
    Source: '/rustc/library/core/src/cell.rs', lines 952:0-952:45
    Name pattern: [core::cell::is_writing] -/
@[rust_fun "core::cell::is_writing"]
def core.cell.is_writing (x : Std.Isize) : Result Bool := do
  ok (x < core.cell.UNUSED)

/-- [core::cell::is_reading]:
    Source: '/rustc/library/core/src/cell.rs', lines 957:0-957:45
    Name pattern: [core::cell::is_reading] -/
@[rust_fun "core::cell::is_reading"]
def core.cell.is_reading (x : Std.Isize) : Result Bool := do
  ok (x > core.cell.UNUSED)

end StdBorrowCounter
