-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_u256_extracted]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace U256Extracted

/-- [core::ub_checks::check_language_ub::runtime]:
    Source: '/rustc/library/core/src/intrinsics/mod.rs', lines 2526:8-2526:63
    Name pattern: [core::ub_checks::check_language_ub::runtime] -/
@[rust_fun "core::ub_checks::check_language_ub::runtime"]
def core.ub_checks.check_language_ub.runtime : Result Bool := do
  ok (¬ true)

/-- [core::ub_checks::check_language_ub]:
    Source: '/rustc/library/core/src/ub_checks.rs', lines 96:0-96:47
    Name pattern: [core::ub_checks::check_language_ub] -/
@[rust_fun "core::ub_checks::check_language_ub"]
def core.ub_checks.check_language_ub : Result Bool := do
  let b ← core.ub_checks.check_language_ub.runtime
  if b
  then ok false
  else ok false

/-- [core::num::{usize}::unchecked_add::precondition_check]:
    Source: '/rustc/library/core/src/ub_checks.rs', lines 68:12-68:55
    Name pattern: [core::num::{usize}::unchecked_add::precondition_check] -/
@[rust_fun "core::num::{usize}::unchecked_add::precondition_check"]
def core.num.Usize.unchecked_add.precondition_check
  (lhs : Std.Usize) (rhs : Std.Usize) : Result Unit := do
  let (_, b) ← lift (core.num.Usize.overflowing_add lhs rhs)
  massert (¬ b)

/-- [core::num::{usize}::unchecked_add]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 1031:8-1031:66
    Name pattern: [core::num::{usize}::unchecked_add]
    Visibility: public -/
@[rust_fun "core::num::{usize}::unchecked_add"]
def core.num.Usize.unchecked_add
  (self : Std.Usize) (rhs : Std.Usize) : Result Std.Usize := do
  let b ← core.ub_checks.check_language_ub
  if b
  then core.num.Usize.unchecked_add.precondition_check self rhs
  else ok ()
  self + rhs

/-- [core::num::{usize}::div_ceil]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3817:8-3817:54
    Name pattern: [core::num::{usize}::div_ceil]
    Visibility: public -/
@[rust_fun "core::num::{usize}::div_ceil"]
def core.num.Usize.div_ceil
  (self : Std.Usize) (rhs : Std.Usize) : Result Std.Usize := do
  let d ← self / rhs
  let r ← self % rhs
  if r > 0#usize
  then d + 1#usize
  else ok d

/-- [ruint::mask]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 384:0-384:37
    Name pattern: [ruint::mask]
    Visibility: public -/
@[rust_fun "ruint::mask"]
def ruint.mask (bits : Std.Usize) : Result Std.U64 := do
  if bits = 0#usize
  then ok 0#u64
  else
    let bits1 ← bits % 64#usize
    if bits1 = 0#usize
    then ok core.num.U64.MAX
    else let i ← 1#u64 <<< bits1
         i - 1#u64

/-- [ruint::{ruint::Uint<BITS, LIMBS>}::MASK]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 174:4-174:23
    Name pattern: [ruint::{ruint::Uint<@BITS, @LIMBS>}::MASK]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "ruint::{ruint::Uint<@BITS, @LIMBS>}::MASK"]
def ruint.Uint.MASK (BITS : Std.Usize) (LIMBS : Std.Usize) : Result Std.U64 :=
  ruint.mask BITS

/-- [ruint::{ruint::Uint<BITS, LIMBS>}::SHOULD_MASK]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 176:4-176:27
    Name pattern: [ruint::{ruint::Uint<@BITS, @LIMBS>}::SHOULD_MASK] -/
@[global_simps, irreducible, rust_const
  "ruint::{ruint::Uint<@BITS, @LIMBS>}::SHOULD_MASK"]
def ruint.Uint.SHOULD_MASK (BITS : Std.Usize) (LIMBS : Std.Usize)
  : Result Bool :=
  if BITS > 0#usize
  then do
       let i ← ruint.Uint.MASK BITS LIMBS
       ok (i != core.num.U64.MAX)
  else ok false

/-- [ruint::Uint]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 158:0-158:54
    Name pattern: [ruint::Uint]
    Visibility: public -/
@[rust_type "ruint::Uint"]
structure ruint.Uint (BITS : Std.Usize) (LIMBS : Std.Usize) where
  limbs : Array Std.U64 LIMBS

/-- [ruint::{ruint::Uint<BITS, LIMBS>}::apply_mask]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 344:4-344:34
    Name pattern: [ruint::{ruint::Uint<@BITS, @LIMBS>}::apply_mask] -/
@[rust_fun "ruint::{ruint::Uint<@BITS, @LIMBS>}::apply_mask"]
def ruint.Uint.apply_mask
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  let b ← ruint.Uint.SHOULD_MASK BITS LIMBS
  if b
  then
    let i ← LIMBS - 1#usize
    let i1 ← Array.index_usize self.limbs i
    let i2 ← ruint.Uint.MASK BITS LIMBS
    let i3 ← lift (i1 &&& i2)
    let a ← Array.update self.limbs i i3
    ok { limbs := a }
  else ok self

/-- [ruint::{ruint::Uint<BITS, LIMBS>}::masked]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 360:4-360:37
    Name pattern: [ruint::{ruint::Uint<@BITS, @LIMBS>}::masked] -/
@[rust_fun "ruint::{ruint::Uint<@BITS, @LIMBS>}::masked"]
def ruint.Uint.masked
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.apply_mask self

/-- [ruint::nlimbs]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 377:0-377:41
    Name pattern: [ruint::nlimbs]
    Visibility: public -/
@[rust_fun "ruint::nlimbs"]
def ruint.nlimbs (bits : Std.Usize) : Result Std.Usize := do
  core.num.Usize.div_ceil bits 64#usize

/-- [ruint::{ruint::Uint<BITS, LIMBS>}::LIMBS#1]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 164:4-164:26
    Name pattern: [ruint::{ruint::Uint<@BITS, @LIMBS>}::LIMBS#1]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "ruint::{ruint::Uint<@BITS, @LIMBS>}::LIMBS#1"]
def ruint.Uint.LIMBS_1 (BITS : Std.Usize) (LIMBS : Std.Usize)
  : Result Std.Usize := do
  let limbs ← ruint.nlimbs BITS
  massert (LIMBS = limbs)
  ok limbs

/-- [ruint::{ruint::Uint<BITS, LIMBS>}::from_limbs]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 243:4-243:56
    Name pattern: [ruint::{ruint::Uint<@BITS, @LIMBS>}::from_limbs]
    Visibility: public -/
@[rust_fun "ruint::{ruint::Uint<@BITS, @LIMBS>}::from_limbs"]
def ruint.Uint.from_limbs
  (BITS : Std.Usize) {LIMBS : Std.Usize} (limbs : Array Std.U64 LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  let b ← ruint.Uint.SHOULD_MASK BITS LIMBS
  if b
  then
    let i ← LIMBS - 1#usize
    let i1 ← Array.index_usize limbs i
    let i2 ← ruint.Uint.MASK BITS LIMBS
    massert (i1 <= i2)
    let _ ← ruint.Uint.LIMBS_1 BITS LIMBS
    ok { limbs }
  else let _ ← ruint.Uint.LIMBS_1 BITS LIMBS
       ok { limbs }

/-- [ruint::{ruint::Uint<BITS, LIMBS>}::ZERO]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 183:4-183:24
    Name pattern: [ruint::{ruint::Uint<@BITS, @LIMBS>}::ZERO]
    Visibility: public -/
@[global_simps, irreducible, rust_const
  "ruint::{ruint::Uint<@BITS, @LIMBS>}::ZERO"]
def ruint.Uint.ZERO (BITS : Std.Usize) (LIMBS : Std.Usize)
  : Result (ruint.Uint BITS LIMBS) :=
  let a := Array.repeat LIMBS 0#u64
  ruint.Uint.from_limbs BITS a

/-- [ruint::algorithms::add::carrying_add]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/algorithms/add.rs', lines 6:0-6:73
    Name pattern: [ruint::algorithms::add::carrying_add]
    Visibility: public -/
@[rust_fun "ruint::algorithms::add::carrying_add"]
def ruint.algorithms.add.carrying_add
  (lhs : Std.U64) (rhs : Std.U64) (carry : Bool) :
  Result (Std.U64 × Bool)
  := do
  let (result, carry_1) ← lift (core.num.U64.overflowing_add lhs rhs)
  let i ← lift (UScalar.cast_fromBool .U64 carry)
  let (result1, carry_2) ← lift (core.num.U64.overflowing_add result i)
  ok (result1, carry_1 || carry_2)

/-- [ruint::add::{ruint::Uint<BITS, LIMBS>}::overflowing_add]: loop body 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:14-118:51
    Name pattern: [ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_add]
    Visibility: public -/
@[rust_loop_body, rust_fun
  "ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_add"]
def ruint.add.Uint.overflowing_add_loop.body
  {BITS : Std.Usize} {LIMBS : Std.Usize} (rhs : ruint.Uint BITS LIMBS)
  (self : ruint.Uint BITS LIMBS) (carry : Bool) (iter : Std.Usize) :
  Result (ControlFlow ((ruint.Uint BITS LIMBS) × Bool × Std.Usize)
    ((ruint.Uint BITS LIMBS) × Bool))
  := do
  if iter < LIMBS
  then
    let iter1 ← core.num.Usize.unchecked_add iter 1#usize
    let i ← Array.index_usize self.limbs iter
    let i1 ← Array.index_usize rhs.limbs iter
    let (i2, carry1) ← ruint.algorithms.add.carrying_add i i1 carry
    let a ← Array.update self.limbs iter i2
    ok (cont ({ limbs := a }, carry1, iter1))
  else ok (done (self, carry))

/-- [ruint::add::{ruint::Uint<BITS, LIMBS>}::overflowing_add]: loop 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:14-118:51
    Name pattern: [ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_add]
    Visibility: public -/
@[rust_loop, rust_fun
  "ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_add"]
def ruint.add.Uint.overflowing_add_loop
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) (carry : Bool) (iter : Std.Usize) :
  Result ((ruint.Uint BITS LIMBS) × Bool)
  := do
  loop
    (fun (self1, carry1, iter1) => ruint.add.Uint.overflowing_add_loop.body rhs
      self1 carry1 iter1)
    (self, carry, iter)

/-- [ruint::add::{ruint::Uint<BITS, LIMBS>}::overflowing_add]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/add.rs', lines 109:4-109:69
    Name pattern: [ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_add]
    Visibility: public -/
@[rust_fun "ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_add"]
def ruint.add.Uint.overflowing_add
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result ((ruint.Uint BITS LIMBS) × Bool)
  := do
  if BITS = 0#usize
  then let u ← ruint.Uint.ZERO BITS LIMBS
       ok (u, false)
  else
    let (self1, carry) ←
      ruint.add.Uint.overflowing_add_loop self rhs false 0#usize
    let i ← LIMBS - 1#usize
    let i1 ← Array.index_usize self1.limbs i
    let i2 ← ruint.Uint.MASK BITS LIMBS
    let u ← ruint.Uint.masked self1
    ok (u, carry || (i1 > i2))

/-- [ruint::algorithms::add::borrowing_sub]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/algorithms/add.rs', lines 24:0-24:75
    Name pattern: [ruint::algorithms::add::borrowing_sub]
    Visibility: public -/
@[rust_fun "ruint::algorithms::add::borrowing_sub"]
def ruint.algorithms.add.borrowing_sub
  (lhs : Std.U64) (rhs : Std.U64) (borrow : Bool) :
  Result (Std.U64 × Bool)
  := do
  let (result, borrow_1) ← lift (core.num.U64.overflowing_sub lhs rhs)
  let i ← lift (UScalar.cast_fromBool .U64 borrow)
  let (result1, borrow_2) ← lift (core.num.U64.overflowing_sub result i)
  ok (result1, borrow_1 || borrow_2)

/-- [ruint::add::{ruint::Uint<BITS, LIMBS>}::overflowing_sub]: loop body 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:14-118:51
    Name pattern: [ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_sub]
    Visibility: public -/
@[rust_loop_body, rust_fun
  "ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_sub"]
def ruint.add.Uint.overflowing_sub_loop.body
  {BITS : Std.Usize} {LIMBS : Std.Usize} (rhs : ruint.Uint BITS LIMBS)
  (self : ruint.Uint BITS LIMBS) (borrow : Bool) (iter : Std.Usize) :
  Result (ControlFlow ((ruint.Uint BITS LIMBS) × Bool × Std.Usize)
    ((ruint.Uint BITS LIMBS) × Bool))
  := do
  if iter < LIMBS
  then
    let iter1 ← core.num.Usize.unchecked_add iter 1#usize
    let i ← Array.index_usize self.limbs iter
    let i1 ← Array.index_usize rhs.limbs iter
    let (i2, borrow1) ← ruint.algorithms.add.borrowing_sub i i1 borrow
    let a ← Array.update self.limbs iter i2
    ok (cont ({ limbs := a }, borrow1, iter1))
  else ok (done (self, borrow))

/-- [ruint::add::{ruint::Uint<BITS, LIMBS>}::overflowing_sub]: loop 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/macros.rs', lines 112:14-118:51
    Name pattern: [ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_sub]
    Visibility: public -/
@[rust_loop, rust_fun
  "ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_sub"]
def ruint.add.Uint.overflowing_sub_loop
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) (borrow : Bool) (iter : Std.Usize) :
  Result ((ruint.Uint BITS LIMBS) × Bool)
  := do
  loop
    (fun (self1, borrow1, iter1) => ruint.add.Uint.overflowing_sub_loop.body
      rhs self1 borrow1 iter1)
    (self, borrow, iter)

/-- [ruint::add::{ruint::Uint<BITS, LIMBS>}::overflowing_sub]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/add.rs', lines 140:4-140:69
    Name pattern: [ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_sub]
    Visibility: public -/
@[rust_fun "ruint::add::{ruint::Uint<@BITS, @LIMBS>}::overflowing_sub"]
def ruint.add.Uint.overflowing_sub
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result ((ruint.Uint BITS LIMBS) × Bool)
  := do
  if BITS = 0#usize
  then let u ← ruint.Uint.ZERO BITS LIMBS
       ok (u, false)
  else
    let (self1, borrow) ←
      ruint.add.Uint.overflowing_sub_loop self rhs false 0#usize
    let i ← LIMBS - 1#usize
    let i1 ← Array.index_usize self1.limbs i
    let i2 ← ruint.Uint.MASK BITS LIMBS
    let u ← ruint.Uint.masked self1
    ok (u, borrow || (i1 > i2))

/-- [ruint::add::{ruint::Uint<BITS, LIMBS>}::wrapping_add]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/add.rs', lines 177:4-177:54
    Name pattern: [ruint::add::{ruint::Uint<@BITS, @LIMBS>}::wrapping_add]
    Visibility: public -/
@[rust_fun "ruint::add::{ruint::Uint<@BITS, @LIMBS>}::wrapping_add"]
def ruint.add.Uint.wrapping_add
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  let (u, _) ← ruint.add.Uint.overflowing_add self rhs
  ok u

/-- [ruint::add::{ruint::Uint<BITS, LIMBS>}::wrapping_sub]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/add.rs', lines 191:4-191:54
    Name pattern: [ruint::add::{ruint::Uint<@BITS, @LIMBS>}::wrapping_sub]
    Visibility: public -/
@[rust_fun "ruint::add::{ruint::Uint<@BITS, @LIMBS>}::wrapping_sub"]
def ruint.add.Uint.wrapping_sub
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  let (u, _) ← ruint.add.Uint.overflowing_sub self rhs
  ok u

/-- [kasane_u256_extracted::add]:
    Source: 'lib.rs', lines 2:0-2:58
    Visibility: public -/
def add
  (a : ruint.Uint 256#usize 4#usize) (b : ruint.Uint 256#usize 4#usize) :
  Result (ruint.Uint 256#usize 4#usize)
  := do
  ruint.add.Uint.wrapping_add a b

/-- [kasane_u256_extracted::sub]:
    Source: 'lib.rs', lines 3:0-3:58
    Visibility: public -/
def sub
  (a : ruint.Uint 256#usize 4#usize) (b : ruint.Uint 256#usize 4#usize) :
  Result (ruint.Uint 256#usize 4#usize)
  := do
  ruint.add.Uint.wrapping_sub a b

end U256Extracted
