-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_ledger_timestamp_probe]: function definitions
import Aeneas
import LedgerPanicPayload.Types
import LedgerPanicPayload.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace LedgerPanicPayload

/-- [core::convert::num::{impl core::convert::TryFrom<u128, core::num::error::TryFromIntError> for u64}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 383:12-383:64
    Name pattern: [core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from"]
def U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from
  (u : Std.U128) :
  Result (core.result.Result Std.U64 core.num.error.TryFromIntError)
  := do
  let i ← lift (UScalar.cast .U128 core.num.U64.MAX)
  if u > i
  then ok (core.result.Result.Err core.num.error.IntErrorKind.PosOverflow)
  else let i1 ← lift (UScalar.cast .U64 u)
       ok (core.result.Result.Ok i1)

/-- Trait implementation: [core::fmt::{impl core::fmt::Display for &'_0 T}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2871:8-2871:46
    Name pattern: [core::fmt::Display<&'0 @T>] -/
@[reducible, rust_trait_impl "core::fmt::Display<&'0 @T>"]
def Shared0T.Insts.CoreFmtDisplay {T : Type} (DisplayInst : core.fmt.Display T)
  : core.fmt.Display T := {
  fmt := Shared0T.Insts.CoreFmtDisplay.fmt DisplayInst
}

/-- Trait implementation: [core::fmt::{impl core::fmt::Display for str}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2964:0-2964:20
    Name pattern: [core::fmt::Display<str>] -/
@[reducible, rust_trait_impl "core::fmt::Display<str>"]
def Str.Insts.CoreFmtDisplay : core.fmt.Display Str := {
  fmt := Str.Insts.CoreFmtDisplay.fmt
}

/-- Trait implementation: [core::num::error::{impl core::fmt::Debug for core::num::error::TryFromIntError}]
    Source: '/rustc/library/core/src/num/error.rs', lines 8:9-8:14
    Name pattern: [core::fmt::Debug<core::num::error::TryFromIntError>] -/
@[reducible, rust_trait_impl
  "core::fmt::Debug<core::num::error::TryFromIntError>"]
def core.num.error.TryFromIntError.Insts.CoreFmtDebug : core.fmt.Debug
  core.num.error.TryFromIntError := {
  fmt := core.num.error.TryFromIntError.Insts.CoreFmtDebug.fmt
}

/-- [core::num::niche_types::{core::num::niche_types::Nanoseconds}::new_unchecked]:
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 40:12-40:64
    Name pattern: [core::num::niche_types::{core::num::niche_types::Nanoseconds}::new_unchecked]
    Visibility: public -/
@[rust_fun
  "core::num::niche_types::{core::num::niche_types::Nanoseconds}::new_unchecked"]
def core.num.niche_types.Nanoseconds.new_unchecked
  (val : Std.U32) : Result core.num.niche_types.Nanoseconds := do
  (if rangeValid : (val).val ≤ 999999999 then Result.ok ⟨(val), Nat.zero_le _, rangeValid⟩ else Result.fail Error.undef)

/-- [core::num::niche_types::{core::num::niche_types::Nanoseconds}::as_inner]:
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 46:12-46:47
    Name pattern: [core::num::niche_types::{core::num::niche_types::Nanoseconds}::as_inner]
    Visibility: public -/
@[rust_fun
  "core::num::niche_types::{core::num::niche_types::Nanoseconds}::as_inner"]
def core.num.niche_types.Nanoseconds.as_inner
  (self : core.num.niche_types.Nanoseconds) : Result Std.U32 := do
  ok (self).val

/-- [core::result::unwrap_failed]:
    Source: '/rustc/library/core/src/result.rs', lines 1869:0-1869:56
    Name pattern: [core::result::unwrap_failed] -/
@[rust_fun "core::result::unwrap_failed"]
def core.result.unwrap_failed
  (msg : Str) (error : Dyn (fun _dyn => core.fmt.Debug _dyn)) :
  Result Never
  := do
  let a ←
    core.fmt.rt.Argument.new_display (Shared0T.Insts.CoreFmtDisplay
      Str.Insts.CoreFmtDisplay) msg
  let a1 ←
    core.fmt.rt.Argument.new_debug (core.fmt.DebugShared
      ({ fmt := (fun (d : Dyn (fun _dyn => core.fmt.Debug
      _dyn)) f => d.inst.fmt d.value f) })) error
  let a2 ←
    core.fmt.Arguments.new
      (Array.make 6#usize [ 192#u8, 2#u8, 58#u8, 32#u8, 192#u8, 0#u8 ])
      (Array.make 2#usize [ a, a1 ])
  let x ← core.panicking.panic_fmt a2
  nomatch x

/-- [core::result::{core::result::Result<T, E>}::unwrap]:
    Source: '/rustc/library/core/src/result.rs', lines 1226:4-1228:22
    Name pattern: [core::result::{core::result::Result<@T, @E>}::unwrap]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::unwrap"]
def core.result.Result.unwrap
  {T : Type} {E : Type} (fmtDebugInst : core.fmt.Debug E)
  (self : core.result.Result T E) :
  Result T
  := do
  match self with
  | core.result.Result.Ok t => ok t
  | core.result.Result.Err e =>
    let e1 := Dyn.mk _ fmtDebugInst e
    let x ←
      core.result.unwrap_failed
        (Slice.from [99#u8, 97#u8, 108#u8, 108#u8, 101#u8, 100#u8, 32#u8, 96#u8, 82#u8, 101#u8, 115#u8, 117#u8, 108#u8, 116#u8, 58#u8, 58#u8, 117#u8, 110#u8, 119#u8, 114#u8, 97#u8, 112#u8, 40#u8, 41#u8, 96#u8, 32#u8, 111#u8, 110#u8, 32#u8, 97#u8, 110#u8, 32#u8, 96#u8, 69#u8, 114#u8, 114#u8, 96#u8, 32#u8, 118#u8, 97#u8, 108#u8, 117#u8, 101#u8] (by scalar_tac))
        e1
    nomatch x

/-- [core::time::NANOS_PER_SEC]
    Source: '/rustc/library/core/src/time.rs', lines 27:0-27:24
    Name pattern: [core::time::NANOS_PER_SEC] -/
@[global_simps, irreducible, rust_const "core::time::NANOS_PER_SEC"]
def core.time.NANOS_PER_SEC : Std.U32 := 1000000000#u32

/-- [core::time::{core::time::Duration}::from_nanos::NANOS_PER_SEC]
    Source: '/rustc/library/core/src/time.rs', lines 302:8-302:32
    Name pattern: [core::time::{core::time::Duration}::from_nanos::NANOS_PER_SEC] -/
@[global_simps, irreducible, rust_const
  "core::time::{core::time::Duration}::from_nanos::NANOS_PER_SEC"]
def core.time.Duration.from_nanos.NANOS_PER_SEC : Result Std.U64 :=
  ok (UScalar.cast .U64 core.time.NANOS_PER_SEC)

/-- [core::time::{core::time::Duration}::from_nanos]:
    Source: '/rustc/library/core/src/time.rs', lines 301:4-301:51
    Name pattern: [core::time::{core::time::Duration}::from_nanos]
    Visibility: public -/
@[rust_fun "core::time::{core::time::Duration}::from_nanos"]
def core.time.Duration.from_nanos
  (nanos : Std.U64) : Result core.time.Duration := do
  let i ← core.time.Duration.from_nanos.NANOS_PER_SEC
  let secs ← nanos / i
  let i1 ← nanos % i
  let subsec_nanos ← lift (UScalar.cast .U32 i1)
  let subsec_nanos1 ←
    core.num.niche_types.Nanoseconds.new_unchecked subsec_nanos
  ok { secs, nanos := subsec_nanos1 }

/-- [core::time::{core::time::Duration}::as_nanos]:
    Source: '/rustc/library/core/src/time.rs', lines 639:4-639:40
    Name pattern: [core::time::{core::time::Duration}::as_nanos]
    Visibility: public -/
@[rust_fun "core::time::{core::time::Duration}::as_nanos"]
def core.time.Duration.as_nanos
  (self : core.time.Duration) : Result Std.U128 := do
  let i ← lift (UScalar.cast .U128 self.secs)
  let i1 ← lift (UScalar.cast .U128 core.time.NANOS_PER_SEC)
  let i2 ← i * i1
  let i3 ← core.num.niche_types.Nanoseconds.as_inner self.nanos
  let i4 ← lift (UScalar.cast .U128 i3)
  i2 + i4

/-- [kasane_ledger_timestamp_probe::timestamp::{impl core::ops::arith::Add<core::time::Duration, kasane_ledger_timestamp_probe::timestamp::TimeStamp> for kasane_ledger_timestamp_probe::timestamp::TimeStamp}::add]:
    Source: 'timestamp.rs', lines 68:4-74:5
    Visibility: public -/
def timestamp.TimeStamp.Insts.CoreOpsArithAddDurationTimeStamp.add
  (self : timestamp.TimeStamp) (d : core.time.Duration) :
  Result timestamp.TimeStamp
  := do
  let i ← core.time.Duration.as_nanos d
  let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i
  let i1 ←
    core.result.Result.unwrap core.num.error.TryFromIntError.Insts.CoreFmtDebug
      r
  let i2 ← lift (core.num.U64.saturating_add self.timestamp_nanos i1)
  ok { timestamp_nanos := i2 }

/-- [kasane_ledger_timestamp_probe::timestamp::{kasane_ledger_timestamp_probe::timestamp::TimeStamp}::from_nanos_since_unix_epoch]:
    Source: 'timestamp.rs', lines 41:4-45:5
    Visibility: public -/
def timestamp.TimeStamp.from_nanos_since_unix_epoch
  (nanos : Std.U64) : Result timestamp.TimeStamp := do
  ok { timestamp_nanos := nanos }

/-- [kasane_ledger_timestamp_probe::add_time]:
    Source: 'lib.rs', lines 4:0-6:1
    Visibility: public -/
def add_time
  (nanos : Std.U64) (duration : Std.U64) : Result timestamp.TimeStamp := do
  let ts ← timestamp.TimeStamp.from_nanos_since_unix_epoch nanos
  let d ← core.time.Duration.from_nanos duration
  timestamp.TimeStamp.Insts.CoreOpsArithAddDurationTimeStamp.add ts d

/-- [kasane_ledger_timestamp_probe::timestamp::{impl core::ops::arith::Sub<core::time::Duration, kasane_ledger_timestamp_probe::timestamp::TimeStamp> for kasane_ledger_timestamp_probe::timestamp::TimeStamp}::sub]:
    Source: 'timestamp.rs', lines 80:4-86:5
    Visibility: public -/
def timestamp.TimeStamp.Insts.CoreOpsArithSubDurationTimeStamp.sub
  (self : timestamp.TimeStamp) (d : core.time.Duration) :
  Result timestamp.TimeStamp
  := do
  let i ← core.time.Duration.as_nanos d
  let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i
  let i1 ←
    core.result.Result.unwrap core.num.error.TryFromIntError.Insts.CoreFmtDebug
      r
  let i2 ← lift (core.num.U64.saturating_sub self.timestamp_nanos i1)
  ok { timestamp_nanos := i2 }

/-- [kasane_ledger_timestamp_probe::sub_time]:
    Source: 'lib.rs', lines 7:0-9:1
    Visibility: public -/
def sub_time
  (nanos : Std.U64) (duration : Std.U64) : Result timestamp.TimeStamp := do
  let ts ← timestamp.TimeStamp.from_nanos_since_unix_epoch nanos
  let d ← core.time.Duration.from_nanos duration
  timestamp.TimeStamp.Insts.CoreOpsArithSubDurationTimeStamp.sub ts d

end LedgerPanicPayload
