-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_ledger_timestamp_probe]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace DurationRead

/-- [core::num::niche_types::Nanoseconds]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 20:8-20:55
    Name pattern: [core::num::niche_types::Nanoseconds]
    Visibility: public -/
@[reducible, rust_type "core::num::niche_types::Nanoseconds"]
def core.num.niche_types.Nanoseconds :=
  { rangeValue : Std.U32 // 0 ≤ rangeValue.val ∧ rangeValue.val ≤ 999999999 }

/-- [core::num::niche_types::{core::num::niche_types::Nanoseconds}::as_inner]:
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 46:12-46:47
    Name pattern: [core::num::niche_types::{core::num::niche_types::Nanoseconds}::as_inner]
    Visibility: public -/
@[rust_fun
  "core::num::niche_types::{core::num::niche_types::Nanoseconds}::as_inner"]
def core.num.niche_types.Nanoseconds.as_inner
  (self : core.num.niche_types.Nanoseconds) : Result Std.U32 := do
  ok (self).val

/-- [core::time::NANOS_PER_SEC]
    Source: '/rustc/library/core/src/time.rs', lines 27:0-27:24
    Name pattern: [core::time::NANOS_PER_SEC] -/
@[global_simps, irreducible, rust_const "core::time::NANOS_PER_SEC"]
def core.time.NANOS_PER_SEC : Std.U32 := 1000000000#u32

/-- [core::time::Duration]
    Source: '/rustc/library/core/src/time.rs', lines 81:0-81:19
    Name pattern: [core::time::Duration]
    Visibility: public -/
@[rust_type "core::time::Duration"]
structure core.time.Duration where
  secs : Std.U64
  nanos : core.num.niche_types.Nanoseconds

/-- [core::time::{core::time::Duration}::as_secs]:
    Source: '/rustc/library/core/src/time.rs', lines 514:4-514:38
    Name pattern: [core::time::{core::time::Duration}::as_secs]
    Visibility: public -/
@[rust_fun "core::time::{core::time::Duration}::as_secs"]
def core.time.Duration.as_secs
  (self : core.time.Duration) : Result Std.U64 := do
  ok self.secs

/-- [core::time::{core::time::Duration}::as_nanos]:
    Source: '/rustc/library/core/src/time.rs', lines 639:4-639:40
    Name pattern: [core::time::{core::time::Duration}::as_nanos]
    Visibility: public -/
@[rust_fun "core::time::{core::time::Duration}::as_nanos"]
def core.time.Duration.as_nanos
  (self : core.time.Duration) : Result Std.U128 := do
  let i ← lift (UScalar.cast .U128 self.secs)
  let i1 ← lift (UScalar.cast .U128 core.time.NANOS_PER_SEC)
  let i2 ← i * i1
  let i3 ← core.num.niche_types.Nanoseconds.as_inner self.nanos
  let i4 ← lift (UScalar.cast .U128 i3)
  i2 + i4

end DurationRead
