-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_bitwise_extracted]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace BitwiseOperators

/-- [core::ops::bit::{impl core::ops::bit::BitAndAssign<u64> for u64}::bitand_assign]:
    Source: '/rustc/library/core/src/ops/bit.rs', lines 748:12-748:50
    Name pattern: [core::ops::bit::{core::ops::bit::BitAndAssign<u64, u64>}::bitand_assign]
    Visibility: public -/
@[rust_fun
  "core::ops::bit::{core::ops::bit::BitAndAssign<u64, u64>}::bitand_assign"]
def U64.Insts.CoreOpsBitBitAndAssignU64.bitand_assign
  (self : Std.U64) (other : Std.U64) : Result Std.U64 := do
  ok (self &&& other)

/-- [core::ops::bit::{impl core::ops::bit::BitOrAssign<u64> for u64}::bitor_assign]:
    Source: '/rustc/library/core/src/ops/bit.rs', lines 823:12-823:49
    Name pattern: [core::ops::bit::{core::ops::bit::BitOrAssign<u64, u64>}::bitor_assign]
    Visibility: public -/
@[rust_fun
  "core::ops::bit::{core::ops::bit::BitOrAssign<u64, u64>}::bitor_assign"]
def U64.Insts.CoreOpsBitBitOrAssignU64.bitor_assign
  (self : Std.U64) (other : Std.U64) : Result Std.U64 := do
  ok (self ||| other)

/-- [core::ops::bit::{impl core::ops::bit::BitXorAssign<u64> for u64}::bitxor_assign]:
    Source: '/rustc/library/core/src/ops/bit.rs', lines 898:12-898:50
    Name pattern: [core::ops::bit::{core::ops::bit::BitXorAssign<u64, u64>}::bitxor_assign]
    Visibility: public -/
@[rust_fun
  "core::ops::bit::{core::ops::bit::BitXorAssign<u64, u64>}::bitxor_assign"]
def U64.Insts.CoreOpsBitBitXorAssignU64.bitxor_assign
  (self : Std.U64) (other : Std.U64) : Result Std.U64 := do
  ok (self ^^^ other)

/-- [ruint::Uint]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 158:0-158:54
    Name pattern: [ruint::Uint]
    Visibility: public -/
@[rust_type "ruint::Uint"]
structure ruint.Uint (BITS : Std.Usize) (LIMBS : Std.Usize) where
  limbs : Array Std.U64 LIMBS

/-- [ruint::bits::{impl core::ops::bit::BitAndAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitand_assign]: loop body 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 717:16-719:17
    Name pattern: [ruint::bits::{core::ops::bit::BitAndAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitand_assign]
    Visibility: public -/
@[rust_loop_body, rust_fun
  "ruint::bits::{core::ops::bit::BitAndAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitand_assign"]
def ruint.Uint.Insts.CoreOpsBitBitAndAssignShared0Uint.bitand_assign_loop.body
  {BITS : Std.Usize} {LIMBS : Std.Usize} (rhs : ruint.Uint BITS LIMBS)
  (iter : core.ops.range.Range Std.Usize) (self : ruint.Uint BITS LIMBS) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (ruint.Uint BITS
    LIMBS)) (ruint.Uint BITS LIMBS))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done self)
  | some i =>
    let (i1, index_mut_back) ← Array.index_mut_usize self.limbs i
    let i2 ← Array.index_usize rhs.limbs i
    let i3 ← U64.Insts.CoreOpsBitBitAndAssignU64.bitand_assign i1 i2
    let a := index_mut_back i3
    ok (cont (iter1, { limbs := a }))

/-- [ruint::bits::{impl core::ops::bit::BitAndAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitand_assign]: loop 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 717:16-719:17
    Name pattern: [ruint::bits::{core::ops::bit::BitAndAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitand_assign]
    Visibility: public -/
@[rust_loop, rust_fun
  "ruint::bits::{core::ops::bit::BitAndAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitand_assign"]
def ruint.Uint.Insts.CoreOpsBitBitAndAssignShared0Uint.bitand_assign_loop
  {BITS : Std.Usize} {LIMBS : Std.Usize}
  (iter : core.ops.range.Range Std.Usize) (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  loop
    (fun (iter1, self1) =>
      ruint.Uint.Insts.CoreOpsBitBitAndAssignShared0Uint.bitand_assign_loop.body
      rhs iter1 self1)
    (iter, self)

/-- [ruint::bits::{impl core::ops::bit::BitAndAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitand_assign]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 716:12-716:61
    Name pattern: [ruint::bits::{core::ops::bit::BitAndAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitand_assign]
    Visibility: public -/
@[reducible, rust_fun
  "ruint::bits::{core::ops::bit::BitAndAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitand_assign"]
def ruint.Uint.Insts.CoreOpsBitBitAndAssignShared0Uint.bitand_assign
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitAndAssignShared0Uint.bitand_assign_loop
    { start := 0#usize, «end» := LIMBS } self rhs

/-- [ruint::bits::{impl core::ops::bit::BitAndAssign<ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitand_assign]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 707:12-707:60
    Name pattern: [ruint::bits::{core::ops::bit::BitAndAssign<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitand_assign]
    Visibility: public -/
@[rust_fun
  "ruint::bits::{core::ops::bit::BitAndAssign<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitand_assign"]
def ruint.Uint.Insts.CoreOpsBitBitAndAssignUint.bitand_assign
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitAndAssignShared0Uint.bitand_assign self rhs

/-- [ruint::bits::{impl core::ops::bit::BitOrAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitor_assign]: loop body 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 717:16-719:17
    Name pattern: [ruint::bits::{core::ops::bit::BitOrAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitor_assign]
    Visibility: public -/
@[rust_loop_body, rust_fun
  "ruint::bits::{core::ops::bit::BitOrAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitor_assign"]
def ruint.Uint.Insts.CoreOpsBitBitOrAssignShared0Uint.bitor_assign_loop.body
  {BITS : Std.Usize} {LIMBS : Std.Usize} (rhs : ruint.Uint BITS LIMBS)
  (iter : core.ops.range.Range Std.Usize) (self : ruint.Uint BITS LIMBS) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (ruint.Uint BITS
    LIMBS)) (ruint.Uint BITS LIMBS))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done self)
  | some i =>
    let (i1, index_mut_back) ← Array.index_mut_usize self.limbs i
    let i2 ← Array.index_usize rhs.limbs i
    let i3 ← U64.Insts.CoreOpsBitBitOrAssignU64.bitor_assign i1 i2
    let a := index_mut_back i3
    ok (cont (iter1, { limbs := a }))

/-- [ruint::bits::{impl core::ops::bit::BitOrAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitor_assign]: loop 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 717:16-719:17
    Name pattern: [ruint::bits::{core::ops::bit::BitOrAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitor_assign]
    Visibility: public -/
@[rust_loop, rust_fun
  "ruint::bits::{core::ops::bit::BitOrAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitor_assign"]
def ruint.Uint.Insts.CoreOpsBitBitOrAssignShared0Uint.bitor_assign_loop
  {BITS : Std.Usize} {LIMBS : Std.Usize}
  (iter : core.ops.range.Range Std.Usize) (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  loop
    (fun (iter1, self1) =>
      ruint.Uint.Insts.CoreOpsBitBitOrAssignShared0Uint.bitor_assign_loop.body
      rhs iter1 self1)
    (iter, self)

/-- [ruint::bits::{impl core::ops::bit::BitOrAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitor_assign]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 716:12-716:61
    Name pattern: [ruint::bits::{core::ops::bit::BitOrAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitor_assign]
    Visibility: public -/
@[reducible, rust_fun
  "ruint::bits::{core::ops::bit::BitOrAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitor_assign"]
def ruint.Uint.Insts.CoreOpsBitBitOrAssignShared0Uint.bitor_assign
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitOrAssignShared0Uint.bitor_assign_loop
    { start := 0#usize, «end» := LIMBS } self rhs

/-- [ruint::bits::{impl core::ops::bit::BitOrAssign<ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitor_assign]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 707:12-707:60
    Name pattern: [ruint::bits::{core::ops::bit::BitOrAssign<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitor_assign]
    Visibility: public -/
@[rust_fun
  "ruint::bits::{core::ops::bit::BitOrAssign<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitor_assign"]
def ruint.Uint.Insts.CoreOpsBitBitOrAssignUint.bitor_assign
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitOrAssignShared0Uint.bitor_assign self rhs

/-- [ruint::bits::{impl core::ops::bit::BitXorAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitxor_assign]: loop body 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 717:16-719:17
    Name pattern: [ruint::bits::{core::ops::bit::BitXorAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitxor_assign]
    Visibility: public -/
@[rust_loop_body, rust_fun
  "ruint::bits::{core::ops::bit::BitXorAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitxor_assign"]
def ruint.Uint.Insts.CoreOpsBitBitXorAssignShared0Uint.bitxor_assign_loop.body
  {BITS : Std.Usize} {LIMBS : Std.Usize} (rhs : ruint.Uint BITS LIMBS)
  (iter : core.ops.range.Range Std.Usize) (self : ruint.Uint BITS LIMBS) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (ruint.Uint BITS
    LIMBS)) (ruint.Uint BITS LIMBS))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done self)
  | some i =>
    let (i1, index_mut_back) ← Array.index_mut_usize self.limbs i
    let i2 ← Array.index_usize rhs.limbs i
    let i3 ← U64.Insts.CoreOpsBitBitXorAssignU64.bitxor_assign i1 i2
    let a := index_mut_back i3
    ok (cont (iter1, { limbs := a }))

/-- [ruint::bits::{impl core::ops::bit::BitXorAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitxor_assign]: loop 0:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 717:16-719:17
    Name pattern: [ruint::bits::{core::ops::bit::BitXorAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitxor_assign]
    Visibility: public -/
@[rust_loop, rust_fun
  "ruint::bits::{core::ops::bit::BitXorAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitxor_assign"]
def ruint.Uint.Insts.CoreOpsBitBitXorAssignShared0Uint.bitxor_assign_loop
  {BITS : Std.Usize} {LIMBS : Std.Usize}
  (iter : core.ops.range.Range Std.Usize) (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  loop
    (fun (iter1, self1) =>
      ruint.Uint.Insts.CoreOpsBitBitXorAssignShared0Uint.bitxor_assign_loop.body
      rhs iter1 self1)
    (iter, self)

/-- [ruint::bits::{impl core::ops::bit::BitXorAssign<&'_0 ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitxor_assign]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 716:12-716:61
    Name pattern: [ruint::bits::{core::ops::bit::BitXorAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitxor_assign]
    Visibility: public -/
@[reducible, rust_fun
  "ruint::bits::{core::ops::bit::BitXorAssign<ruint::Uint<@BITS, @LIMBS>, &'0 ruint::Uint<@BITS, @LIMBS>>}::bitxor_assign"]
def ruint.Uint.Insts.CoreOpsBitBitXorAssignShared0Uint.bitxor_assign
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitXorAssignShared0Uint.bitxor_assign_loop
    { start := 0#usize, «end» := LIMBS } self rhs

/-- [ruint::bits::{impl core::ops::bit::BitXorAssign<ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitxor_assign]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 707:12-707:60
    Name pattern: [ruint::bits::{core::ops::bit::BitXorAssign<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitxor_assign]
    Visibility: public -/
@[rust_fun
  "ruint::bits::{core::ops::bit::BitXorAssign<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitxor_assign"]
def ruint.Uint.Insts.CoreOpsBitBitXorAssignUint.bitxor_assign
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitXorAssignShared0Uint.bitxor_assign self rhs

/-- [ruint::bits::{impl core::ops::bit::BitAnd<ruint::Uint<BITS, LIMBS>, ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitand]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 729:12-729:68
    Name pattern: [ruint::bits::{core::ops::bit::BitAnd<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitand]
    Visibility: public -/
@[rust_fun
  "ruint::bits::{core::ops::bit::BitAnd<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitand"]
def ruint.Uint.Insts.CoreOpsBitBitAndUintUint.bitand
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitAndAssignUint.bitand_assign self rhs

/-- [ruint::bits::{impl core::ops::bit::BitOr<ruint::Uint<BITS, LIMBS>, ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitor]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 729:12-729:68
    Name pattern: [ruint::bits::{core::ops::bit::BitOr<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitor]
    Visibility: public -/
@[rust_fun
  "ruint::bits::{core::ops::bit::BitOr<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitor"]
def ruint.Uint.Insts.CoreOpsBitBitOrUintUint.bitor
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitOrAssignUint.bitor_assign self rhs

/-- [ruint::bits::{impl core::ops::bit::BitXor<ruint::Uint<BITS, LIMBS>, ruint::Uint<BITS, LIMBS>> for ruint::Uint<BITS, LIMBS>}::bitxor]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/bits.rs', lines 729:12-729:68
    Name pattern: [ruint::bits::{core::ops::bit::BitXor<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitxor]
    Visibility: public -/
@[rust_fun
  "ruint::bits::{core::ops::bit::BitXor<ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>, ruint::Uint<@BITS, @LIMBS>>}::bitxor"]
def ruint.Uint.Insts.CoreOpsBitBitXorUintUint.bitxor
  {BITS : Std.Usize} {LIMBS : Std.Usize} (self : ruint.Uint BITS LIMBS)
  (rhs : ruint.Uint BITS LIMBS) :
  Result (ruint.Uint BITS LIMBS)
  := do
  ruint.Uint.Insts.CoreOpsBitBitXorAssignUint.bitxor_assign self rhs

/-- [kasane_bitwise_extracted::operator_and]:
    Source: 'lib.rs', lines 6:0-6:55
    Visibility: public -/
def operator_and
  (a : ruint.Uint 256#usize 4#usize) (b : ruint.Uint 256#usize 4#usize) :
  Result (ruint.Uint 256#usize 4#usize)
  := do
  ruint.Uint.Insts.CoreOpsBitBitAndUintUint.bitand a b

/-- [kasane_bitwise_extracted::operator_or]:
    Source: 'lib.rs', lines 7:0-7:54
    Visibility: public -/
def operator_or
  (a : ruint.Uint 256#usize 4#usize) (b : ruint.Uint 256#usize 4#usize) :
  Result (ruint.Uint 256#usize 4#usize)
  := do
  ruint.Uint.Insts.CoreOpsBitBitOrUintUint.bitor a b

/-- [kasane_bitwise_extracted::operator_xor]:
    Source: 'lib.rs', lines 8:0-8:55
    Visibility: public -/
def operator_xor
  (a : ruint.Uint 256#usize 4#usize) (b : ruint.Uint 256#usize 4#usize) :
  Result (ruint.Uint 256#usize 4#usize)
  := do
  ruint.Uint.Insts.CoreOpsBitBitXorUintUint.bitxor a b

end BitwiseOperators
