import ReleaseTimestampLocalLifetime
namespace ReleaseTimestampLocalLifetime
def addEvents : List Event :=
  [.live 3,
   .live 4,
   .copy 1 4,
   .live 5,
   .live 6,
   .live 7,
   .live 8,
   .borrow 2 8,
   .call [8] 7,
   .dead 8,
   .call [7] 6,
   .dead 7,
   .call [6] 5,
   .dead 6,
   .call [4, 5] 3,
   .dead 5,
   .dead 4,
   .move 3 0,
   .dead 3,
   .ret 0]
def subEvents : List Event :=
  [.live 3,
   .live 4,
   .copy 1 4,
   .live 5,
   .live 6,
   .live 7,
   .live 8,
   .borrow 2 8,
   .call [8] 7,
   .dead 8,
   .call [7] 6,
   .dead 7,
   .call [6] 5,
   .dead 6,
   .call [4, 5] 3,
   .dead 5,
   .dead 4,
   .move 3 0,
   .dead 3,
   .ret 0]
end ReleaseTimestampLocalLifetime
