-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [evm_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RevmStack

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3160:4-3160:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
def alloc.vec.Vec.is_empty
  {T : Type} (A : Type) (self : alloc.vec.Vec T) : Result Bool := do
  let i := alloc.vec.Vec.len self
  ok (i = 0#usize)

/-- [revm_interpreter::instruction_result::InstructionResult]
    Source: 'vendor/revm/crates/interpreter/src/instruction_result.rs', lines 14:0-14:26
    Name pattern: [revm_interpreter::instruction_result::InstructionResult]
    Visibility: public -/
@[discriminant u8 [1,2,3,16,17,18,19,20,21,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54],
  rust_type "revm_interpreter::instruction_result::InstructionResult"]
inductive revm_interpreter.instruction_result.InstructionResult where
| Stop : revm_interpreter.instruction_result.InstructionResult
| Return : revm_interpreter.instruction_result.InstructionResult
| SelfDestruct : revm_interpreter.instruction_result.InstructionResult
| Revert : revm_interpreter.instruction_result.InstructionResult
| CallTooDeep : revm_interpreter.instruction_result.InstructionResult
| OutOfFunds : revm_interpreter.instruction_result.InstructionResult
| CreateInitCodeStartingEF00 :
  revm_interpreter.instruction_result.InstructionResult
| InvalidEOFInitCode : revm_interpreter.instruction_result.InstructionResult
| InvalidExtDelegateCallTarget :
  revm_interpreter.instruction_result.InstructionResult
| OutOfGas : revm_interpreter.instruction_result.InstructionResult
| MemoryOOG : revm_interpreter.instruction_result.InstructionResult
| MemoryLimitOOG : revm_interpreter.instruction_result.InstructionResult
| PrecompileOOG : revm_interpreter.instruction_result.InstructionResult
| InvalidOperandOOG : revm_interpreter.instruction_result.InstructionResult
| ReentrancySentryOOG : revm_interpreter.instruction_result.InstructionResult
| OpcodeNotFound : revm_interpreter.instruction_result.InstructionResult
| CallNotAllowedInsideStatic :
  revm_interpreter.instruction_result.InstructionResult
| StateChangeDuringStaticCall :
  revm_interpreter.instruction_result.InstructionResult
| InvalidFEOpcode : revm_interpreter.instruction_result.InstructionResult
| InvalidJump : revm_interpreter.instruction_result.InstructionResult
| NotActivated : revm_interpreter.instruction_result.InstructionResult
| StackUnderflow : revm_interpreter.instruction_result.InstructionResult
| StackOverflow : revm_interpreter.instruction_result.InstructionResult
| OutOfOffset : revm_interpreter.instruction_result.InstructionResult
| CreateCollision : revm_interpreter.instruction_result.InstructionResult
| OverflowPayment : revm_interpreter.instruction_result.InstructionResult
| PrecompileError : revm_interpreter.instruction_result.InstructionResult
| NonceOverflow : revm_interpreter.instruction_result.InstructionResult
| CreateContractSizeLimit :
  revm_interpreter.instruction_result.InstructionResult
| CreateContractStartingWithEF :
  revm_interpreter.instruction_result.InstructionResult
| CreateInitCodeSizeLimit :
  revm_interpreter.instruction_result.InstructionResult
| FatalExternalError : revm_interpreter.instruction_result.InstructionResult

/-- [ruint::Uint]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ruint-1.20.0/src/lib.rs', lines 158:0-158:54
    Name pattern: [ruint::Uint]
    Visibility: public -/
@[rust_type "ruint::Uint"]
structure ruint.Uint (BITS : Std.Usize) (LIMBS : Std.Usize) where
  limbs : Array Std.U64 LIMBS

/-- [revm_interpreter::interpreter::stack::Stack]
    Source: 'vendor/revm/crates/interpreter/src/interpreter/stack.rs', lines 14:0-14:16
    Name pattern: [revm_interpreter::interpreter::stack::Stack]
    Visibility: public -/
@[rust_type "revm_interpreter::interpreter::stack::Stack"]
structure revm_interpreter.interpreter.stack.Stack where
  data : alloc.vec.Vec (ruint.Uint 256#usize 4#usize)

/-- [revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::len]:
    Source: 'vendor/revm/crates/interpreter/src/interpreter/stack.rs', lines 123:4-123:30
    Name pattern: [revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::len]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::len"]
def revm_interpreter.interpreter.stack.Stack.len
  (self : revm_interpreter.interpreter.stack.Stack) : Result Std.Usize := do
  ok (alloc.vec.Vec.len self.data)

/-- [revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::is_empty]:
    Source: 'vendor/revm/crates/interpreter/src/interpreter/stack.rs', lines 129:4-129:34
    Name pattern: [revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::is_empty]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::is_empty"]
def revm_interpreter.interpreter.stack.Stack.is_empty
  (self : revm_interpreter.interpreter.stack.Stack) : Result Bool := do
  alloc.vec.Vec.is_empty Global self.data

/-- [revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::peek]:
    Source: 'vendor/revm/crates/interpreter/src/interpreter/stack.rs', lines 243:4-243:77
    Name pattern: [revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::peek]
    Visibility: public -/
@[rust_fun
  "revm_interpreter::interpreter::stack::{revm_interpreter::interpreter::stack::Stack}::peek"]
def revm_interpreter.interpreter.stack.Stack.peek
  (self : revm_interpreter.interpreter.stack.Stack) (no_from_top : Std.Usize) :
  Result (core.result.Result (ruint.Uint 256#usize 4#usize)
    revm_interpreter.instruction_result.InstructionResult)
  := do
  let i := alloc.vec.Vec.len self.data
  if i > no_from_top
  then
    let i1 := alloc.vec.Vec.len self.data
    let i2 ← i1 - no_from_top
    let i3 ← i2 - 1#usize
    let u ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (ruint.Uint
        256#usize 4#usize)) self.data i3
    ok (core.result.Result.Ok u)
  else
    ok (core.result.Result.Err
      revm_interpreter.instruction_result.InstructionResult.StackUnderflow)

end RevmStack
