-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [charon_lib]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace CharonTypeInfo

/-- [charon_lib::ast::type_level::type_info::_::InternalBitFlags]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/internal.rs', lines 20:8-20:42
    Visibility: public -/
@[reducible]
def ast.type_level.type_info._.InternalBitFlags := Std.U8

/-- [charon_lib::ast::type_level::type_info::_::{charon_lib::ast::type_level::type_info::_::InternalBitFlags}::bits]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/lib.rs', lines 650:12-653:13
    Visibility: public -/
def ast.type_level.type_info._.InternalBitFlags.bits
  (self : ast.type_level.type_info._.InternalBitFlags) : Result Std.U8 := do
  ok self

/-- [charon_lib::ast::type_level::type_info::TypeFlags]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/public.rs', lines 17:8-17:99
    Visibility: public -/
@[reducible]
def ast.type_level.type_info.TypeFlags :=
  ast.type_level.type_info._.InternalBitFlags

/-- [charon_lib::ast::type_level::type_info::_::{charon_lib::ast::type_level::type_info::_::InternalBitFlags}::from_bits_retain]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/lib.rs', lines 673:12-676:13
    Visibility: public -/
def ast.type_level.type_info._.InternalBitFlags.from_bits_retain
  (bits : Std.U8) : Result ast.type_level.type_info._.InternalBitFlags := do
  ok bits

/-- [charon_lib::ast::type_level::type_info::_::{charon_lib::ast::type_level::type_info::TypeFlags}::from_bits_retain]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/lib.rs', lines 673:12-676:13
    Visibility: public -/
def ast.type_level.type_info._.TypeFlags.from_bits_retain
  (bits : Std.U8) : Result ast.type_level.type_info.TypeFlags := do
  let ibf ← ast.type_level.type_info._.InternalBitFlags.from_bits_retain bits
  ok ibf

/-- [charon_lib::ast::type_level::type_info::_::{charon_lib::ast::type_level::type_info::_::InternalBitFlags}::contains]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/lib.rs', lines 712:12-716:13
    Visibility: public -/
def ast.type_level.type_info._.InternalBitFlags.contains
  (self : ast.type_level.type_info._.InternalBitFlags)
  (other : ast.type_level.type_info._.InternalBitFlags) :
  Result Bool
  := do
  let i ← ast.type_level.type_info._.InternalBitFlags.bits self
  let i1 ← ast.type_level.type_info._.InternalBitFlags.bits other
  let i2 ← lift (i &&& i1)
  ok (i2 = i1)

/-- [charon_lib::ast::type_level::type_info::_::{charon_lib::ast::type_level::type_info::TypeFlags}::contains]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/lib.rs', lines 712:12-716:13
    Visibility: public -/
def ast.type_level.type_info._.TypeFlags.contains
  (self : ast.type_level.type_info.TypeFlags)
  (other : ast.type_level.type_info.TypeFlags) :
  Result Bool
  := do
  ast.type_level.type_info._.InternalBitFlags.contains self other

/-- [charon_lib::ast::type_level::type_info::{charon_lib::ast::type_level::type_info::TypeFlags}::MENTIONS_FREE_VAR]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/public.rs', lines 526:24-526:79
    Visibility: public -/
@[global_simps, irreducible]
def ast.type_level.type_info.TypeFlags.MENTIONS_FREE_VAR
  : Result ast.type_level.type_info.TypeFlags := do
  let i ← 1#u8 <<< 4#i32
  ast.type_level.type_info._.TypeFlags.from_bits_retain i

/-- [charon_lib::ast::type_level::type_info::{charon_lib::ast::type_level::type_info::TypeFlags}::MENTIONS_SELF_CLAUSE]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/public.rs', lines 526:24-526:79
    Visibility: public -/
@[global_simps, irreducible]
def ast.type_level.type_info.TypeFlags.MENTIONS_SELF_CLAUSE
  : Result ast.type_level.type_info.TypeFlags := do
  let i ← 1#u8 <<< 1#i32
  ast.type_level.type_info._.TypeFlags.from_bits_retain i

/-- [charon_lib::ast::type_level::type_info::{charon_lib::ast::type_level::type_info::TypeFlags}::USES_SIZE_METADATA]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitflags-2.9.1/src/public.rs', lines 526:24-526:79
    Visibility: public -/
@[global_simps, irreducible]
def ast.type_level.type_info.TypeFlags.USES_SIZE_METADATA
  : Result ast.type_level.type_info.TypeFlags := do
  let i ← 1#u8 <<< 2#i32
  ast.type_level.type_info._.TypeFlags.from_bits_retain i

/-- [charon_lib::ast::type_level::vars::DeBruijnId]
    Source: 'src/ast/type_level/vars.rs', lines 21:0-23:1
    Visibility: public -/
structure ast.type_level.vars.DeBruijnId where
  index : Std.Usize

/-- [charon_lib::ast::type_level::type_info::TypeInfo]
    Source: 'src/ast/type_level/type_info.rs', lines 21:0-24:1
    Visibility: public -/
structure ast.type_level.type_info.TypeInfo where
  max_de_bruijn_id : Option ast.type_level.vars.DeBruijnId
  flags : ast.type_level.type_info.TypeFlags

/-- [charon_lib::ast::type_level::type_info::{charon_lib::ast::type_level::type_info::TypeInfo}::mentions_var]:
    Source: 'src/ast/type_level/type_info.rs', lines 192:4-194:5
    Visibility: public -/
def ast.type_level.type_info.TypeInfo.mentions_var
  (self : ast.type_level.type_info.TypeInfo) : Result Bool := do
  let b := core.option.Option.is_some self.max_de_bruijn_id
  if b
  then ok true
  else
    let tf ← ast.type_level.type_info.TypeFlags.MENTIONS_FREE_VAR
    ast.type_level.type_info._.TypeFlags.contains self.flags tf

/-- [charon_lib::ast::type_level::type_info::{charon_lib::ast::type_level::type_info::TypeInfo}::mentions_self_clause]:
    Source: 'src/ast/type_level/type_info.rs', lines 197:4-199:5
    Visibility: public -/
def ast.type_level.type_info.TypeInfo.mentions_self_clause
  (self : ast.type_level.type_info.TypeInfo) : Result Bool := do
  let tf ← ast.type_level.type_info.TypeFlags.MENTIONS_SELF_CLAUSE
  ast.type_level.type_info._.TypeFlags.contains self.flags tf

/-- [charon_lib::ast::type_level::type_info::{charon_lib::ast::type_level::type_info::TypeInfo}::uses_size_metadata]:
    Source: 'src/ast/type_level/type_info.rs', lines 202:4-204:5
    Visibility: public -/
def ast.type_level.type_info.TypeInfo.uses_size_metadata
  (self : ast.type_level.type_info.TypeInfo) : Result Bool := do
  let tf ← ast.type_level.type_info.TypeFlags.USES_SIZE_METADATA
  ast.type_level.type_info._.TypeFlags.contains self.flags tf

/-- [charon_lib::ast::type_level::type_info::{charon_lib::ast::type_level::type_info::TypeInfo}::is_closed]:
    Source: 'src/ast/type_level/type_info.rs', lines 207:4-209:5
    Visibility: public -/
def ast.type_level.type_info.TypeInfo.is_closed
  (self : ast.type_level.type_info.TypeInfo) : Result Bool := do
  let b ← ast.type_level.type_info.TypeInfo.mentions_var self
  if b
  then ok false
  else
    let b1 ← ast.type_level.type_info.TypeInfo.mentions_self_clause self
    if b1
    then ok false
    else
      let b2 ← ast.type_level.type_info.TypeInfo.uses_size_metadata self
      ok (¬ b2)

end CharonTypeInfo
