/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TxsRouteImport } from './routes/txs'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AddressHexRouteImport } from './routes/address.$hex'
import { Route as BlocksNumberRouteImport } from './routes/blocks_.$number'
import { Route as PrincipalTextRouteImport } from './routes/principal.$text'
import { Route as TxHashRouteImport } from './routes/tx.$hash'
import { Route as ApiOpsVerifyRouteImport } from './routes/api.ops.verify'
import { Route as ApiVerifyStatusRouteImport } from './routes/api.verify.status'
import { Route as ApiVerifySubmitRouteImport } from './routes/api.verify.submit'
import { Route as ApiContractsAddressVerifiedRouteImport } from './routes/api.contracts.$address.verified'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TxsRoute = TxsRouteImport.update({
  id: '/txs',
  path: '/txs',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressHexRoute = AddressHexRouteImport.update({
  id: '/address/$hex',
  path: '/address/$hex',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksNumberRoute = BlocksNumberRouteImport.update({
  id: '/blocks_/$number',
  path: '/blocks/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalTextRoute = PrincipalTextRouteImport.update({
  id: '/principal/$text',
  path: '/principal/$text',
  getParentRoute: () => rootRouteImport,
} as any)
const TxHashRoute = TxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsVerifyRoute = ApiOpsVerifyRouteImport.update({
  id: '/api/ops/verify',
  path: '/api/ops/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyStatusRoute = ApiVerifyStatusRouteImport.update({
  id: '/api/verify/status',
  path: '/api/verify/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifySubmitRoute = ApiVerifySubmitRouteImport.update({
  id: '/api/verify/submit',
  path: '/api/verify/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContractsAddressVerifiedRoute =
  ApiContractsAddressVerifiedRouteImport.update({
    id: '/api/contracts/$address/verified',
    path: '/api/contracts/$address/verified',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/logs': typeof LogsRoute
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/txs': typeof TxsRoute
  '/verify': typeof VerifyRoute
  '/address/$hex': typeof AddressHexRoute
  '/blocks/$number': typeof BlocksNumberRoute
  '/principal/$text': typeof PrincipalTextRoute
  '/tx/$hash': typeof TxHashRoute
  '/api/ops/verify': typeof ApiOpsVerifyRoute
  '/api/verify/status': typeof ApiVerifyStatusRoute
  '/api/verify/submit': typeof ApiVerifySubmitRoute
  '/api/contracts/$address/verified': typeof ApiContractsAddressVerifiedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/logs': typeof LogsRoute
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/txs': typeof TxsRoute
  '/verify': typeof VerifyRoute
  '/address/$hex': typeof AddressHexRoute
  '/blocks/$number': typeof BlocksNumberRoute
  '/principal/$text': typeof PrincipalTextRoute
  '/tx/$hash': typeof TxHashRoute
  '/api/ops/verify': typeof ApiOpsVerifyRoute
  '/api/verify/status': typeof ApiVerifyStatusRoute
  '/api/verify/submit': typeof ApiVerifySubmitRoute
  '/api/contracts/$address/verified': typeof ApiContractsAddressVerifiedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/logs': typeof LogsRoute
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/txs': typeof TxsRoute
  '/verify': typeof VerifyRoute
  '/address/$hex': typeof AddressHexRoute
  '/blocks_/$number': typeof BlocksNumberRoute
  '/principal/$text': typeof PrincipalTextRoute
  '/tx/$hash': typeof TxHashRoute
  '/api/ops/verify': typeof ApiOpsVerifyRoute
  '/api/verify/status': typeof ApiVerifyStatusRoute
  '/api/verify/submit': typeof ApiVerifySubmitRoute
  '/api/contracts/$address/verified': typeof ApiContractsAddressVerifiedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/logs'
    | '/ops'
    | '/search'
    | '/txs'
    | '/verify'
    | '/address/$hex'
    | '/blocks/$number'
    | '/principal/$text'
    | '/tx/$hash'
    | '/api/ops/verify'
    | '/api/verify/status'
    | '/api/verify/submit'
    | '/api/contracts/$address/verified'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/logs'
    | '/ops'
    | '/search'
    | '/txs'
    | '/verify'
    | '/address/$hex'
    | '/blocks/$number'
    | '/principal/$text'
    | '/tx/$hash'
    | '/api/ops/verify'
    | '/api/verify/status'
    | '/api/verify/submit'
    | '/api/contracts/$address/verified'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/logs'
    | '/ops'
    | '/search'
    | '/txs'
    | '/verify'
    | '/address/$hex'
    | '/blocks_/$number'
    | '/principal/$text'
    | '/tx/$hash'
    | '/api/ops/verify'
    | '/api/verify/status'
    | '/api/verify/submit'
    | '/api/contracts/$address/verified'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  LogsRoute: typeof LogsRoute
  OpsRoute: typeof OpsRoute
  SearchRoute: typeof SearchRoute
  TxsRoute: typeof TxsRoute
  VerifyRoute: typeof VerifyRoute
  AddressHexRoute: typeof AddressHexRoute
  BlocksNumberRoute: typeof BlocksNumberRoute
  PrincipalTextRoute: typeof PrincipalTextRoute
  TxHashRoute: typeof TxHashRoute
  ApiOpsVerifyRoute: typeof ApiOpsVerifyRoute
  ApiVerifyStatusRoute: typeof ApiVerifyStatusRoute
  ApiVerifySubmitRoute: typeof ApiVerifySubmitRoute
  ApiContractsAddressVerifiedRoute: typeof ApiContractsAddressVerifiedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/txs': {
      id: '/txs'
      path: '/txs'
      fullPath: '/txs'
      preLoaderRoute: typeof TxsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$hex': {
      id: '/address/$hex'
      path: '/address/$hex'
      fullPath: '/address/$hex'
      preLoaderRoute: typeof AddressHexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks_/$number': {
      id: '/blocks_/$number'
      path: '/blocks/$number'
      fullPath: '/blocks/$number'
      preLoaderRoute: typeof BlocksNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/$text': {
      id: '/principal/$text'
      path: '/principal/$text'
      fullPath: '/principal/$text'
      preLoaderRoute: typeof PrincipalTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tx/$hash': {
      id: '/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof TxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/verify': {
      id: '/api/ops/verify'
      path: '/api/ops/verify'
      fullPath: '/api/ops/verify'
      preLoaderRoute: typeof ApiOpsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify/status': {
      id: '/api/verify/status'
      path: '/api/verify/status'
      fullPath: '/api/verify/status'
      preLoaderRoute: typeof ApiVerifyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify/submit': {
      id: '/api/verify/submit'
      path: '/api/verify/submit'
      fullPath: '/api/verify/submit'
      preLoaderRoute: typeof ApiVerifySubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contracts/$address/verified': {
      id: '/api/contracts/$address/verified'
      path: '/api/contracts/$address/verified'
      fullPath: '/api/contracts/$address/verified'
      preLoaderRoute: typeof ApiContractsAddressVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  LogsRoute: LogsRoute,
  OpsRoute: OpsRoute,
  SearchRoute: SearchRoute,
  TxsRoute: TxsRoute,
  VerifyRoute: VerifyRoute,
  AddressHexRoute: AddressHexRoute,
  BlocksNumberRoute: BlocksNumberRoute,
  PrincipalTextRoute: PrincipalTextRoute,
  TxHashRoute: TxHashRoute,
  ApiOpsVerifyRoute: ApiOpsVerifyRoute,
  ApiVerifyStatusRoute: ApiVerifyStatusRoute,
  ApiVerifySubmitRoute: ApiVerifySubmitRoute,
  ApiContractsAddressVerifiedRoute: ApiContractsAddressVerifiedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
