-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kasane_ledger_timestamp_probe]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace LedgerActualUnwrap

/-- [core::num::error::IntErrorKind]
    Source: '/rustc/library/core/src/num/error.rs', lines 88:0-88:21
    Name pattern: [core::num::error::IntErrorKind]
    Visibility: public -/
@[discriminant isize, rust_type "core::num::error::IntErrorKind"]
inductive core.num.error.IntErrorKind where
| Empty : core.num.error.IntErrorKind
| InvalidDigit : core.num.error.IntErrorKind
| PosOverflow : core.num.error.IntErrorKind
| NegOverflow : core.num.error.IntErrorKind
| Zero : core.num.error.IntErrorKind
| NotAPowerOfTwo : core.num.error.IntErrorKind

/-- [core::num::error::TryFromIntError]
    Source: '/rustc/library/core/src/num/error.rs', lines 9:0-9:26
    Name pattern: [core::num::error::TryFromIntError]
    Visibility: public -/
@[reducible, rust_type "core::num::error::TryFromIntError"]
def core.num.error.TryFromIntError := core.num.error.IntErrorKind

/-- [core::num::niche_types::Nanoseconds]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 20:8-20:55
    Name pattern: [core::num::niche_types::Nanoseconds]
    Visibility: public -/
@[reducible, rust_type "core::num::niche_types::Nanoseconds"]
def core.num.niche_types.Nanoseconds :=
  { rangeValue : Std.U32 // 0 ≤ rangeValue.val ∧ rangeValue.val ≤ 999999999 }

/-- [core::time::Duration]
    Source: '/rustc/library/core/src/time.rs', lines 81:0-81:19
    Name pattern: [core::time::Duration]
    Visibility: public -/
@[rust_type "core::time::Duration"]
structure core.time.Duration where
  secs : Std.U64
  nanos : core.num.niche_types.Nanoseconds

/-- [kasane_ledger_timestamp_probe::timestamp::TimeStamp]
    Source: 'timestamp.rs', lines 28:0-31:1
    Visibility: public -/
structure timestamp.TimeStamp where
  timestamp_nanos : Std.U64

end LedgerActualUnwrap
