#!/usr/bin/env bash
# Actual source extraction diagnostic; generated Cell axioms are not accepted proofs.
set -euo pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}/.."
export DYLD_LIBRARY_PATH="$PWD/.local/proof-tools/aeneas/libs${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
export RUSTUP_TOOLCHAIN=nightly-2026-09-17
export CARGO_TARGET_DIR="$PWD/.local/proof-tools/revm-root-target"
python3 - <<'RUN'
import hashlib,json,pathlib,subprocess,tempfile,sys
sys.path.insert(0,'scripts')
from audit_std_borrow_ref_new_llbc import inspect,negative_controls
root=pathlib.Path.cwd(); profile=json.load(open('proofs/extraction/tool-patches/std-borrow-ref-new-profile.json'))
for mapping in [profile['sha256'],profile['base_source_sha256']]:
 for f,h in mapping.items(): assert hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest()==h,f
with tempfile.TemporaryDirectory(prefix='kasane-std-borrow-ref-new-') as tmp:
 tmp=pathlib.Path(tmp)
 for label,transparent in [('opaque_cell',False),('transparent_cell',True)]:
  dest=tmp/(label+'.llbc'); out=tmp/label;out.mkdir()
  args=['.local/proof-tools/charon-gat-candidate/charon','cargo','--preset=aeneas','--mir','promoted','--error-on-warnings','--start-from','core::cell::BorrowRef::new','--include','core::cell::_::new','--include','core::cell::BorrowRef','--include','core::cell::is_reading','--include','core::cell::UNUSED']
  if transparent:
   for name in ['core::cell::_::get','core::cell::_::replace','core::cell::Cell','core::cell::UnsafeCell']: args+=['--include',name]
  args+=['--dest-file',str(dest),'--','--manifest-path','crates/evm-core/Cargo.toml','--lib','--locked']
  r=subprocess.run(args,capture_output=True,text=True,timeout=180);assert r.returncode==0,r.stdout+r.stderr
  data=json.loads(dest.read_text());assert inspect(data,transparent)==profile['observations'][label];negative_controls(data,transparent)
  tool='.local/proof-tools/aeneas-gat-source/aeneas'
  for mode,args in [('borrow',['-borrow-check']),('lean',['-backend','lean','-dest',str(out),'-namespace','StdBorrowRefNew','-use-lean-modules','false'])]:
   r=subprocess.run([tool]+args+['-abort-on-error','-warnings-as-errors',str(dest)],capture_output=True,text=True,timeout=180)
   if transparent:
    assert r.returncode!=0 and 'Aeneas does not yet support dereferencing raw pointers.' in r.stdout+r.stderr,r.stdout+r.stderr
    assert not list(out.rglob('*.lean')),'Unaccepted partial Lean output'
    print(label+' '+mode+' rejects actual raw-pointer dereference')
   else:
    assert r.returncode==0,r.stdout+r.stderr
    print(label+' '+mode+' passed with Cell operations remaining unproved')
  if not transparent:
   assert len(list(out.rglob('*.lean')))==1
   source=(out/'OpaqueCell.lean').read_text()
   assert source==(root/'proofs/extraction/quarantine/std-borrow-ref-new/New.lean').read_text(),'Quarantined generated bytes changed'
   # First compile the unchanged generator output. Then reject its unresolved axioms.
   lean_root=root/'proofs/extraction/u256-lean'
   with tempfile.TemporaryDirectory(prefix='borrow-ref-axiom-',dir=lean_root/'.lake') as lean_tmp:
    f=pathlib.Path(lean_tmp)/'Probe.lean';f.write_text(source)
    r=subprocess.run(['lake','env','lean','-DwarningAsError=true',str(f)],cwd=lean_root,capture_output=True,text=True,timeout=180)
    assert r.returncode==0,r.stdout+r.stderr
    audit='''\nopen Lean in
run_cmd do
  let axioms ← collectAxioms `StdBorrowRefNew.core.cell.BorrowRef.new
  let expected := #[`StdBorrowRefNew.core.cell.Cell, `StdBorrowRefNew.core.cell.Cell.get, `StdBorrowRefNew.core.cell.Cell.replace]
  for axiomName in expected do
    unless axioms.contains axiomName do
      throwError "Missing expected unresolved Cell axiom {axiomName}"
  for axiomName in axioms do
    unless (expected ++ #[`propext, `Quot.sound, `Classical.choice]).contains axiomName do
      throwError "Unexpected unresolved axiom {axiomName}"
  throwError "Actual generated BorrowRef.new depends on unproved Cell type/get/replace axioms"
'''
    f.write_text('import Lean\n'+source+audit)
    r=subprocess.run(['lake','env','lean',str(f)],cwd=lean_root,capture_output=True,text=True,timeout=180)
    assert r.returncode!=0 and 'Actual generated BorrowRef.new depends on unproved Cell type/get/replace axioms' in r.stdout+r.stderr,r.stdout+r.stderr
    print('Unchanged opaque generator output compiles; three unresolved Cell axioms explicitly rejected by audit')
print('Fresh actual std BorrowRef/Cell source diagnostic and twelve modified-witness rejections passed; no heap/refinement theorem accepted.')
RUN
