#!/usr/bin/env bash
# where: playground-only manual build/deploy helper
# what: build wasm with cargo (no dfx build) and install via icp-cli
# why: keep wasm small and reproducible; avoid dfx-internal build/strip issues
# note: this is intended for playground use only (size issues); not needed for mainnet deploys
set -euo pipefail
source "$(dirname "$0")/lib_init_args.sh"

NETWORK="${NETWORK:-playground}"
CANISTER_NAME="${CANISTER_NAME:-evm_canister}"
CANISTER_ID="${CANISTER_ID:-}"
MODE="${MODE:-reinstall}"
RUN_SMOKE="${RUN_SMOKE:-0}"
FUNDED_ETH_PRIVKEY="${FUNDED_ETH_PRIVKEY:-}"
FUNDED_ETH_AMOUNT="${FUNDED_ETH_AMOUNT:-1000000000000000000}"
AUTO_GENERATE_FUNDED_ETH_PRIVKEY="${AUTO_GENERATE_FUNDED_ETH_PRIVKEY:-1}"
WRITE_SMOKE_ENV="${WRITE_SMOKE_ENV:-1}"
SMOKE_ENV_FILE="${SMOKE_ENV_FILE:-${REPO_ROOT}/scripts/.playground_smoke.env}"

log() {
  echo "[manual-deploy] $*"
}

build_wasm() {
  log "cargo build --release --target wasm32-unknown-unknown -p ic-evm-wrapper"
  cargo build --release --target wasm32-unknown-unknown -p ic-evm-wrapper
}

ensure_funded_eth_privkey() {
  if [[ -n "${FUNDED_ETH_PRIVKEY}" ]]; then
    return
  fi
  if [[ "${AUTO_GENERATE_FUNDED_ETH_PRIVKEY}" != "1" ]]; then
    return
  fi
  log "generating FUNDED_ETH_PRIVKEY for genesis-funded eth smoke path"
  FUNDED_ETH_PRIVKEY=$(cargo run -q -p ic-evm-core --features local-signer-bin --bin eth_raw_tx -- --mode genkey)
}

write_smoke_env_file() {
  if [[ "${WRITE_SMOKE_ENV}" != "1" || -z "${FUNDED_ETH_PRIVKEY}" ]]; then
    return
  fi
  cat >"${SMOKE_ENV_FILE}" <<EOF
# generated by scripts/playground_manual_deploy.sh
FUNDED_ETH_PRIVKEY='${FUNDED_ETH_PRIVKEY}'
EOF
  log "wrote smoke env file: ${SMOKE_ENV_FILE}"
}

install_wasm() {
  local wasm_path="target/wasm32-unknown-unknown/release/ic_evm_wrapper.wasm"
  if [[ ! -f "${wasm_path}" ]]; then
    log "wasm not found: ${wasm_path}"
    exit 1
  fi
  log "wasm size: $(ls -lh "${wasm_path}" | awk '{print $5}')"
  local wasm_out="target/wasm32-unknown-unknown/release/ic_evm_wrapper.final.wasm"
  scripts/build_wasm_postprocess.sh "${wasm_path}" "${wasm_out}"

  if [[ "${NETWORK}" == "playground" || "${NETWORK}" == "ic" ]]; then
    if [[ -z "${CANISTER_ID}" ]]; then
      log "CANISTER_ID is required for network=${NETWORK}"
      exit 1
    fi
    log "install wasm to canister_id=${CANISTER_ID} mode=${MODE}"
    echo "This will ${MODE} the canister ${CANISTER_ID}. Type YES to continue:"
    read -r confirm
    if [[ "${confirm}" != "YES" ]]; then
      log "aborted"
      exit 1
    fi
    local init_args
    if [[ -n "${FUNDED_ETH_PRIVKEY}" ]]; then
      init_args="$(build_init_args_for_current_identity_with_eth_sender "${FUNDED_ETH_PRIVKEY}" "1000000000000000000" "${FUNDED_ETH_AMOUNT}")"
    else
      init_args="$(build_init_args_for_current_identity 1000000000000000000)"
    fi
    icp canister install -n "${NETWORK}" --mode "${MODE}" --wasm "${wasm_out}" --args "${init_args}" "${CANISTER_ID}"
  else
    log "install wasm to canister_name=${CANISTER_NAME} mode=${MODE}"
    echo "This will ${MODE} the canister ${CANISTER_NAME}. Type YES to continue:"
    read -r confirm
    if [[ "${confirm}" != "YES" ]]; then
      log "aborted"
      exit 1
    fi
    local init_args
    if [[ -n "${FUNDED_ETH_PRIVKEY}" ]]; then
      init_args="$(build_init_args_for_current_identity_with_eth_sender "${FUNDED_ETH_PRIVKEY}" "1000000000000000000" "${FUNDED_ETH_AMOUNT}")"
    else
      init_args="$(build_init_args_for_current_identity 1000000000000000000)"
    fi
    icp canister install -n "${NETWORK}" --mode "${MODE}" --wasm "${wasm_out}" --args "${init_args}" "${CANISTER_NAME}"
  fi
}

ensure_funded_eth_privkey
write_smoke_env_file
build_wasm
install_wasm

if [[ "${RUN_SMOKE}" == "1" ]]; then
  if [[ "${NETWORK}" != "playground" ]]; then
    log "RUN_SMOKE=1 is only wired for playground_smoke.sh (network=playground)"
    exit 1
  fi
  log "running playground smoke"
  FUNDED_ETH_PRIVKEY="${FUNDED_ETH_PRIVKEY}" CANISTER_ID="${CANISTER_ID}" scripts/playground_smoke.sh
fi
