#!/usr/bin/env bash
# Four generated fixed-std predicate proofs; RefCell heap/Rust refinement unproved.
set -euo pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}/.."
export DYLD_LIBRARY_PATH="$PWD/.local/proof-tools/aeneas/libs${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
export RUSTUP_TOOLCHAIN=nightly-2026-09-17
export CARGO_TARGET_DIR="$PWD/.local/proof-tools/revm-root-target"
python3 - <<'RUN'
import hashlib,json,pathlib,subprocess,tempfile,sys
sys.path.insert(0,'scripts')
from audit_std_borrow_counter_llbc import inspect,negative_controls
root=pathlib.Path.cwd();profile=json.load(open('proofs/extraction/tool-patches/std-borrow-counter-profile.json'))
for mapping in [profile['sha256'],profile['base_source_sha256']]:
 for f,h in mapping.items():assert hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest()==h,f
with tempfile.TemporaryDirectory(prefix='kasane-dynamic-effects-') as tmp:
 tmp=pathlib.Path(tmp);dest=tmp/'counter.llbc'
 args=['.local/proof-tools/charon-gat-candidate/charon','cargo','--preset=aeneas','--mir','promoted','--error-on-warnings']
 for name in ['core::cell::is_reading','core::cell::is_writing']: args+=['--start-from',name,'--include',name]
 args+=['--include','core::cell::UNUSED']
 args+=['--dest-file',str(dest),'--','--manifest-path','crates/evm-core/Cargo.toml','--lib','--locked']
 proc=subprocess.run(args,capture_output=True,text=True,timeout=180)
 assert proc.returncode==0,proc.stdout+proc.stderr
 data=json.loads(dest.read_text());assert inspect(data)==profile['observation'];negative_controls(data)
 out=tmp/'lean';out.mkdir()
 proc=subprocess.run(['.local/proof-tools/aeneas-gat-source/aeneas','-backend','lean','-dest',str(out),'-namespace','StdBorrowCounter','-use-lean-modules','false','-abort-on-error','-warnings-as-errors',str(dest)],capture_output=True,text=True,timeout=180)
 assert proc.returncode==0,proc.stdout+proc.stderr
 assert len(list(out.rglob('*.lean')))==1
 assert (out/'Counter.lean').read_bytes()==(root/'proofs/extraction/u256-lean/StdBorrowCounterGenerated.lean').read_bytes(),'Generated execute drift'
print('Fresh actual std predicates and UNUSED initializer audited; eight witness modifications rejected; generated byte identity passed.')
RUN
cd proofs/extraction/u256-lean
for source in StdBorrowCounterGenerated StdBorrowCounterCorrespondence StdBorrowCounterAudit; do
 lake env lean -DwarningAsError=true -o ".lake/build/lib/lean/$source.olean" "$source.lean"
done
lake env leanchecker StdBorrowCounterCorrespondence
python3 - <<'NEG'
import pathlib,subprocess,tempfile
head,body=pathlib.Path('StdBorrowCounterAudit.lean').read_text().split('open Lean in',1)
with tempfile.TemporaryDirectory(prefix='execute-negative-',dir='.lake') as tmp:
 for label,mutation in {
  'axiom':'axiom bad : False\ntheorem negative : False := bad',
  'sorry':'theorem negative : False := by sorry',
  'native':'theorem negative : (1 : Nat) = 1 := by native_decide'}.items():
  f=pathlib.Path(tmp)/f'{label}.lean'
  f.write_text(head+'import Std.Tactic\nnamespace StdBorrowCounterCorrespondence\n'+mutation+'\nend StdBorrowCounterCorrespondence\nopen Lean in'+body)
  r=subprocess.run(['lake','env','lean',str(f)],capture_output=True,text=True)
  assert r.returncode!=0 and 'depends on forbidden axiom' in r.stdout+r.stderr,r.stdout+r.stderr
  print(label+' rejected by audit')
 prefix=pathlib.Path('StdBorrowCounterCorrespondence.lean').read_text().split('-- Fixed generated std predicates')[0]
 for label,claim in {
  'reading_positive':'is_reading (1#isize) = .ok true',
  'writing_positive_false':'is_writing (1#isize) = .ok false',
  'unused_zero':'is_reading (0#isize) = .ok false ∧ is_writing (0#isize) = .ok false'}.items():
  f=pathlib.Path(tmp)/f'{label}.lean'
  definitions=', '.join(name for name in ['is_reading','is_writing'] if name in claim)
  f.write_text(prefix+'example : '+claim+' := by simp ['+definitions+', UNUSED'+(', IScalar.lt_equiv' if '1#isize' in claim else '')+']\nend StdBorrowCounterCorrespondence\n')
  r=subprocess.run(['lake','env','lean','-DwarningAsError=true',str(f)],capture_output=True,text=True)
  assert r.returncode==0,r.stdout+r.stderr
  print(label+' positive claim accepted')
 for label,claim in {
  'reading_zero':'is_reading (0#isize) = .ok true',
  'writing_positive':'is_writing (1#isize) = .ok true' }.items():
  f=pathlib.Path(tmp)/f'{label}.lean'
  definitions=', '.join(name for name in ['is_reading','is_writing'] if name in claim)
  f.write_text(prefix+'example : '+claim+' := by simp ['+definitions+', UNUSED'+(', IScalar.lt_equiv' if '1#isize' in claim else '')+']\nend StdBorrowCounterCorrespondence\n')
  r=subprocess.run(['lake','env','lean',str(f)],capture_output=True,text=True)
  assert r.returncode!=0 and 'unsolved goals' in r.stdout+r.stderr,r.stdout+r.stderr
  print(label+' false std predicate claim rejected')

NEG
