#!/usr/bin/env bash
# Three actual generated execute-body proofs; unadopted extraction and Rust refinement unproved.
set -euo pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}/.."
export DYLD_LIBRARY_PATH="$PWD/.local/proof-tools/aeneas/libs${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
export RUSTUP_TOOLCHAIN=nightly-2026-09-17
export CARGO_TARGET_DIR="$PWD/.local/proof-tools/revm-root-target"
python3 - <<'RUN'
import hashlib,json,pathlib,subprocess,tempfile,sys
sys.path.insert(0,'scripts')
from audit_revm_execute_llbc import inspect,negative_controls
root=pathlib.Path.cwd();profile=json.load(open('proofs/extraction/tool-patches/revm-execute-dynamic-profile.json'))
for mapping in [profile['sha256'],profile['base_source_sha256']]:
 for f,h in mapping.items():assert hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest()==h,f
with tempfile.TemporaryDirectory(prefix='kasane-dynamic-effects-') as tmp:
 tmp=pathlib.Path(tmp);dest=tmp/'execute.llbc'
 args=['.local/proof-tools/charon-gat-candidate/charon','cargo','--preset=aeneas','--mir','promoted','--remove-unused-clauses','--error-on-warnings','--start-from','revm_interpreter::instructions::_::execute']
 for name in ['revm_interpreter::instructions::_::execute','revm_interpreter::instructions::Instruction','revm_interpreter::interpreter::Interpreter','revm_interpreter::gas::Gas']:
  args+=['--include',name]
 args+=['--dest-file',str(dest),'--','--manifest-path','crates/evm-core/Cargo.toml','--lib','--locked']
 proc=subprocess.run(args,capture_output=True,text=True,timeout=180)
 assert proc.returncode==0,proc.stdout+proc.stderr
 data=json.loads(dest.read_text());assert inspect(data)==profile['observation'];negative_controls(data)
 out=tmp/'lean';out.mkdir()
 proc=subprocess.run(['.local/proof-tools/aeneas-dynamic-effects/aeneas','-backend','lean','-dest',str(out),'-namespace','RevmExecuteDynamic','-use-lean-modules','false','-abort-on-error','-warnings-as-errors',str(dest)],capture_output=True,text=True,timeout=180)
 assert proc.returncode==0,proc.stdout+proc.stderr
 assert len(list(out.rglob('*.lean')))==1
 assert (out/'Execute.lean').read_bytes()==(root/'proofs/extraction/u256-lean/RevmExecuteGenerated.lean').read_bytes(),'Generated execute drift'
print('Fresh actual execute body/types/GAT metadata audited; eleven witness modifications rejected; generated byte identity passed.')
RUN
cd proofs/extraction/u256-lean
for source in RevmExecuteGenerated RevmExecuteCorrespondence RevmExecuteAudit; do
 lake env lean -DwarningAsError=true -o ".lake/build/lib/lean/$source.olean" "$source.lean"
done
lake env leanchecker RevmExecuteCorrespondence
python3 - <<'NEG'
import pathlib,subprocess,tempfile
head,body=pathlib.Path('RevmExecuteAudit.lean').read_text().split('open Lean in',1)
with tempfile.TemporaryDirectory(prefix='execute-negative-',dir='.lake') as tmp:
 for label,mutation in {
  'axiom':'axiom bad : False\ntheorem negative : False := bad',
  'sorry':'theorem negative : False := by sorry',
  'native':'theorem negative : (1 : Nat) = 1 := by native_decide'}.items():
  f=pathlib.Path(tmp)/f'{label}.lean'
  f.write_text(head+'import Std.Tactic\nnamespace RevmExecuteCorrespondence\n'+mutation+'\nend RevmExecuteCorrespondence\nopen Lean in'+body)
  r=subprocess.run(['lake','env','lean',str(f)],capture_output=True,text=True)
  assert r.returncode!=0 and 'depends on forbidden axiom' in r.stdout+r.stderr,r.stdout+r.stderr
  print(label+' rejected by audit')
 prefix=pathlib.Path('RevmExecuteCorrespondence.lean').read_text().split('-- Generated actual body')[0]
 for label,claim in {
  'ignored_callback':'instructions.Instruction.execute instruction context = .ok context',
  'forced_failure':'instructions.Instruction.execute instruction context = .fail .panic'}.items():
  f=pathlib.Path(tmp)/f'{label}.lean'
  f.write_text(prefix+'example : '+claim+' := by rfl\nend RevmExecuteCorrespondence\n')
  r=subprocess.run(['lake','env','lean',str(f)],capture_output=True,text=True)
  assert r.returncode!=0 and 'rfl' in r.stdout+r.stderr,r.stdout+r.stderr
  print(label+' false execute claim rejected')

NEG
