/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const InitArgs = IDL.Record({
    'kasane_canister' : IDL.Principal,
    'native_ledger_canister' : IDL.Principal,
    'allowed_assets' : IDL.Vec(IDL.Principal),
    'fee_ledger_canister' : IDL.Principal,
    'evm_gateway_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  const DispatchNativeWithdrawalRequestArgs = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'recipient' : IDL.Principal,
    'amount_e8s' : IDL.Nat,
  });
  const ApiError = IDL.Variant({
    'Internal' : IDL.Record({ 'code' : IDL.Text, 'message' : IDL.Text }),
    'Rejected' : IDL.Record({ 'code' : IDL.Text, 'message' : IDL.Text }),
    'InvalidArgument' : IDL.Record({ 'code' : IDL.Text, 'message' : IDL.Text }),
  });
  const FeePolicyView = IDL.Record({
    'fee_ledger_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const RequestStatus = IDL.Variant({
    'Queued' : IDL.Null,
    'Failed' : IDL.Null,
    'Succeeded' : IDL.Null,
    'Running' : IDL.Null,
  });
  const RequestKind = IDL.Variant({ 'Wrap' : IDL.Null, 'Unwrap' : IDL.Null });
  const RequestDispatchStatusView = IDL.Variant({
    'Queued' : IDL.Null,
    'Dispatching' : IDL.Null,
    'Dispatched' : IDL.Null,
    'DispatchFailed' : IDL.Null,
  });
  const RequestErrorView = IDL.Record({
    'code' : IDL.Text,
    'message' : IDL.Text,
  });
  const RequestOverview = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'status' : RequestStatus,
    'charged_fee_e8s' : IDL.Opt(IDL.Nat),
    'withdraw_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'kind' : RequestKind,
    'dispatch_status' : IDL.Opt(RequestDispatchStatusView),
    'error' : IDL.Opt(RequestErrorView),
    'dispatch_error' : IDL.Opt(IDL.Text),
    'fee_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'charged_gas_price_wei' : IDL.Opt(IDL.Nat),
    'withdraw_error_code' : IDL.Opt(IDL.Text),
    'ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'mint_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'pull_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const GetUnwrapRequirementsArgs = IDL.Record({
    'caller_evm_address' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'asset_id' : IDL.Principal,
  });
  const UnwrapReadiness = IDL.Variant({
    'TokenNotDeployed' : IDL.Null,
    'InsufficientAllowance' : IDL.Null,
    'InsufficientBalance' : IDL.Null,
    'Ready' : IDL.Null,
  });
  const GetUnwrapRequirementsOk = IDL.Record({
    'balance' : IDL.Nat,
    'wrapped_token_address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'approve_required' : IDL.Bool,
    'allowance' : IDL.Nat,
    'factory_address' : IDL.Vec(IDL.Nat8),
    'readiness' : UnwrapReadiness,
  });
  const StandardRecord = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const icrc21_consent_message_metadata = IDL.Record({
    'utc_offset_minutes' : IDL.Opt(IDL.Int16),
    'language' : IDL.Text,
  });
  const Icrc21LineDisplaySpec = IDL.Record({
    'characters_per_line' : IDL.Nat16,
    'lines_per_page' : IDL.Nat16,
  });
  const icrc21_consent_message_spec = IDL.Record({
    'metadata' : icrc21_consent_message_metadata,
    'device_spec' : IDL.Opt(
      IDL.Variant({
        'GenericDisplay' : IDL.Null,
        'LineDisplay' : Icrc21LineDisplaySpec,
      })
    ),
  });
  const icrc21_consent_message_request = IDL.Record({
    'arg' : IDL.Vec(IDL.Nat8),
    'method' : IDL.Text,
    'user_preferences' : icrc21_consent_message_spec,
  });
  const Icrc21LineDisplayPage = IDL.Record({ 'lines' : IDL.Vec(IDL.Text) });
  const Icrc21LineDisplayMessage = IDL.Record({
    'pages' : IDL.Vec(Icrc21LineDisplayPage),
  });
  const icrc21_consent_message = IDL.Variant({
    'LineDisplayMessage' : Icrc21LineDisplayMessage,
    'GenericDisplayMessage' : IDL.Text,
  });
  const icrc21_consent_info = IDL.Record({
    'metadata' : icrc21_consent_message_metadata,
    'consent_message' : icrc21_consent_message,
  });
  const icrc21_error_info = IDL.Record({ 'description' : IDL.Text });
  const icrc21_error = IDL.Variant({
    'GenericError' : IDL.Record({
      'description' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'InsufficientPayment' : icrc21_error_info,
    'UnsupportedCanisterCall' : icrc21_error_info,
    'ConsentMessageUnavailable' : icrc21_error_info,
  });
  const icrc21_consent_message_response = IDL.Variant({
    'Ok' : icrc21_consent_info,
    'Err' : icrc21_error,
  });
  const QuoteNativeDepositArgs = IDL.Record({
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
  });
  const QuoteNativeDepositOk = IDL.Record({
    'charged_fee_e8s' : IDL.Nat,
    'native_ledger_canister' : IDL.Principal,
    'fee_ledger_canister' : IDL.Principal,
  });
  const QuoteNativeWithdrawalArgs = IDL.Record({
    'recipient' : IDL.Principal,
    'amount_e8s' : IDL.Nat,
  });
  const QuoteNativeWithdrawalOk = IDL.Record({
    'native_ledger_canister' : IDL.Principal,
    'ledger_fee_e8s' : IDL.Nat,
    'receive_amount_e8s' : IDL.Nat,
  });
  const QuoteWrapRequestArgs = IDL.Record({
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'gas_limit' : IDL.Nat64,
    'asset_id' : IDL.Principal,
  });
  const QuoteWrapRequestOk = IDL.Record({
    'charged_fee_e8s' : IDL.Nat,
    'fee_ledger_canister' : IDL.Principal,
    'charged_gas_price_wei' : IDL.Nat,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const RecoverFailedWrapArgs = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
  });
  const RetryRequestArgs = IDL.Record({ 'request_id' : IDL.Vec(IDL.Nat8) });
  const SetFeePolicyArgs = IDL.Record({
    'fee_ledger_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const SubmitNativeDepositArgs = IDL.Record({
    'deposit_id' : IDL.Vec(IDL.Nat8),
    'max_fee_e8s' : IDL.Nat,
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'fee_ledger_canister' : IDL.Principal,
  });
  const SubmitNativeDepositOk = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'charged_fee_e8s' : IDL.Nat,
    'fee_ledger_tx_id' : IDL.Vec(IDL.Nat8),
  });
  const SubmitWrapRequestArgs = IDL.Record({
    'max_fee_e8s' : IDL.Nat,
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'fee_ledger_canister' : IDL.Principal,
    'gas_limit' : IDL.Nat64,
    'asset_id' : IDL.Principal,
    'quoted_gas_price_wei' : IDL.Nat,
    'evm_nonce' : IDL.Nat64,
  });
  const SubmitWrapRequestOk = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'charged_fee_e8s' : IDL.Nat,
    'fee_ledger_tx_id' : IDL.Vec(IDL.Nat8),
    'charged_gas_price_wei' : IDL.Nat,
  });
  
  return IDL.Service({
    'dispatch_native_withdrawal_request' : IDL.Func(
        [DispatchNativeWithdrawalRequestArgs],
        [
          IDL.Variant({
            'Ok' : IDL.Record({ 'request_id' : IDL.Vec(IDL.Nat8) }),
            'Err' : ApiError,
          }),
        ],
        [],
      ),
    'get_allowed_assets' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Vec(IDL.Principal), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_fee_policy' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : FeePolicyView, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_native_deposit_result' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(RequestOverview)],
        ['query'],
      ),
    'get_request' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(RequestOverview)],
        ['query'],
      ),
    'get_unwrap_requirements' : IDL.Func(
        [GetUnwrapRequirementsArgs],
        [IDL.Variant({ 'Ok' : GetUnwrapRequirementsOk, 'Err' : ApiError })],
        ['query'],
      ),
    'icrc10_supported_standards' : IDL.Func(
        [],
        [IDL.Vec(StandardRecord)],
        ['query'],
      ),
    'icrc21_canister_call_consent_message' : IDL.Func(
        [icrc21_consent_message_request],
        [icrc21_consent_message_response],
        [],
      ),
    'quote_native_deposit' : IDL.Func(
        [QuoteNativeDepositArgs],
        [IDL.Variant({ 'Ok' : QuoteNativeDepositOk, 'Err' : ApiError })],
        ['query'],
      ),
    'quote_native_withdrawal' : IDL.Func(
        [QuoteNativeWithdrawalArgs],
        [IDL.Variant({ 'Ok' : QuoteNativeWithdrawalOk, 'Err' : ApiError })],
        ['query'],
      ),
    'quote_wrap_request' : IDL.Func(
        [QuoteWrapRequestArgs],
        [IDL.Variant({ 'Ok' : QuoteWrapRequestOk, 'Err' : ApiError })],
        ['query'],
      ),
    'recover_failed_wrap' : IDL.Func(
        [RecoverFailedWrapArgs],
        [IDL.Variant({ 'Ok' : RequestOverview, 'Err' : ApiError })],
        [],
      ),
    'retry_native_deposit' : IDL.Func(
        [RetryRequestArgs],
        [IDL.Variant({ 'Ok' : RequestOverview, 'Err' : ApiError })],
        [],
      ),
    'retry_native_withdrawal' : IDL.Func(
        [RetryRequestArgs],
        [IDL.Variant({ 'Ok' : RequestOverview, 'Err' : ApiError })],
        [],
      ),
    'retry_request' : IDL.Func(
        [RetryRequestArgs],
        [IDL.Variant({ 'Ok' : RequestOverview, 'Err' : ApiError })],
        [],
      ),
    'set_allowed_assets' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_fee_policy' : IDL.Func(
        [SetFeePolicyArgs],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'submit_native_deposit' : IDL.Func(
        [SubmitNativeDepositArgs],
        [IDL.Variant({ 'Ok' : SubmitNativeDepositOk, 'Err' : ApiError })],
        [],
      ),
    'submit_wrap_request' : IDL.Func(
        [SubmitWrapRequestArgs],
        [IDL.Variant({ 'Ok' : SubmitWrapRequestOk, 'Err' : ApiError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => {
  const InitArgs = IDL.Record({
    'kasane_canister' : IDL.Principal,
    'native_ledger_canister' : IDL.Principal,
    'allowed_assets' : IDL.Vec(IDL.Principal),
    'fee_ledger_canister' : IDL.Principal,
    'evm_gateway_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  
  return [InitArgs];
};