/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const InitArgs = IDL.Record({
    'kasane_canister' : IDL.Principal,
    'allowed_assets' : IDL.Vec(IDL.Principal),
    'fee_ledger_canister' : IDL.Principal,
    'evm_gateway_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  const FeePolicyView = IDL.Record({
    'fee_ledger_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const RequestStatus = IDL.Variant({
    'Queued' : IDL.Null,
    'Failed' : IDL.Null,
    'Succeeded' : IDL.Null,
    'Running' : IDL.Null,
  });
  const RequestKind = IDL.Variant({ 'Wrap' : IDL.Null, 'Unwrap' : IDL.Null });
  const RequestDispatchStatusView = IDL.Variant({
    'Queued' : IDL.Null,
    'Dispatching' : IDL.Null,
    'Dispatched' : IDL.Null,
    'DispatchFailed' : IDL.Null,
  });
  const RequestErrorView = IDL.Record({
    'code' : IDL.Text,
    'message' : IDL.Text,
  });
  const RequestOverview = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'status' : RequestStatus,
    'charged_fee_e8s' : IDL.Opt(IDL.Nat),
    'withdraw_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'kind' : RequestKind,
    'dispatch_status' : IDL.Opt(RequestDispatchStatusView),
    'error' : IDL.Opt(RequestErrorView),
    'dispatch_error' : IDL.Opt(IDL.Text),
    'fee_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'charged_gas_price_wei' : IDL.Opt(IDL.Nat),
    'withdraw_error_code' : IDL.Opt(IDL.Text),
    'ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'mint_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'pull_ledger_tx_id' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const GetUnwrapRequirementsArgs = IDL.Record({
    'caller_evm_address' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'asset_id' : IDL.Principal,
  });
  const UnwrapReadiness = IDL.Variant({
    'TokenNotDeployed' : IDL.Null,
    'InsufficientAllowance' : IDL.Null,
    'InsufficientBalance' : IDL.Null,
    'Ready' : IDL.Null,
  });
  const GetUnwrapRequirementsOk = IDL.Record({
    'balance' : IDL.Nat,
    'wrapped_token_address' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'approve_required' : IDL.Bool,
    'allowance' : IDL.Nat,
    'factory_address' : IDL.Vec(IDL.Nat8),
    'readiness' : UnwrapReadiness,
  });
  const ApiError = IDL.Variant({
    'Internal' : IDL.Record({ 'code' : IDL.Text, 'message' : IDL.Text }),
    'Rejected' : IDL.Record({ 'code' : IDL.Text, 'message' : IDL.Text }),
    'InvalidArgument' : IDL.Record({ 'code' : IDL.Text, 'message' : IDL.Text }),
  });
  const QuoteWrapRequestArgs = IDL.Record({
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'gas_limit' : IDL.Nat64,
    'asset_id' : IDL.Principal,
  });
  const QuoteWrapRequestOk = IDL.Record({
    'charged_fee_e8s' : IDL.Nat,
    'fee_ledger_canister' : IDL.Principal,
    'charged_gas_price_wei' : IDL.Nat,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const RecoverFailedWrapArgs = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
  });
  const RetryRequestArgs = IDL.Record({ 'request_id' : IDL.Vec(IDL.Nat8) });
  const SetFeePolicyArgs = IDL.Record({
    'fee_ledger_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
  });
  const SubmitWrapRequestArgs = IDL.Record({
    'evm_recipient' : IDL.Vec(IDL.Nat8),
    'amount_e8s' : IDL.Nat,
    'gas_limit' : IDL.Nat64,
    'asset_id' : IDL.Principal,
    'evm_nonce' : IDL.Nat64,
  });
  const SubmitWrapRequestOk = IDL.Record({
    'request_id' : IDL.Vec(IDL.Nat8),
    'charged_fee_e8s' : IDL.Nat,
    'fee_ledger_tx_id' : IDL.Vec(IDL.Nat8),
    'charged_gas_price_wei' : IDL.Nat,
  });
  
  return IDL.Service({
    'get_allowed_assets' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Vec(IDL.Principal), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_fee_policy' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : FeePolicyView, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_request' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(RequestOverview)],
        ['query'],
      ),
    'get_unwrap_requirements' : IDL.Func(
        [GetUnwrapRequirementsArgs],
        [IDL.Variant({ 'Ok' : GetUnwrapRequirementsOk, 'Err' : ApiError })],
        ['query'],
      ),
    'quote_wrap_request' : IDL.Func(
        [QuoteWrapRequestArgs],
        [IDL.Variant({ 'Ok' : QuoteWrapRequestOk, 'Err' : ApiError })],
        ['query'],
      ),
    'recover_failed_wrap' : IDL.Func(
        [RecoverFailedWrapArgs],
        [IDL.Variant({ 'Ok' : RequestOverview, 'Err' : ApiError })],
        [],
      ),
    'retry_request' : IDL.Func(
        [RetryRequestArgs],
        [IDL.Variant({ 'Ok' : RequestOverview, 'Err' : ApiError })],
        [],
      ),
    'set_allowed_assets' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_fee_policy' : IDL.Func(
        [SetFeePolicyArgs],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'submit_wrap_request' : IDL.Func(
        [SubmitWrapRequestArgs],
        [IDL.Variant({ 'Ok' : SubmitWrapRequestOk, 'Err' : ApiError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => {
  const InitArgs = IDL.Record({
    'kasane_canister' : IDL.Principal,
    'allowed_assets' : IDL.Vec(IDL.Principal),
    'fee_ledger_canister' : IDL.Principal,
    'evm_gateway_canister' : IDL.Principal,
    'gas_price_buffer_bps' : IDL.Nat32,
    'cycle_fee_e8s' : IDL.Nat64,
    'wrap_factory_address' : IDL.Vec(IDL.Nat8),
  });
  
  return [InitArgs];
};