/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.3.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApiError = {
    'Internal' : { 'code' : string, 'message' : string }
  } |
  { 'Rejected' : { 'code' : string, 'message' : string } } |
  { 'InvalidArgument' : { 'code' : string, 'message' : string } };
export interface FeePolicyView {
  'fee_ledger_canister' : Principal,
  'gas_price_buffer_bps' : number,
  'cycle_fee_e8s' : bigint,
}
export interface GetUnwrapRequirementsArgs {
  'caller_evm_address' : Uint8Array,
  'amount_e8s' : bigint,
  'asset_id' : Principal,
}
export interface GetUnwrapRequirementsOk {
  'balance' : bigint,
  'wrapped_token_address' : [] | [Uint8Array],
  'approve_required' : boolean,
  'allowance' : bigint,
  'factory_address' : Uint8Array,
  'readiness' : UnwrapReadiness,
}
export interface InitArgs {
  'kasane_canister' : Principal,
  'allowed_assets' : Array<Principal>,
  'fee_ledger_canister' : Principal,
  'evm_gateway_canister' : Principal,
  'gas_price_buffer_bps' : number,
  'cycle_fee_e8s' : bigint,
  'wrap_factory_address' : Uint8Array,
}
export interface QuoteWrapRequestArgs {
  'evm_recipient' : Uint8Array,
  'amount_e8s' : bigint,
  'gas_limit' : bigint,
  'asset_id' : Principal,
}
export interface QuoteWrapRequestOk {
  'charged_fee_e8s' : bigint,
  'fee_ledger_canister' : Principal,
  'charged_gas_price_wei' : bigint,
  'cycle_fee_e8s' : bigint,
}
export interface RecoverFailedWrapArgs { 'request_id' : Uint8Array }
export type RequestDispatchStatusView = { 'Queued' : null } |
  { 'Dispatching' : null } |
  { 'Dispatched' : null } |
  { 'DispatchFailed' : null };
export interface RequestErrorView { 'code' : string, 'message' : string }
export type RequestKind = { 'Wrap' : null } |
  { 'Unwrap' : null };
export interface RequestOverview {
  'request_id' : Uint8Array,
  'status' : RequestStatus,
  'charged_fee_e8s' : [] | [bigint],
  'withdraw_ledger_tx_id' : [] | [Uint8Array],
  'kind' : RequestKind,
  'dispatch_status' : [] | [RequestDispatchStatusView],
  'error' : [] | [RequestErrorView],
  'dispatch_error' : [] | [string],
  'fee_ledger_tx_id' : [] | [Uint8Array],
  'charged_gas_price_wei' : [] | [bigint],
  'withdraw_error_code' : [] | [string],
  'ledger_tx_id' : [] | [Uint8Array],
  'mint_tx_id' : [] | [Uint8Array],
  'pull_ledger_tx_id' : [] | [Uint8Array],
}
export type RequestStatus = { 'Queued' : null } |
  { 'Failed' : null } |
  { 'Succeeded' : null } |
  { 'Running' : null };
export interface RetryRequestArgs { 'request_id' : Uint8Array }
export interface SetFeePolicyArgs {
  'fee_ledger_canister' : Principal,
  'gas_price_buffer_bps' : number,
  'cycle_fee_e8s' : bigint,
}
export interface SubmitWrapRequestArgs {
  'evm_recipient' : Uint8Array,
  'amount_e8s' : bigint,
  'gas_limit' : bigint,
  'asset_id' : Principal,
  'evm_nonce' : bigint,
}
export interface SubmitWrapRequestOk {
  'request_id' : Uint8Array,
  'charged_fee_e8s' : bigint,
  'fee_ledger_tx_id' : Uint8Array,
  'charged_gas_price_wei' : bigint,
}
export type UnwrapReadiness = { 'TokenNotDeployed' : null } |
  { 'InsufficientAllowance' : null } |
  { 'InsufficientBalance' : null } |
  { 'Ready' : null };
export interface _SERVICE {
  'get_allowed_assets' : ActorMethod<
    [],
    { 'Ok' : Array<Principal> } |
      { 'Err' : string }
  >,
  'get_fee_policy' : ActorMethod<
    [],
    { 'Ok' : FeePolicyView } |
      { 'Err' : string }
  >,
  'get_request' : ActorMethod<[Uint8Array], [] | [RequestOverview]>,
  'get_unwrap_requirements' : ActorMethod<
    [GetUnwrapRequirementsArgs],
    { 'Ok' : GetUnwrapRequirementsOk } |
      { 'Err' : ApiError }
  >,
  'quote_wrap_request' : ActorMethod<
    [QuoteWrapRequestArgs],
    { 'Ok' : QuoteWrapRequestOk } |
      { 'Err' : ApiError }
  >,
  'recover_failed_wrap' : ActorMethod<
    [RecoverFailedWrapArgs],
    { 'Ok' : RequestOverview } |
      { 'Err' : ApiError }
  >,
  'retry_request' : ActorMethod<
    [RetryRequestArgs],
    { 'Ok' : RequestOverview } |
      { 'Err' : ApiError }
  >,
  'set_allowed_assets' : ActorMethod<
    [Array<Principal>],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'set_fee_policy' : ActorMethod<
    [SetFeePolicyArgs],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'submit_wrap_request' : ActorMethod<
    [SubmitWrapRequestArgs],
    { 'Ok' : SubmitWrapRequestOk } |
      { 'Err' : ApiError }
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];