(* Exact, scoped option profile for retaining panic_fmt arguments.
   The preset path remains unchanged; this alternative is not a global relaxation. *)
open Aeneas.LlbcAst

let formatting_source_options (o : cli_options) =
  o = {
    ullbc = false;
    precise_drops = false;
    mir = Some Optimized;
    rustc_args = [];
    targets = [];
    sysroot = None;
    monomorphize = false;
    monomorphize_mut = None;
    start_from = ["kasane_ledger_timestamp_probe::add_time"; "kasane_ledger_timestamp_probe::sub_time"];
    start_from_if_exists = [];
    start_from_attribute = [];
    start_from_pub = false;
    included = ["core::time::Duration"; "core::num::niche_types::Nanoseconds"; "core::num::niche_types::_::new_unchecked"; "core::num::niche_types::_::as_inner"; "core::time::_::from_nanos"; "core::time::_::as_nanos"; "core::time::NANOS_PER_SEC"; "core::convert::num::_::try_from"; "core::num::error::TryFromIntError"; "core::result::_::unwrap"; "core::result::unwrap_failed"; "core::fmt::rt::Argument"; "core::fmt::rt::ArgumentType"; "core::fmt::Arguments"; "core::fmt::rt::_::new_debug"; "core::fmt::rt::_::new_display"; "core::fmt::_::new"];
    opaque = ["core::panicking::panic_fmt"];
    exclude = [];
    extract_opaque_bodies = false;
    translate_all_methods = false;
    eager_vtables = false;
    duplicate_defaulted_methods = false;
    lift_associated_types = ["*"];
    hide_marker_traits = true;
    hide_allocator = true;
    no_doc_comments = false;
    remove_unused_clauses = false;
    remove_unused_self_clauses = true;
    remove_adt_clauses = true;
    desugar_drops = false;
    resugar_drops = false;
    detect_drop_flags = false;
    ops_to_function_calls = true;
    index_to_function_calls = true;
    treat_box_as_builtin = true;
    no_gen_tuple_structs = true;
    raw_consts = false;
    consts = None;
    unsized_strings = false;
    reconstruct_fallible_operations = true;
    reconstruct_panic_calls = false;
    reconstruct_asserts = true;
    reconstruct_matches = true;
    deallocate_all_locals = true;
    unbind_item_vars = true;
    print_original_ullbc = false;
    print_ullbc = false;
    print_built_llbc = false;
    print_llbc = false;
    print_layouts = false;
    print_safety = false;
    dest_dir = None;
    dest_file = o.dest_file;
    no_dedup_serialized_ast = false;
    format = None;
    no_serialize = false;
    skip_borrowck = false;
    erase_body_lifetimes = false;
    no_typecheck = false;
    no_normalize = false;
    no_reorder_decls = false;
    no_compute_layout_guarantees = false;
    abort_on_error = false;
    error_on_warnings = true;
    preset = None;
  }
